Repository python-pillow/Pillow, pull requests merged in 2018-12, with the labels that each got.

#3479 Allow arbitrary number of comment extension subblocks
  Tests/images/hopper_zero_comment_subblocks.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#3461 Close exclusive fp before discarding
  Tests/test_file_cur.py
  Tests/test_file_icns.py
  Tests/test_file_png.py
  src/PIL/IcnsImagePlugin.py
  src/PIL/PngImagePlugin.py
Labels: File Closing

#3261 Resolve __fp when closing and deleting
  Tests/test_file_dcx.py
  Tests/test_file_fli.py
  Tests/test_file_gif.py
  Tests/test_file_im.py
  Tests/test_file_mpo.py
  Tests/test_file_spider.py
  Tests/test_file_tiff.py
  src/PIL/DcxImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/Image.py
  src/PIL/MicImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: File Closing

#3467 CI: Allow lint job to fail
  .travis.yml
  Tests/createfontdatachunk.py
  Tests/helper.py
  Tests/test_imagemath.py
  mp_compile.py
  setup.cfg
  src/PIL/Image.py
  src/PIL/ImageFilter.py
  src/PIL/ImageFont.py
  src/PIL/ImageQt.py
  src/PIL/ImageTk.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/PdfParser.py
  src/PIL/PngImagePlugin.py
  src/PIL/PyAccess.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/_util.py
  winbuild/build.py
  winbuild/build_dep.py
  winbuild/config.py
Labels: Testing

#3488 Travis CI: Upgrade PyPy from 5.8.0 to 6.0
  .travis.yml
  docs/installation.rst
Labels: Build

#3490 Updated open files documentation
  docs/reference/open_files.rst
  src/PIL/Image.py
Labels: Documentation

#3486 Docs: Add page of deprecations and removals
  docs/deprecations.rst
  docs/index.rst
Labels: Documentation

#3187 Wait until mode is normalized to copy im.info into encoderinfo
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#3350 Added custom int and float TIFF tags
  Tests/test_file_libtiff.py
  Tests/test_file_tiff_metadata.py
  Tests/versions.py
  src/PIL/TiffImagePlugin.py
  src/PIL/TiffTags.py
  src/_imaging.c
  src/encode.c
  src/libImaging/TiffDecode.c
  src/libImaging/TiffDecode.h
Labels: TIFF

#3511 Corrected docstring
  src/PIL/Image.py
Labels: Documentation

#3513 Added custom string TIFF tags
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
  src/PIL/TiffTags.py
  src/encode.c
Labels: TIFF

#3245 Lookup ld.so.cache instead of hardcoding search paths
  setup.py
Labels: Linux

#3516 Allow EPS tests that do not require Ghostscript
  Tests/test_file_eps.py
Labels: Testing
