Repository python-pillow/Pillow, pull requests merged in 2018-06, with the labels that each got.

#3175 Temporarily use --no-cache-dir for pip on mingw32
  winbuild/appveyor_install_msys2_deps.sh
Labels: Build, Windows

#3170 Update Python 2 doc URLs to Python 3
  Makefile
  docs/reference/Image.rst
Labels: Documentation

#3164 Improved Image.transform documentation
  src/PIL/Image.py
Labels: Documentation

#2979 Remove redundant travis_after_all stuff
  .travis.yml
  .travis/after_success.sh
  MANIFEST.in
  build_children.sh
Labels: Build, Cleanup

#3214 Added file handling links in documentation
  docs/reference/open_files.rst
  src/PIL/Image.py
Labels: Documentation

#3165 Use travis_retry for docker pull to avoid occasional network timeouts
  .travis.yml
Labels: Build
