Repository python-pillow/Pillow, pull requests merged in 2018-10, with the labels that each got.

#3397 Fixed documentation on bilevel conversion
  src/PIL/Image.py
Labels: Documentation

#3404 Minor ImageDraw documentation improvement
  src/PIL/ImageDraw.py
Labels: Documentation

#3405 Docs: update CI targets matrix
  docs/installation.rst
Labels: Documentation

#3409 Optimise ImageOps.fit by combining resize and crop
  docs/releasenotes/5.4.0.rst
  docs/releasenotes/index.rst
  src/PIL/ImageOps.py
Labels: Enhancement, Performance

#3417 Only ask for YCbCr->RGB libtiff conversion for jpeg-compressed tiffs
  src/libImaging/TiffDecode.c
Labels: Bug, TIFF

#3423 Fix some tests
  Tests/test_features.py
  Tests/test_format_hsv.py
  Tests/test_pyroma.py
Labels: Testing

#3424 Improved ImageGrab tests
  Tests/test_imagegrab.py
Labels: Testing

#3435 Install project using pip in ReadTheDocs build
  .readthedocs.yml
Labels: Documentation

#3385 Change tuple background to global color table index when saving as GIF
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#3443 Re-add the downloads badge
  README.rst
  docs/index.rst
Labels: Documentation
