Repository python-pillow/Pillow, pull requests merged in 2018-03, with the labels that each got.

#2988 Fix AppVeyor master builds for forks
  appveyor.yml
Labels: Build, Windows

#3007 Add support for BLP file format
  CHANGES.rst
  Tests/images/blp/blp1_jpeg.blp
  Tests/images/blp/blp2_dxt1.blp
  Tests/images/blp/blp2_dxt1.png
  Tests/images/blp/blp2_dxt1a.blp
  Tests/images/blp/blp2_dxt1a.png
  Tests/images/blp/blp2_raw.blp
  Tests/images/blp/blp2_raw.png
  Tests/test_file_blp.py
  src/PIL/BlpImagePlugin.py
  src/PIL/__init__.py
  tox.ini
Labels: Needs Documentation, Needs Release Notes

#3021 Docs: Move intro text below its header
  docs/reference/Image.rst
Labels: Documentation
