Repository python-pillow/Pillow, pull requests merged in 2018-11, with the labels that each got.

#3451 Added release notes for #3406
  docs/reference/PixelAccess.rst
  docs/reference/PyAccess.rst
  docs/releasenotes/5.4.0.rst
Labels: Documentation

#3392 Update tests
  Tests/check_large_memory.py
  Tests/helper.py
  Tests/test_000_sanity.py
  Tests/test_color_lut.py
  Tests/test_features.py
  Tests/test_file_eps.py
  Tests/test_file_ico.py
  Tests/test_file_libtiff.py
  Tests/test_file_png.py
  Tests/test_file_tiff.py
  Tests/test_file_tiff_metadata.py
  Tests/test_file_webp_alpha.py
  Tests/test_file_webp_lossless.py
  Tests/test_image.py
  Tests/test_image_convert.py
  Tests/test_image_getdata.py
  Tests/test_image_getextrema.py
  Tests/test_image_resample.py
  Tests/test_imagedraw.py
  Tests/test_imagefile.py
  Tests/test_imagetk.py
  Tests/test_lib_pack.py
  Tests/test_pyroma.py
  Tests/test_qt_image_toqimage.py
Labels: Testing

#3412 CI: Fix diff-cover, move linting to own job, name the jobs
  .travis.yml
  .travis/after_success.sh
  depends/diffcover-install.sh
  depends/diffcover-run.sh
Labels: Build

#3459 Added __main__ code to test_core_resources
  Tests/test_core_resources.py
Labels: Testing

#3472 Travis CI: Remove 'sudo' config
  .travis.yml
Labels: Build
