Repository python-pillow/Pillow, pull requests merged in 2019-01, with the labels that each got.

#3521 Update 5.4.0 release notes
  docs/releasenotes/5.4.0.rst
Labels: Documentation

#3523 Added updating Pillow in docker-images to RELEASING
  RELEASING.md
Labels: Documentation

#3525 Detect mimetypes
  Tests/images/balloon.jpf
  Tests/test_file_jpeg2k.py
  Tests/test_file_png.py
  Tests/test_file_sgi.py
  src/PIL/ImageFile.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/SgiImagePlugin.py
Labels: Regression

#3544 Add 5.4.1 release notes
  docs/releasenotes/5.4.1.rst
  docs/releasenotes/index.rst
Labels: Documentation

#3540 Only close __fp if not fp
  Tests/images/hopper_unknown_pixel_mode.tif
  Tests/test_file_tiff.py
  src/PIL/DcxImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/Image.py
  src/PIL/MicImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: File Closing

#3524 CI: Run check-manifest in lint job
  .travis.yml
Labels: Build

#3560 Install optional dependencies in tox environment
  tox.ini
Labels: Testing

#3562 Update release checklist
  .gitignore
  RELEASING.md
Labels: Documentation

#3582 Docs: Release history is visible at PyPI
  docs/installation.rst
Labels: Documentation

#3585 Fix Travis CI: Only start Xvfb for Qt builds
  .travis.yml
Labels: Build

#3595 Moved docs JS file into custom directory
  docs/conf.py
  docs/resources/js/script.js
Labels: Documentation

#3587 Added Ghostscript to AppVeyor
  winbuild/build_dep.py
  winbuild/config.py
Labels: Testing, Windows

#3598 Remove deprecated PIL.OleFileIO in favour of olefile Python package
  src/PIL/OleFileIO.py
Labels: Removal

#3599 Remove deprecated ImageOps functions
  Tests/test_imageops_usm.py
  src/PIL/ImageOps.py
Labels: Removal

#3600 Document removals
  docs/deprecations.rst
  docs/releasenotes/4.3.0.rst
  docs/releasenotes/6.0.0.rst
  docs/releasenotes/index.rst
Labels: Documentation, Removal
