Repository python-pillow/Pillow, pull requests merged in 2019-03, with the labels that each got.

#3679 Document removal of VERSION
  docs/deprecations.rst
  docs/releasenotes/6.0.0.rst
Labels: Documentation

#3686 Use pillow-wheels update script
  RELEASING.md
Labels: Documentation

#3682 Document Python 2.7 will be dropped on 2020-01-01
  docs/deprecations.rst
  docs/installation.rst
  docs/releasenotes/6.0.0.rst
Labels: Deprecation, Documentation

#3670 Add Azure Pipelines CI
  .azure-pipelines/jobs/lint.yml
  .azure-pipelines/jobs/test-docker.yml
  MANIFEST.in
  azure-pipelines.yml
Labels: Build, Testing

#3696 Update docs: macOS saves to a temp PNG before showing
  src/PIL/Image.py
Labels: Documentation

#3700 Updated list of Unix utilities used to show an image
  src/PIL/Image.py
Labels: Documentation

#3672 Corrected length of Tiff BYTE tags
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#3673 Added reading of DDS uncompressed RGB data
  Tests/images/uncompressed_rgb.dds
  Tests/images/uncompressed_rgb.png
  Tests/images/unimplemented_dxgi_format.dds
  Tests/images/unimplemented_pixel_format.dds
  Tests/test_file_dds.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/6.0.0.rst
  src/PIL/DdsImagePlugin.py
Labels: Enhancement

#3699 Add option to set dither param on quantize
  Tests/test_image_quantize.py
  docs/releasenotes/6.0.0.rst
  src/PIL/Image.py
Labels: Enhancement

#3674 Added EXIF support for PNG
  Tests/images/exif.png
  Tests/test_file_png.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/6.0.0.rst
  src/PIL/PngImagePlugin.py
Labels: Exif

#3489 Add reading old-JPEG compressed TIFFs
  Tests/images/old-style-jpeg-compression.png
  Tests/images/old-style-jpeg-compression.tif
  Tests/test_file_libtiff.py
  docs/releasenotes/6.0.0.rst
  src/PIL/TiffImagePlugin.py
  src/libImaging/TiffDecode.c
Labels: TIFF

#3698 Only close exclusive fp on Image __exit__
  Tests/test_image_load.py
  src/PIL/Image.py
Labels: File Closing

#3551 Remove unused C hashtable functions
  src/libImaging/QuantHash.c
  src/libImaging/QuantHash.h
Labels: Hasn't worked in 20 years, Removal

#3722 Corrected seek documentation
  docs/handbook/image-file-formats.rst
  docs/handbook/tutorial.rst
  src/PIL/Image.py
Labels: Documentation

#3683 Only close original fp in __del__ and __exit__ if original fp is exclusive
  Tests/test_image.py
  src/PIL/Image.py
  src/PIL/WebPImagePlugin.py
Labels: File Closing

#3736 Remove additional references to removed handles_eof
  docs/reference/open_files.rst
  src/PIL/ImageFile.py
Labels: Documentation

#3737 Add backticks around Python classes and modules in open_files.rst
  docs/reference/open_files.rst
Labels: Documentation

#3751 AppVeyor: Upgrade to PyPy 7.1.0
  winbuild/appveyor_install_pypy.cmd
Labels: Build, Windows

#3729 Improved docstring
  src/PIL/SpiderImagePlugin.py
Labels: Documentation

#3498 Cache EXIF information
  src/PIL/JpegImagePlugin.py
Labels: Exif, JPEG, Performance

#3713 Fixed TIFF bug when seeking backwards and then forwards
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#3740 Corrected remap_palette documentation
  src/PIL/Image.py
Labels: Documentation

#3743 I;16 mode transpose support release notes
  docs/releasenotes/6.0.0.rst
Labels: Documentation

#3724 Ensure image is mutable before saving
  Tests/test_image.py
  src/PIL/Image.py
Labels: Bug

#3701 Read Photoshop resolution data
  Tests/test_file_jpeg.py
  src/PIL/IptcImagePlugin.py
  src/PIL/JpegImagePlugin.py
Labels: Enhancement, JPEG

#3588 Change size of MPO image to match frame
  Tests/images/sugarshack_frame_size.mpo
  Tests/test_file_mpo.py
  src/PIL/MpoImagePlugin.py
Labels: Bug, Exif

#3757 Updated lcms tested versions
  docs/installation.rst
Labels: Documentation

#3714 Improvements to TIFF is_animated and n_frames
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: Performance, TIFF

#3658 Fast MPO open
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
Labels: Performance

#3720 Describe multiframe features for TIFF/GIF
  docs/handbook/image-file-formats.rst
Labels: Documentation

#3637 Docs: Link to Codecov rather than Coveralls
  .github/CONTRIBUTING.md
  README.rst
  docs/index.rst
Labels: Documentation
