Repository python-pillow/Pillow, pull requests merged in 2019-06, with the labels that each got.

#3881 Link method in docs
  docs/handbook/overview.rst
Labels: Documentation

#3882 Tighten fixed pyroma test
  Tests/test_pyroma.py
Labels: Testing

#3906 Renamed OS X reference to macOS
  docs/installation.rst
Labels: Documentation

#3893 Simplified definition of BMP values
  src/PIL/BmpImagePlugin.py
Labels: Cleanup

#3896 Changed Preview application path so that it is no longer static
  src/PIL/ImageShow.py
Labels: Bug, macOS

#3759 Improve handling of PSD frames
  Tests/test_file_psd.py
  Tests/test_imagesequence.py
  src/PIL/ImageSequence.py
  src/PIL/PsdImagePlugin.py
Labels: Bug

#3869 Do not down-convert if image is LA when showing with PNG format
  Tests/test_image_mode.py
  Tests/test_imageshow.py
  src/PIL/ImageMode.py
  src/PIL/ImageShow.py
Labels: Enhancement

#3860 Replace non-ascii quotes from docstring
  src/PIL/ImageFont.py
Labels: Documentation

#3802 Added variation font support
  Tests/fonts/AdobeVFPrototype.ttf
  Tests/fonts/LICENSE.txt
  Tests/fonts/TINY5x3GX.ttf
  Tests/images/variation_adobe.png
  Tests/images/variation_adobe_axes.png
  Tests/images/variation_adobe_name.png
  Tests/images/variation_tiny.png
  Tests/images/variation_tiny_axes.png
  Tests/images/variation_tiny_name.png
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: Enhancement, Fonts

#3870 Add __main__.py to output basic format and support information
  Tests/test_features.py
  Tests/test_main.py
  src/PIL/__main__.py
  src/PIL/features.py
Labels: Enhancement

#3864 Fixed bugs in calculating text size
  Tests/fonts/ArefRuqaa-Regular.ttf
  Tests/fonts/LICENSE.txt
  Tests/images/test_x_max_and_y_offset.png
  Tests/images/test_y_offset.png
  Tests/test_imagefontctl.py
  src/_imagingft.c
Labels: Font Rendering

#3903 Advice on general questions, bug reports and feature requests
  .github/ISSUE_TEMPLATE.md
Labels: Documentation

#3911 Added release notes for #3802 and #3856
  docs/releasenotes/6.1.0.rst
Labels: Documentation

#3858 Fix SPARC memory alignment issues in Pack/Unpack functions
  src/libImaging/Pack.c
  src/libImaging/Unpack.c
Labels: SPARC

#3912 Fixed crash when loading non-font bytes
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: Fonts

#3922 Improved parameter documentation
  src/PIL/_binary.py
Labels: Documentation

#3776 Documentation for Image module
  .gitignore
  docs/reference/Image.rst
Labels: Documentation

#3608 Added an `image.entropy()` method (second revision)
  Tests/test_image_entropy.py
  selftest.py
  src/PIL/Image.py
  src/_imaging.c
Labels: Enhancement

#3795 Updated TIFF tile descriptors to match current decoding functionality
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#3923 Use unsigned int to store TIFF IFD offsets
  src/decode.c
  src/libImaging/TiffDecode.c
  src/libImaging/TiffDecode.h
Labels: TIFF

#3708 Create GIF deltas from background colour of GIF frames if disposal mode is 2
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#3778 Added ImageSequence all_frames
  Tests/test_imagesequence.py
  docs/releasenotes/6.1.0.rst
  src/PIL/ImageSequence.py
Labels: Enhancement

#3926 Add TIFFTAG_SAMPLEFORMAT to blocklist
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#3899 Consider I;16 pixel size when drawing
  Tests/images/imagedraw_rectangle_I.png
  Tests/test_imagedraw.py
  src/libImaging/Draw.c
Labels: Bug

#3780 Update Py_UNICODE to Py_UCS4
  Tests/fonts/LICENSE.txt
  Tests/fonts/NotoSansSymbols-Regular.ttf
  Tests/images/unicode_extended.png
  Tests/test_imagefont.py
  src/_imagingft.c
Labels: Font Rendering

#3861 Improve encoding of TIFF tags
  Tests/test_file_libtiff.py
  docs/handbook/image-file-formats.rst
  src/PIL/TiffImagePlugin.py
  src/encode.c
  src/libImaging/TiffDecode.c
  src/libImaging/TiffDecode.h
Labels: Needs Release Notes, TIFF
