Repository python-pillow/Pillow, pull requests merged in 2019-11, with the labels that each got.

#4183 Add support for Fedora 31
  .github/workflows/test-docker.yml
  .travis.yml
  azure-pipelines.yml
  docs/installation.rst
Labels: Build

#4176 Use pillow-depends on HTTPError
  winbuild/build_dep.py
  winbuild/config.py
  winbuild/fetch.py
Labels: Windows

#4190 Ignore UserWarnings in TestFileTiff::test_string_dimension
  Tests/test_file_tiff.py
Labels: Testing

#4185 Update docs for 7.0.0
  docs/deprecations.rst
  docs/releasenotes/7.0.0.rst
  docs/releasenotes/index.rst
Labels: Documentation

#4189 Report details about Pillow when running tests
  Tests/conftest.py
Labels: Testing

#4196 GHA: Test Python 3.8 on Linux/macOS
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Build, Testing

#4186 Enabled page heap verification
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Testing, Windows

#4201 GitHub Actions: Update to windows-2019
  .github/workflows/test-windows.yml
  winbuild/lcms2_patch.ps1
Labels: Build, Windows

#4199 Test on latest available macOS and Ubuntu
  .github/workflows/test.yml
Labels: Build, Linux, macOS

#4203 AppVeyor: Test on Python 3.8
  .appveyor.yml
  winbuild/config.py
Labels: Build, Windows

#4171 Corrected DdsImagePlugin setting info gamma
  Tests/images/DXGI_FORMAT_BC7_UNORM_SRGB.dds
  Tests/images/DXGI_FORMAT_BC7_UNORM_SRGB.png
  Tests/test_file_dds.py
  src/PIL/DdsImagePlugin.py
Labels: Bug

#4116 Fixed freeing unallocated pointer when resizing with height too large
  Tests/test_image_resample.py
  src/libImaging/Resample.c
Labels: Memory

#4105 IFDRational init cleanup
  src/PIL/TiffImagePlugin.py
Labels: Cleanup

#4205 Include Pillow version in Windows wheel warning
  setup.py
Labels: Windows

#4208 Add Documentation and Github URLs for PyPi
  setup.py
Labels: Documentation

#4197 Remove deprecated __version__ from plugins
  docs/deprecations.rst
  docs/releasenotes/7.0.0.rst
  src/PIL/BmpImagePlugin.py
  src/PIL/CurImagePlugin.py
  src/PIL/DcxImagePlugin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/FpxImagePlugin.py
  src/PIL/GdImageFile.py
  src/PIL/GifImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/ImtImagePlugin.py
  src/PIL/IptcImagePlugin.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/McIdasImagePlugin.py
  src/PIL/MicImagePlugin.py
  src/PIL/MpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/MspImagePlugin.py
  src/PIL/PalmImagePlugin.py
  src/PIL/PcdImagePlugin.py
  src/PIL/PcxImagePlugin.py
  src/PIL/PdfImagePlugin.py
  src/PIL/PixarImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/PpmImagePlugin.py
  src/PIL/PsdImagePlugin.py
  src/PIL/SgiImagePlugin.py
  src/PIL/SunImagePlugin.py
  src/PIL/TgaImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WmfImagePlugin.py
  src/PIL/XVThumbImagePlugin.py
  src/PIL/XbmImagePlugin.py
  src/PIL/XpmImagePlugin.py
Labels: Removal

#4220 Test Python 3.8 and PyPy3.6 on Windows with GitHub Actions
  .github/workflows/test-windows.yml
  winbuild/config.py
Labels: Testing, Windows

#4174 Fix mismatched function name, add explanation
  src/PIL/JpegPresets.py
Labels: Documentation

#4181 Better error messaging in PIL.Image.fromarray
  Tests/test_image_array.py
  src/PIL/Image.py
Labels: Enhancement
