Repository python-pillow/Pillow, pull requests merged in 2019-10, with the labels that each got.

#4009 Corrected tag types
  src/PIL/TiffTags.py
Labels: TIFF

#4107 Remove deprecated PILLOW_VERSION
  docs/deprecations.rst
  src/PIL/Image.py
  src/PIL/__init__.py
Labels: Removal

#4114 Removed deprecated setting of TIFF image sizes
  Tests/test_file_tiff.py
  docs/deprecations.rst
  src/PIL/TiffImagePlugin.py
Labels: Removal

#4117 Clarified image format documentation
  docs/handbook/image-file-formats.rst
Labels: Documentation

#4118 Use double backticks
  docs/releasenotes/6.2.0.rst
Labels: Documentation

#4108 Drop support for EOL PyQt4 and PySide
  .travis.yml
  .travis/install.sh
  Tests/test_imageqt.py
  Tests/test_qt_image_toqimage.py
  docs/deprecations.rst
  docs/reference/ImageQt.rst
  src/PIL/ImageQt.py
Labels: Removal

#4121 Use bytes literals instead of bytes(str)
  Tests/check_icns_dos.py
  Tests/check_j2k_dos.py
Labels: Testing

#4120 Test Qt5
  .travis.yml
  .travis/install.sh
Labels: Testing

#4125 Updated ImageOps documentation
  docs/reference/ImageOps.rst
Labels: Documentation

#4066 Test Docker with GitHub Actions
  .github/workflows/test-docker.yml
Labels: Build, Testing

#4126 Added Python 3.8 rc1 to AppVeyor
  .appveyor.yml
  winbuild/config.py
Labels: Testing

#4132 Added orientation note
  docs/handbook/concepts.rst
Labels: Documentation

#4084 Test Windows with GitHub Actions
  .github/workflows/test-windows.yml
  Tests/check_imaging_leaks.py
  Tests/check_j2k_leaks.py
  Tests/check_jpeg_leaks.py
  Tests/helper.py
  Tests/test_core_resources.py
  Tests/test_file_jpeg.py
  Tests/test_file_png.py
  Tests/test_file_tiff.py
  Tests/test_font_leaks.py
  Tests/test_image.py
  Tests/test_image_access.py
  Tests/test_imagefont.py
  Tests/test_imageshow.py
  Tests/test_imagewin.py
  Tests/test_imagewin_pointers.py
  Tests/test_main.py
  Tests/test_map.py
  Tests/test_shell_injection.py
  winbuild/build.py
  winbuild/build_dep.py
  winbuild/config.py
  winbuild/fribidi.cmake
  winbuild/raqm.cmake
  winbuild/tiff.opt
Labels: Build, Infrastructure, Testing, Windows

#4133 CI: Stop testing Python 2.7
  .appveyor.yml
  .travis.yml
Labels: Build, Removal, Testing

#4081 Test Linux and macOS with GitHub Actions
  .codecov.yml
  .github/workflows/lint.yml
  .github/workflows/macos-install.sh
  .github/workflows/test.yml
  .travis.yml
  .travis/build.sh
  .travis/test.sh
Labels: Build, Infrastructure, Linux, Testing, macOS

#4137 Add PyPy3 to the tox test matrix
  tox.ini
Labels: Testing

#4140 Test pypy3.6-v7.2.0 on Windows
  .github/workflows/test-windows.yml
  winbuild/appveyor_install_pypy3.cmd
Labels: Build, Testing, Windows

#4141 Add support for Python 3.8
  .appveyor.yml
  .travis.yml
  docs/installation.rst
  setup.py
  tox.ini
Labels: Build

#4150 Updated CI target Python versions for macOS
  docs/installation.rst
Labels: Documentation

#4151 6.2.x: Add support for Python 3.8
  .appveyor.yml
  .travis.yml
  docs/installation.rst
  setup.py
  tox.ini
  winbuild/config.py
Labels: Build

#4153 Add release notes for Pillow 6.2.1
  docs/releasenotes/6.2.1.rst
  docs/releasenotes/index.rst
Labels: Documentation

#4154 Pillow 6.2.1 is the last to support Python 2.7
  CHANGES.rst
  docs/releasenotes/6.2.0.rst
  docs/releasenotes/6.2.1.rst
Labels: Documentation

#4157 Add a check for point releases
  RELEASING.md
Labels: Documentation

#4168 GHA Windows: Explicitly use cmd shell, as GH changed the default to powershell
  .github/workflows/test-windows.yml
Labels: Bug, Build, Windows

#4169 Replaced macOS Command Line Tools install with miniconda path
  .github/workflows/macos-install.sh
  .travis/build.sh
Labels: Build, macOS

#4170 Added OpenJPEG, libimagequant and freetype to GHA macOS
  .github/workflows/macos-install.sh
Labels: Build, macOS

#4165 Remove soon-EOL Fedora 29
  .github/workflows/test-docker.yml
  .travis.yml
  azure-pipelines.yml
  docs/installation.rst
Labels: Build, Testing

#4178 Added GHA to About page
  docs/about.rst
Labels: Documentation

#4175 Simplified install extra test images script
  depends/install_extra_test_images.sh
Labels: Testing
