Repository python-pillow/Pillow, pull requests merged in 2019-09, with the labels that each got.

#3969 Documented more encoding values
  src/PIL/ImageFont.py
Labels: Documentation

#4033 Corrected tag counts
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffTags.py
Labels: TIFF

#4014 Fixed arc drawing bug for a non-whole number of degrees
  Tests/images/imagedraw_arc_width_non_whole_angle.png
  Tests/test_imagedraw.py
  src/libImaging/Draw.c
Labels: Bug

#4017 Do not allow floodfill to extend into negative coordinates
  Tests/images/imagedraw_floodfill_not_negative.png
  Tests/test_imagedraw.py
  src/PIL/ImageDraw.py
Labels: Bug

#4047 Documented more limited support modes
  docs/handbook/concepts.rst
  src/libImaging/Storage.c
Labels: Documentation

#4029 No more deprecated bdist_wininst .exe installers
  winbuild/build.py
  winbuild/build.rst
Labels: Build, Installation, Windows

#3978 Added text stroking
  Tests/images/imagedraw_stroke_different.png
  Tests/images/imagedraw_stroke_multiline.png
  Tests/images/imagedraw_stroke_same.png
  Tests/images/test_direction_ttb_stroke.png
  Tests/test_imagedraw.py
  Tests/test_imagefont.py
  Tests/test_imagefontctl.py
  docs/reference/ImageDraw.rst
  src/PIL/ImageDraw.py
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: Enhancement, Font Rendering

#4004 Improved HSV conversion
  Tests/test_image_convert.py
  src/libImaging/Convert.c
Labels: Conversion

#4031 Lazily use ImageFileDirectory_v1 values from Exif
  Tests/test_imagefile.py
  src/PIL/Image.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
Labels: Exif, Performance

#4050 Use double backticks in RST
  CHANGES.rst
  docs/handbook/image-file-formats.rst
  docs/handbook/tutorial.rst
  docs/reference/Image.rst
  docs/reference/ImageCms.rst
  docs/reference/ImagePath.rst
  docs/releasenotes/2.7.0.rst
  docs/releasenotes/2.8.0.rst
  docs/releasenotes/3.0.0.rst
  docs/releasenotes/3.1.0.rst
  winbuild/build.rst
Labels: Documentation

#4061 GitHub Actions: include `pull_request` so PRs from forks run
  .github/workflows/lint.yml
Labels: Build

#4065 Added release notes
  docs/releasenotes/6.2.0.rst
  docs/releasenotes/index.rst
Labels: Documentation

#4063 Use TIFF orientation
  Tests/images/g4_orientation_1.tif
  Tests/images/g4_orientation_2.tif
  Tests/images/g4_orientation_3.tif
  Tests/images/g4_orientation_4.tif
  Tests/images/g4_orientation_5.tif
  Tests/images/g4_orientation_6.tif
  Tests/images/g4_orientation_7.tif
  Tests/images/g4_orientation_8.tif
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#4074 Test ImageShow.show on CIs
  Tests/helper.py
  Tests/test_imageshow.py
Labels: Testing

#4080 Changed WindowsViewer format to PNG
  src/PIL/Image.py
  src/PIL/ImageShow.py
Labels: Windows

#4077 AppVeyor build improvements
  winbuild/build.py
  winbuild/build_dep.py
Labels: Build, Testing, Windows

#4082 PyPy3 on AppVeyor
  .appveyor.yml
  winbuild/appveyor_install_pypy2.cmd
  winbuild/appveyor_install_pypy3.cmd
  winbuild/config.py
Labels: Build, Testing, Windows

#4083 Cleanup by resetting locale
  Tests/test_locale.py
Labels: Testing

#4089 Release notes for #4086
  docs/releasenotes/6.2.0.rst
Labels: Documentation

#3950 Add option to capture all monitors on Windows
  Tests/test_imagegrab.py
  docs/reference/ImageGrab.rst
  src/PIL/ImageGrab.py
  src/display.c
Labels: Screen grab, Windows

#4096 Documented #3950 in the release notes
  docs/releasenotes/6.2.0.rst
Labels: Documentation, Release

#4088 Do not calculate the crop width in Image.fit if it is already known
  Tests/test_imageops.py
  src/PIL/ImageOps.py
Labels: Bug

#4100 Moved libtiff test into libtiff test file
  Tests/test_file_libtiff.py
  Tests/test_file_tiff.py
Labels: Cleanup, Testing

#4000 Fix Screengrab DPI scaling on Windows 10 version 1607+
  src/display.c
Labels: Screen grab, Windows

#4103 Raise error if TIFF dimension is a string
  Tests/images/string_dimension.tiff
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#4034 Initialize rows_per_strip when RowsPerStrip tag is missing
  Tests/images/no_rows_per_strip.tif
  Tests/test_file_libtiff.py
  src/libImaging/TiffDecode.c
Labels: Bug, TIFF
