Repository python-pillow/Pillow, pull requests merged in 2020-09, with the labels that each got.

#4894 Without the Bitbucket repo, there is no place for PIL issues
  docs/about.rst
Labels: Documentation

#4862 Added writing of subIFDs
  Tests/images/empty_gps_ifd.jpg
  Tests/test_file_jpeg.py
  src/PIL/TiffImagePlugin.py
Labels: Exif

#4803 Fail tests if bytes/bytearray are interpolated into str
  .ci/test.sh
  src/PIL/TiffImagePlugin.py
Labels: Testing

#4890 MSYS2 fixes
  .github/workflows/test-windows.yml
  docs/installation.rst
  setup.py
  src/libImaging/TiffDecode.c
Labels: Windows

#4846 Compute polygon coordinates
  Tests/images/imagedraw_regular_octagon.png
  Tests/images/imagedraw_square.png
  Tests/images/imagedraw_square_rotate_45.png
  Tests/test_imagedraw.py
  docs/reference/ImageDraw.rst
  src/PIL/ImageDraw.py
Labels: Enhancement

#4898 Add comma and minor style changes
  docs/installation.rst
Labels: Documentation

#4837 Add formats parameter to open
  Tests/test_image.py
  docs/releasenotes/8.0.0.rst
  src/PIL/Image.py
Labels: Enhancement

#4902 Add `ImageDraw.regular_polygon` to release notes
  docs/releasenotes/8.0.0.rst
Labels: Documentation

#4905 Docs: Give supported Python versions its own header
  docs/installation.rst
Labels: Documentation

#4908 Fixed effect_spread bug for zero distance
  Tests/test_image.py
  src/libImaging/Effects.c
Labels: Bug

#4840 Image.thumbnail docstring: added missing filters
  src/PIL/Image.py
Labels: Documentation

#4914 Fixed loading profile with non-ASCII path on Windows
  Tests/test_imagecms.py
  Tests/test_imagefont.py
  src/PIL/ImageCms.py
Labels: Windows

#4919 Updated libjpeg-turbo to 2.0.5
  winbuild/build_prepare.py
Labels: Windows

#4921 Updated Ghostscript to 9.53.1
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Windows

#4924 chown pip wheels cache in Travis
  .ci/install.sh
Labels: Build

#4915 Winbuild: Enable FT_CONFIG_OPTION_USE_HARFBUZZ
  winbuild/build_prepare.py
Labels: Fonts, Windows

#4934 Added overview to README and ReadTheDocs index
  README.md
  docs/index.rst
Labels: Documentation

#4931 Add Mergify config
  .github/mergify.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Infrastructure

#4932 Updated PIL repository link
  CHANGES.rst
Labels: Documentation
