Repository python-pillow/Pillow, pull requests merged in 2020-07, with the labels that each got.

#4751 Update Docker Images repository as part of releases
  RELEASING.md
Labels: Documentation

#4755 Moved tests
  Tests/test_image.py
  Tests/test_imagefile.py
Labels: Testing

#4759 Docs: Use 'plugin', fix formatting and typos
  docs/handbook/writing-your-own-file-decoder.rst
  src/PIL/JpegImagePlugin.py
Labels: Documentation

#4749 Allow ImageOps.autocontrast to specify low and high cutoffs separately
  Tests/test_imageops.py
  src/PIL/ImageOps.py
Labels: Enhancement

#4763 Remove unused externs from Imaging.h
  src/libImaging/Imaging.h
Labels: Cleanup

#4767 Use sphinx_removed_in and re-document deprecated versions of removals
  .github/workflows/test.yml
  docs/conf.py
  docs/deprecations.rst
  requirements.txt
Labels: Documentation

#4778 Fix PostScript typos
  CHANGES.rst
  docs/handbook/tutorial.rst
  docs/reference/PSDraw.rst
  src/PIL/EpsImagePlugin.py
  src/PIL/PSDraw.py
Labels: Documentation

#4774 Fix documentation references: standard library
  docs/conf.py
  docs/handbook/image-file-formats.rst
  docs/handbook/writing-your-own-file-decoder.rst
  docs/reference/Image.rst
  docs/reference/ImageDraw.rst
  docs/reference/ImageGrab.rst
  docs/releasenotes/5.3.0.rst
  docs/releasenotes/7.0.0.rst
  docs/releasenotes/7.1.0.rst
  src/PIL/PSDraw.py
Labels: Documentation

#4777 Travis CI: Allow 3.9-dev to fail
  .travis.yml
Labels: Build, Testing

#4773 Fix documentation references: PngImagePlugin
  docs/PIL.rst
  docs/handbook/image-file-formats.rst
  docs/reference/plugins.rst
  src/PIL/PngImagePlugin.py
Labels: Documentation

#4771 Fix some documentation references
  docs/handbook/image-file-formats.rst
  docs/handbook/tutorial.rst
  docs/handbook/writing-your-own-file-decoder.rst
  docs/porting.rst
  docs/reference/Image.rst
  docs/reference/ImageFilter.rst
  docs/reference/ImageFont.rst
  docs/reference/ImageQt.rst
  docs/reference/TiffTags.rst
  docs/reference/internal_modules.rst
  docs/releasenotes/4.1.0.rst
  docs/releasenotes/4.2.0.rst
  docs/releasenotes/4.3.0.rst
  src/PIL/Image.py
  src/PIL/ImageChops.py
Labels: Documentation

#4739 Document is_animated and n_frames
  docs/reference/Image.rst
  src/PIL/Image.py
Labels: Documentation

#4776 Docs: Enable nitpicky warnings
  docs/conf.py
  docs/releasenotes/4.2.0.rst
Labels: Documentation

#4768 Remove ImageCms.CmsProfile attributes deprecated since 3.2.0
  Tests/test_imagecms.py
  docs/deprecations.rst
  docs/reference/ImageCms.rst
  src/_imagingcms.c
Labels: Removal

#4746 Drop support for EOL Python 3.5
  .appveyor.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  .travis.yml
  docs/installation.rst
  requirements.txt
  setup.py
  src/PIL/_tkinter_finder.py
  tox.ini
  winbuild/README.md
  winbuild/build.rst
  winbuild/build_prepare.py
Labels: Compatibility, Removal

#4785 Updated references
  docs/conf.py
  docs/handbook/image-file-formats.rst
  docs/handbook/writing-your-own-file-decoder.rst
  docs/reference/ImageMath.rst
  src/PIL/ImageWin.py
Labels: Documentation

#4772 Use f-strings in winbuild
  winbuild/build_prepare.py
Labels: Windows

#4781 Added description of release cycle
  docs/releasenotes/index.rst
Labels: Documentation

#4748 Simplify GHA config
  .github/workflows/lint.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Cleanup, Testing

#4791 Fix expected failures on big endian systems without CI
  Tests/test_file_jpeg2k.py
  Tests/test_file_png.py
  Tests/test_file_webp_animated.py
Labels: Big-endian

#4793 Removed Docker images running Python 3.5
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#4795 GitHub Actions Ubuntu is 18.04
  docs/installation.rst
Labels: Documentation

#4800 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#4801 Tested 7.2.0 with 3.5-3.8 on macOS Mojave
  docs/installation.rst
Labels: Documentation, macOS

#4797 Replace distutils.version with packaging.version.parse
  Tests/test_imagefont.py
Labels: Cleanup

#4802 Documented MAX_IMAGE_PIXELS
  docs/conf.py
  docs/reference/Image.rst
  src/PIL/Image.py
Labels: Documentation

#4811 Document missing attributes
  docs/conf.py
  docs/handbook/image-file-formats.rst
  src/PIL/ImageFile.py
  src/PIL/TiffImagePlugin.py
Labels: Documentation

#4798 Remove long-deprecated Image.py functions
  Tests/test_image.py
  Tests/test_image_frombytes.py
  docs/deprecations.rst
  docs/reference/Image.rst
  src/PIL/Image.py
Labels: Removal

#4809 setup.py: Get prefix directly from sys instead of distutils
  setup.py
Labels: Build, Cleanup

#4817 Removed distutils from MinGW detection
  setup.py
Labels: Windows

#4814 Replaced distutils in test_image_access.py
  Tests/test_image_access.py
Labels: Windows
