Repository python-pillow/Pillow, pull requests merged in 2020-08, with the labels that each got.

#4824 Remove outdated make upload-test and upload commands
  Makefile
Labels: Cleanup

#4829 Replaced distutils build_ext with setuptools
  setup.py
Labels: Cleanup

#4740 Add gitignore to winbuild build directory
  winbuild/build_prepare.py
Labels: Windows

#4847 Improved example plugin documentation
  docs/handbook/writing-your-own-file-decoder.rst
Labels: Documentation

#4832 Removed 32-bit MinGW job
  .github/workflows/test-windows.yml
Labels: Windows

#4828 Read EXIF data tEXt chunk into info as bytes instead of string
  Tests/images/exif_text.png
  Tests/test_file_png.py
  src/PIL/PngImagePlugin.py
Labels: Exif

#4784 3.9-dev: Upgrade setuptools
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Build, Dependency

#4850 Docs: Use code formatting instead of emphasis where applicable
  docs/handbook/image-file-formats.rst
  docs/handbook/writing-your-own-file-decoder.rst
  docs/reference/ImageChops.rst
  docs/reference/ImageFile.rst
  docs/reference/ImageFont.rst
  docs/reference/ImagePath.rst
  src/PIL/Image.py
  src/PIL/ImageChops.py
  src/PIL/ImageCms.py
  src/PIL/ImageFile.py
  src/PIL/ImageFilter.py
  src/PIL/ImageFont.py
  src/PIL/ImageOps.py
  src/PIL/ImageTk.py
  src/PIL/ImageWin.py
  src/PIL/JpegPresets.py
  src/PIL/PSDraw.py
  src/PIL/TiffImagePlugin.py
Labels: Documentation

#4858 Fix LCMS2 patch
  winbuild/build_prepare.py
Labels: Build, Windows

#4701 Cache Windows builds
  .github/workflows/test-windows.yml
  winbuild/build_prepare.py
Labels: Windows

#4867 Pillow Wheels has changed to use GitHub releases
  RELEASING.md
Labels: Documentation

#4836 Add develop instructions for winbuild
  winbuild/build.rst
Labels: Documentation, Windows

#4868 Removed duplicate package
  .github/workflows/test-windows.yml
Labels: Cleanup, Windows

#4872 Add Pillow logo to README and PyPI
  README.md
  README.rst
  setup.py
Labels: Documentation

#4889 Updated harfbuzz to 2.7.2
  winbuild/build_prepare.py
Labels: Dependency

#4891 Revert #4832: Removed 32-bit MinGW job
  .github/workflows/test-windows.yml
  docs/installation.rst
Labels: Windows

#4892 Update pre-commit
  .pre-commit-config.yaml
  Tests/check_jpeg_leaks.py
  Tests/check_libtiff_segfault.py
  Tests/test_bmp_reference.py
  Tests/test_file_apng.py
  Tests/test_file_jpeg.py
  Tests/test_file_libtiff.py
  Tests/test_file_libtiff_small.py
  Tests/test_file_tiff.py
  Tests/test_file_tiff_metadata.py
  Tests/test_format_hsv.py
  Tests/test_image.py
  Tests/test_image_access.py
  Tests/test_image_point.py
  Tests/test_imagecms.py
  Tests/test_imagedraw.py
  Tests/test_imagefont_bitmap.py
  Tests/test_imageshow.py
  src/PIL/Image.py
  src/PIL/ImageCms.py
  src/PIL/ImageMorph.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: Testing

#4812 Fix build on macOS and clang when zip.h is present on system
  src/decode.c
  src/encode.c
  src/libImaging/ZipCodecs.h
  src/libImaging/ZipDecode.c
  src/libImaging/ZipEncode.c
Labels: macOS

#4893 Remove W503 from flake8 ignore list (ignored by default)
  setup.cfg
Labels: Testing
