Repository python-pillow/Pillow, pull requests merged in 2020-10, with the labels that each got.

#4944 Skip test_photoimage on MinGW due to segmentation fault
  Tests/test_imagetk.py
Labels: Windows

#4936 Updated Ghostscript to 9.53.3
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: automerge

#4946 Fix crash in ImageTk.PhotoImage on mingw64
  Tests/test_imagetk.py
  src/Tk/tkImaging.c
Labels: Windows

#4942 Fixed bug in Exif __delitem__
  Tests/test_image.py
  src/PIL/Image.py
Labels: Bug, Exif

#4292 Added reading and writing of private PNG chunks
  Tests/test_file_png.py
  docs/handbook/image-file-formats.rst
  src/PIL/PngImagePlugin.py
Labels: Enhancement

#4950 Replace deprecated add-path and set-env
  .github/workflows/test-windows.yml
Labels: Build, Windows

#4951 3.9: Test GitHub Actions
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Build

#4961 Updated CI targets
  docs/installation.rst
Labels: Documentation

#4963 CI: Fail compilation on implicit function declaration warnings
  Makefile
  Tests/test_imagecms.py
  src/PIL/features.py
  src/_imagingcms.c
Labels: Build

#4959 Add getlength and getbbox functions for TrueType fonts
  Tests/fonts/LICENSE.txt
  Tests/fonts/OpenSansCondensed-LightItalic.ttf
  Tests/images/test_combine_multiline_lm_center.png
  Tests/images/test_combine_multiline_lm_left.png
  Tests/images/test_combine_multiline_lm_right.png
  Tests/images/test_combine_multiline_mm_center.png
  Tests/images/test_combine_multiline_mm_left.png
  Tests/images/test_combine_multiline_mm_right.png
  Tests/images/test_combine_multiline_rm_center.png
  Tests/images/test_combine_multiline_rm_left.png
  Tests/images/test_combine_multiline_rm_right.png
  Tests/test_imagefont.py
  Tests/test_imagefontctl.py
  docs/reference/ImageDraw.rst
  src/PIL/ImageDraw.py
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: Fonts, Needs Release Notes

#4971 Updated freetype to 2.10.3
  Tests/test_imagefontctl.py
  winbuild/build_prepare.py
Labels: automerge

#4972 Added release notes for #4862
  docs/releasenotes/8.0.0.rst
Labels: Documentation

#4969 Release notes for TrueType functions and PyPy support
  docs/releasenotes/8.0.0.rst
Labels: Documentation, automerge

#4976 Add #4523 ellipse-drawing algorithm changes to release notes
  docs/releasenotes/8.0.0.rst
Labels: Documentation

#4978 chown pip wheels cache on ppc64le
  .ci/install.sh
Labels: automerge

#4923 Imaging.h: confusion with system
  setup.py
  src/Tk/tkImaging.c
  src/_imaging.c
  src/_imagingcms.c
  src/_imagingft.c
  src/_imagingmath.c
  src/_imagingmorph.c
  src/_imagingtk.c
  src/_webp.c
  src/decode.c
  src/display.c
  src/encode.c
  src/map.c
  src/outline.c
  src/path.c
Labels: Build, Linux

#4974 Added macOS SDK install path to library and include directories
  setup.py
Labels: macOS

#4968 Docs: Add dark mode
  docs/conf.py
  docs/resources/css/dark.css
Labels: Documentation

#4806 Initialize offset memory for PyImagingPhotoPut
  src/Tk/tkImaging.c
Labels: Memory

#4979 Added reading of IFD tag type
  Tests/images/ifd_tag_type.tiff
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
  src/PIL/TiffTags.py
Labels: TIFF

#4918 Add support for 16-bit precision JPEG quantization values
  Tests/images/hopper_16bit_qtables.jpg
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
  src/libImaging/JpegEncode.c
Labels: JPEG

#4984 GHA: Remove obsolete code for old PyPy
  .github/workflows/test-windows.yml
Labels: automerge

#4985 Remove soon-EOL Fedora 31
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#4988 Fix internal Sphinx link to installation doc
  docs/handbook/image-file-formats.rst
  docs/releasenotes/4.2.0.rst
Labels: Documentation

#4994 Updated libimagequant to 2.13.0
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#5000 Add release notes for 8.0.1
  CHANGES.rst
  docs/releasenotes/8.0.1.rst
  docs/releasenotes/index.rst
Labels: Documentation, Release

#5001 CI: Replace test images from pillow-depends
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Testing, Windows

#5004 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: macOS

#5006 Releasing: Add a 'git push' to point release, adjust MD formatting
  RELEASING.md
Labels: Documentation, Release

#5007 Clarified that "text" must be a string
  docs/reference/ImageDraw.rst
Labels: Documentation

#5010 Travis CI: Test on Python 3.9 final
  .travis.yml
Labels: Testing

#5013 Updated CI targets
  docs/installation.rst
Labels: Documentation

#5016 Describe effect of WebP save_all
  docs/handbook/image-file-formats.rst
Labels: Documentation

#5014 AppVeyor: Test on Python 3.9 final
  .appveyor.yml
Labels: Testing, Windows

#5018 Updated CI targets
  docs/installation.rst
Labels: Documentation

#5021 Add Fedora 33
  .github/workflows/test-docker.yml
Labels: Testing

#5022 Update Travis CI links for .com
  .github/CONTRIBUTING.md
  .github/mergify.yml
  README.md
  RELEASING.md
  docs/about.rst
  docs/index.rst
Labels: Documentation

#5024 Added Fedora 33 to CI targets
  docs/installation.rst
Labels: Documentation
