Repository python-pillow/Pillow, pull requests merged in 2020-04, with the labels that each got.

#4502 Add release notes for #3907 PcfFontFile charset encodings
  docs/releasenotes/7.1.0.rst
Labels: Documentation

#4512 Fix PNG seek
  Tests/test_file_png.py
  src/PIL/PngImagePlugin.py
Labels: Bug

#4515 Release notes for 7.1.1
  CHANGES.rst
  docs/releasenotes/7.1.1.rst
Labels: Documentation

#4533 Updated deprecated method
  docs/conf.py
Labels: Documentation

#4522 Update release process
  Makefile
  RELEASING.md
Labels: Documentation

#4538 Update 7.1.0 release notes with CVEs
  docs/releasenotes/7.1.0.rst
Labels: Documentation

#4524 GHA: Check docs
  .github/workflows/test.yml
Labels: Documentation, Testing

#4546 Document getexif
  docs/reference/Image.rst
Labels: Documentation

#4548 Added multiline text example
  docs/reference/ImageDraw.rst
Labels: Documentation

#4562 GitHub Actions now sets CI=true
  MANIFEST.in
  Tests/helper.py
Labels: Testing

#4561 Fix pickling WebP
  Tests/test_pickle.py
  src/PIL/WebPImagePlugin.py
Labels: Bug, WebP

#4564 Removed default arguments from pickle test helper functions
  Tests/test_pickle.py
Labels: Testing

#4565 Fixed bug when unpickling TIFF images
  Tests/test_pickle.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#4552 Simplified animation code
  src/PIL/DcxImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/MicImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PsdImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WebPImagePlugin.py
Labels: Cleanup

#4567 Don't show own deprecation warning in test logs
  Tests/test_imagefile.py
Labels: Testing

#4576 Link to Filters concept from methods' parameters
  src/PIL/Image.py
Labels: Documentation

#4577 Updated example code to new-style class
  src/PIL/Image.py
Labels: Documentation

#4582 Added Ubuntu 20.04 to Docker jobs
  .github/workflows/test-docker.yml
Labels: Testing

#4584 Remove soon-EOL Fedora 30
  .github/workflows/test-docker.yml
Labels: Testing

#4587 Updated CI targets
  docs/installation.rst
Labels: Documentation, Testing

#4590 Added Python 3.9
  .travis.yml
Labels: Testing

#4593 CI: Add Fedora 32
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Build, Testing
