Repository python-pillow/Pillow, pull requests merged in 2020-06, with the labels that each got.

#4560 Parse orientation from XMP tags
  Tests/images/xmp_tags_orientation.png
  Tests/test_file_png.py
  src/PIL/Image.py
  src/PIL/PngImagePlugin.py
Labels: Exif

#4608 Added support for 1-D NumPy arrays
  Tests/test_numpy.py
  src/PIL/Image.py
Labels: NumPy

#4580 Fixed drawing a jointed line with a sequence of numeric values
  Tests/test_imagedraw.py
  src/PIL/ImageDraw.py
Labels: Bug

#4660 Update ImageDraw docs formatting and links
  docs/reference/ImageDraw.rst
Labels: Documentation

#4677 Corrected reading EXIF metadata without prefix
  Tests/test_file_webp_metadata.py
  src/PIL/Image.py
Labels: Exif

#4679 Fixed formatting
  docs/reference/ImageDraw.rst
Labels: Documentation

#4637 Use ImageFileDirectory_v2 in Image.Exif
  Tests/test_file_jpeg.py
  src/PIL/Image.py
Labels: Exif

#4682 Improved formatting
  docs/reference/ImageGrab.rst
  src/PIL/Image.py
  src/PIL/ImageCms.py
  src/PIL/ImageWin.py
Labels: Documentation

#4692 Added release notes for 7.2.0
  docs/releasenotes/7.2.0.rst
  docs/releasenotes/index.rst
Labels: Documentation

#4696 Updated harfbuzz to 2.6.7
  Tests/images/variation_adobe.png
  Tests/images/variation_adobe_axes.png
  Tests/images/variation_adobe_name.png
  Tests/images/variation_adobe_older_harfbuzz.png
  Tests/images/variation_adobe_older_harfbuzz_axes.png
  Tests/images/variation_adobe_older_harfbuzz_name.png
  Tests/test_imagefont.py
  winbuild/build_prepare.py
Labels: Font Rendering

#4688 Add docs for features module
  docs/reference/ImageGrab.rst
  docs/reference/features.rst
  docs/reference/index.rst
  src/PIL/Image.py
  src/PIL/ImageFont.py
  src/PIL/features.py
Labels: Documentation

#4708 Updated libjpeg-turbo to 2.0.4
  winbuild/build_prepare.py
Labels: JPEG

#4702 Fix TCL in Windows PyPy tests
  .github/workflows/test-windows.yml
Labels: Testing, Windows

#4547 Added method argument to single frame WebP saving
  Tests/test_file_webp.py
  src/PIL/WebPImagePlugin.py
  src/_webp.c
Labels: WebP

#4605 Writing TIFF tags: improved BYTE, added UNDEFINED
  Tests/test_file_libtiff.py
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffImagePlugin.py
  src/encode.c
Labels: TIFF

#4627 Replaced tiff_jpeg with jpeg compression when saving TIFF images
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#4639 Write JFIF header when saving JPEG
  Tests/test_file_jpeg.py
  src/libImaging/JpegEncode.c
Labels: JPEG

#4626 Change STRIPBYTECOUNTS to LONG if necessary when saving
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#4711 Install NumPy with OpenBLAS
  .github/workflows/macos-install.sh
Labels: NumPy, macOS

#4709 Updated release notes
  docs/deprecations.rst
  docs/releasenotes/7.2.0.rst
Labels: Documentation

#4615 Improve ImageGrab.grabclipboard() on Windows
  Tests/test_imagegrab.py
  src/PIL/ImageGrab.py
  src/display.c
Labels: Windows

#4707 Replaced primitive "magic number" inside of JpegImagePlugin._accept() function by more correct version
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG

#4720 Call _accept instead of duplicating code
  src/PIL/BmpImagePlugin.py
  src/PIL/DcxImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MspImagePlugin.py
  src/PIL/PixarImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/PsdImagePlugin.py
  src/PIL/SgiImagePlugin.py
  src/PIL/SunImagePlugin.py
Labels: Cleanup

#4646 Deprecate Image.show(command="...")
  Tests/test_image.py
  docs/deprecations.rst
  src/PIL/Image.py
Labels: Deprecation

#4647 Allow libtiff to write COLORMAP tag
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
  src/PIL/TiffTags.py
  src/encode.c
Labels: TIFF

#4697 Improve autodocs
  docs/PIL.rst
  docs/conf.py
  docs/reference/ExifTags.rst
  docs/reference/ImageDraw.rst
  docs/reference/ImageEnhance.rst
  docs/reference/ImageShow.rst
  docs/reference/ImageStat.rst
  docs/reference/JpegPresets.rst
  docs/reference/TiffTags.rst
  docs/reference/index.rst
  docs/reference/internal_design.rst
  docs/reference/internal_modules.rst
  requirements.txt
  src/PIL/BdfFontFile.py
  src/PIL/ContainerIO.py
  src/PIL/ExifTags.py
  src/PIL/FontFile.py
  src/PIL/GdImageFile.py
  src/PIL/GimpGradientFile.py
  src/PIL/GimpPaletteFile.py
  src/PIL/ImageDraw2.py
  src/PIL/ImageShow.py
  src/PIL/JpegPresets.py
  src/PIL/PaletteFile.py
  src/PIL/PcfFontFile.py
  src/PIL/TarIO.py
  src/PIL/WalImageFile.py
  src/PIL/__init__.py
  src/PIL/_binary.py
Labels: Documentation

#4716 CI: Show diff when pre-commit fails
  .github/workflows/lint.yml
  setup.cfg
  tox.ini
Labels: Testing

#4736 Fix documentation references: Image constants
  docs/handbook/concepts.rst
  docs/reference/Image.rst
  docs/releasenotes/2.7.0.rst
  docs/releasenotes/4.2.0.rst
  src/PIL/Image.py
Labels: Documentation

#4733 Fix documentation references: modules
  docs/PIL.rst
  docs/porting.rst
  docs/reference/ExifTags.rst
  docs/reference/Image.rst
  docs/reference/ImageChops.rst
  docs/reference/ImageCms.rst
  docs/reference/ImageColor.rst
  docs/reference/ImageDraw.rst
  docs/reference/ImageEnhance.rst
  docs/reference/ImageFile.rst
  docs/reference/ImageFilter.rst
  docs/reference/ImageFont.rst
  docs/reference/ImageGrab.rst
  docs/reference/ImageMath.rst
  docs/reference/ImageMorph.rst
  docs/reference/ImageOps.rst
  docs/reference/ImagePalette.rst
  docs/reference/ImagePath.rst
  docs/reference/ImageQt.rst
  docs/reference/ImageSequence.rst
  docs/reference/ImageShow.rst
  docs/reference/ImageStat.rst
  docs/reference/ImageTk.rst
  docs/reference/ImageWin.rst
  docs/reference/JpegPresets.rst
  docs/reference/PSDraw.rst
  docs/reference/PyAccess.rst
  docs/reference/TiffTags.rst
  docs/reference/features.rst
  docs/reference/internal_modules.rst
  docs/reference/plugins.rst
Labels: Documentation

#4726 APNG: Fix setting disposal
  Tests/test_file_apng.py
  src/PIL/PngImagePlugin.py
Labels: Bug, Cleanup

#4742 Fixed loading non-RGBA mode APNGs with dispose background
  Tests/images/apng/dispose_op_background_p_mode.png
  Tests/test_file_apng.py
  src/PIL/PngImagePlugin.py
Labels: Bug

#4741 Fixed ICNS file pointer saving
  Tests/test_file_icns.py
  src/PIL/IcnsImagePlugin.py
Labels: Bug

#4744 Do not convert I;16 image when showing PNG
  src/PIL/ImageShow.py
Labels: Bug

#4747 Use correct function type for raqm_version_string
  src/_imagingft.c
Labels: Bug
