Repository python-pillow/Pillow, pull requests merged in 2020-05, with the labels that each got.

#4594 Fixes default offset for Exif
  Tests/test_imagefile.py
  src/PIL/Image.py
Labels: Exif

#4601 Replace spaces with tabs and add to pre-commit linting
  .pre-commit-config.yaml
  CHANGES.rst
  depends/install_extra_test_images.sh
  docs/handbook/writing-your-own-file-decoder.rst
  docs/reference/Image.rst
  docs/reference/ImageCms.rst
Labels: Testing

#4613 JPEG: Truncate icclist instead of setting to None
  Tests/images/icc-after-SOF.jpg
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG

#4596 Mention Ubuntu versions younger than 16.04
  docs/installation.rst
Labels: Documentation, Linux

#4599 Fix ImageChops documentation
  src/PIL/ImageChops.py
Labels: Documentation

#4622 Fix broken string in test error message
  Tests/test_image_reduce.py
Labels: Bug, Testing

#4620 Fix repeatedly loading .gbr
  Tests/test_file_gbr.py
  src/PIL/GbrImagePlugin.py
Labels: Bug

#4630 Use _accept function in example plugin
  docs/handbook/writing-your-own-file-decoder.rst
Labels: Documentation

#4631 Add testpaths to tell pytest where to search for tests
  setup.cfg
Labels: Testing

#4633 Fix ImportError on Python 3.9.0b1 for Windows
  setup.py
Labels: Windows

#4636 Link pilfont to its new home in pillow-scripts
  docs/reference/ImageFont.rst
Labels: Documentation

#4638 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation

#4495 Winbuild rewrite
  .appveyor.yml
  .github/workflows/lint.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-windows.yml
  Tests/test_imageshow.py
  docs/installation.rst
  winbuild/README.md
  winbuild/appveyor_install_pypy3.cmd
  winbuild/build.py
  winbuild/build.rst
  winbuild/build_dep.py
  winbuild/build_prepare.py
  winbuild/config.py
  winbuild/fetch.py
  winbuild/fribidi.cmake
  winbuild/get_pythons.py
  winbuild/lcms2_patch.ps1
  winbuild/raqm.cmake
  winbuild/test.py
  winbuild/untar.py
  winbuild/unzip.py
Labels: Build, Windows

#4550 Replaced TiffImagePlugin DEBUG with logging
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#4617 Removed duplicate return statements
  src/libImaging/Except.c
Labels: Cleanup

#4625 Fixed ZeroDivisionError in Image.thumbnail
  Tests/test_image_thumbnail.py
  src/PIL/Image.py
Labels: Bug

#4652 Do not render glyphs during text layout
  src/_imagingft.c
Labels: Fonts

#4619 Removed unused argument from CHOP
  src/libImaging/Chops.c
Labels: Cleanup

#4604 Updated ImageGrab documentation now that Linux is supported
  docs/reference/ImageGrab.rst
  src/PIL/ImageGrab.py
Labels: Documentation, Linux
