Repository python-pillow/Pillow, pull requests merged in 2020-11, with the labels that each got.

#5002 Document FreeMono license
  Tests/fonts/LICENSE.txt
Labels: Documentation

#4980 GHA: Add 3.10-dev
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  src/display.c
Labels: Testing

#5030 Link directly to pilfont script
  docs/reference/ImageFont.rst
Labels: Documentation

#5031 PNG supports append_images
  docs/handbook/image-file-formats.rst
Labels: Documentation

#5040 Fixed link formatting
  src/PIL/ImageFont.py
Labels: Documentation

#5029 Remove excess Travis CI jobs
  .ci/install.sh
  .github/workflows/test.yml
  .travis.yml
  Tests/test_image_quantize.py
Labels: Infrastructure

#5044 Updated libjpeg-turbo to 2.0.6
  winbuild/build_prepare.py
Labels: Dependency

#5026 Removed unused C methods
  src/display.c
Labels: Cleanup

#5052 Add line breaks in test-windows
  .github/workflows/test-windows.yml
Labels: Build, Windows

#4965 Moved warning to end of execution
  setup.py
Labels: Build, Installation, Windows

#5055 Docs: add logo with text to menu
  docs/conf.py
  docs/resources/pillow-logo.png
Labels: Documentation

#5057 GHA: Make windows cache depend on VS version
  .github/workflows/test-windows.yml
Labels: Build, Windows

#5063 Updated libraqm to 0.7.1
  winbuild/build_prepare.py
Labels: Dependency, automerge

#5061 GHA: Install Raqm on macOS
  .github/workflows/macos-install.sh
Labels: Build, macOS

#5064 Update FriBiDi to 1.0.10
  winbuild/build_prepare.py
  winbuild/fribidi.cmake
  winbuild/raqm.cmake
Labels: Dependency, Windows

#5058 Add Release Drafter to draft releases
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: Release

#5066 Updated instructions now that draft releases may exist
  RELEASING.md
Labels: Documentation

#5065 Updated libimagequant to 2.13.1
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#5067 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5068 Corrected documentation syntax
  docs/handbook/writing-your-own-file-decoder.rst
Labels: Documentation

#5070 Updated libraqm to 0.7.1
  depends/install_raqm.sh
Labels: Dependency

#5060 CI: Remove soon-EOL Amazon Linux 1 and CentOS 6
  .github/workflows/test-docker.yml
  Tests/test_imagefont.py
  docs/installation.rst
Labels: Testing
