Repository python-pillow/Pillow, pull requests merged in 2020-12, with the labels that each got.

#5078 Update CHANGES.rst
  CHANGES.rst
Labels: Documentation

#5081 Add categories to Release Drafter
  .github/release-drafter.yml
Labels: Documentation, Release

#5085 Document when deprecations will be removed
  docs/deprecations.rst
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/__init__.py
Labels: Deprecation, Documentation

#5074 Docs: Add 'Release notes' and 'Changelog' links to PyPI
  README.md
  setup.py
Labels: Documentation

#5087 Disable Travis CI from automerge requirements
  .github/mergify.yml
Labels: Testing

#5091 Mark new test failures on non-x86 as xfail
  Tests/helper.py
  Tests/test_file_libtiff.py
  Tests/test_image_quantize.py
Labels: Testing

#5099 GHA: Add PyPy3.7
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Build, Testing

#5050 Remove unused Travis CI config
  .ci/after_success.sh
  .ci/install.sh
  .ci/test.sh
  .github/CONTRIBUTING.md
  .github/mergify.yml
  README.md
  RELEASING.md
  Tests/bench_cffi_access.py
  Tests/helper.py
  depends/README.rst
  depends/diffcover-install.sh
  depends/diffcover-run.sh
  docs/about.rst
  docs/index.rst
  requirements.txt
Labels: Cleanup, Testing

#5106 Added packaging
  requirements.txt
Labels: Testing

#5107 Remove unused Travis CI config
  .ci/after_success.sh
  .ci/install.sh
  .ci/test.sh
  .github/CONTRIBUTING.md
  .github/mergify.yml
  README.md
  RELEASING.md
  Tests/bench_cffi_access.py
  Tests/helper.py
  depends/README.rst
  depends/diffcover-install.sh
  depends/diffcover-run.sh
  docs/about.rst
  docs/index.rst
  requirements.txt
Labels: Cleanup, Testing

#5102 Add tests for ImagePath.Path
  Tests/test_imagepath.py
Labels: Testing

#5109 Remove duplicate code
  src/_imagingcms.c
Labels: Cleanup

#5112 Update some doc code blocks to the 'pycon' lexer
  docs/releasenotes/7.1.1.rst
  docs/releasenotes/7.1.2.rst
Labels: Documentation

#5098 Deprecate FreeType 2.7
  .github/workflows/test.yml
  Makefile
  Tests/test_imagefont.py
  docs/Makefile
  docs/conf.py
  docs/deprecations.rst
  docs/releasenotes/3.1.1.rst
  docs/releasenotes/3.1.2.rst
  docs/releasenotes/6.2.0.rst
  docs/releasenotes/6.2.2.rst
  docs/releasenotes/7.1.0.rst
  docs/releasenotes/8.0.1.rst
  docs/releasenotes/8.1.0.rst
  docs/releasenotes/index.rst
  requirements.txt
  src/PIL/ImageFont.py
Labels: Deprecation

#5115 Fix use of a versus an in ImageCms.rst
  docs/reference/ImageCms.rst
Labels: Documentation

#5056 Don't add light mode bg to 3rd and 4th level menu items
  docs/conf.py
  docs/resources/css/dark.css
  docs/resources/css/light.css
  docs/resources/js/script.js
Labels: Documentation

#4983 Releasing: Replace viewdoc with markdown2 and twine check
  Makefile
  RELEASING.md
  requirements.txt
Labels: Release, Testing

#5117 Added versioning documentation
  RELEASING.md
  docs/releasenotes/index.rst
  docs/releasenotes/versioning.rst
Labels: Documentation

#5120 Block TIFFTAG_SUBIFD
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5122 Fixed comparison warnings
  src/_imaging.c
  src/libImaging/Draw.c
  src/libImaging/Jpeg2KDecode.c
  src/libImaging/RankFilter.c
  src/libImaging/Resample.c
Labels: Build

#5128 Updated harfbuzz to 2.7.3
  winbuild/build_prepare.py
Labels: Dependency

#5131 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation

#5129 Added release notes for #4568
  docs/releasenotes/8.1.0.rst
Labels: Documentation

#5127 Fixed warnings assigning to "unsigned char *" from "char *"
  src/_imagingft.c
  src/libImaging/GetBBox.c
Labels: Cleanup

#5138 Updated harfbuzz to 2.7.4
  winbuild/build_prepare.py
Labels: Dependency

#5140 Removed unused variable
  src/_imagingft.c
Labels: Cleanup

#5151 Updated openjpeg to 2.4.0
  depends/install_openjpeg.sh
  docs/installation.rst
  winbuild/build_prepare.py
Labels: Dependency

#5152 OpenJPEG has been updated in pillow-wheels
  docs/releasenotes/8.1.0.rst
Labels: Documentation, automerge

#5125 Use previous disposal method in GIF load_end
  Tests/images/dispose_none_load_end.gif
  Tests/images/dispose_none_load_end_second.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#5137 Document limited number of characters in FontFile
  docs/reference/ImageFont.rst
Labels: Documentation

#5154 Added #5148 to the release notes
  docs/releasenotes/8.1.0.rst
Labels: Documentation

#5153 Updated libtiff to 4.2.0
  src/libImaging/TiffDecode.c
  winbuild/build_prepare.py
  winbuild/tiff.opt
Labels: TIFF

#5162 Corrected argument
  Tests/test_decompression_bomb.py
Labels: Testing

#5166 Updated copyright year
  LICENSE
  docs/COPYING
  docs/conf.py
Labels: Documentation
