Repository python-pillow/Pillow, pull requests merged in 2021-03, with the labels that each got.

#5198 Add CIFuzz Github Action
  .github/workflows/cifuzz.yml
Labels: Testing

#5301 Update release notes: formatting, links, spelling
  docs/conf.py
  docs/releasenotes/7.1.0.rst
  docs/releasenotes/8.1.0.rst
  docs/releasenotes/8.1.1.rst
Labels: Documentation

#5303 Corrected list of relevant dependencies
  docs/releasenotes/8.1.1.rst
Labels: Documentation

#5306 Added more CVE numbers to 8.1.1 release notes
  docs/releasenotes/8.1.1.rst
Labels: Documentation

#5215 Document license for several fonts
  Tests/fonts/DejaVuSans/DejaVuSans-24-1-stripped.ttf
  Tests/fonts/DejaVuSans/DejaVuSans-24-2-stripped.ttf
  Tests/fonts/DejaVuSans/DejaVuSans-24-4-stripped.ttf
  Tests/fonts/DejaVuSans/DejaVuSans-24-8-stripped.ttf
  Tests/fonts/DejaVuSans/DejaVuSans.ttf
  Tests/fonts/DejaVuSans/LICENSE.txt
  Tests/fonts/LICENSE.txt
  Tests/test_imagefont.py
  Tests/test_imagefontctl.py
Labels: Documentation, Fonts

#5224 Do not use "use built-in mapper WIN32 only"
  Tests/test_map.py
  src/PIL/ImageFile.py
  src/_imaging.c
  src/map.c
Labels: Windows

#5155 Document and add tests for SBIX color font support
  .github/workflows/test-windows.yml
  Tests/fonts/LICENSE.txt
  Tests/fonts/chromacheck-sbix.woff
  Tests/images/chromacheck-sbix.png
  Tests/images/chromacheck-sbix_mask.png
  Tests/test_imagefont.py
  docs/reference/ImageDraw.rst
  docs/releasenotes/8.0.0.rst
Labels: Font Rendering, Testing, automerge

#5208 Added ImageDraw rounded_rectangle method
  Tests/images/imagedraw_rounded_rectangle.png
  Tests/images/imagedraw_rounded_rectangle_both.png
  Tests/images/imagedraw_rounded_rectangle_x.png
  Tests/images/imagedraw_rounded_rectangle_y.png
  Tests/test_imagedraw.py
  docs/reference/ImageDraw.rst
  docs/releasenotes/8.2.0.rst
  src/PIL/ImageDraw.py
Labels: Enhancement

#5219 Replaced mkdir command with Python
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#5260 Ensure file is closed if it is opened by ImageQt.ImageQt
  Tests/test_imageqt.py
  src/PIL/ImageQt.py
Labels: Qt

#5313 Allow alpha_composite destination to be negative
  Tests/test_image.py
  docs/releasenotes/8.2.0.rst
  src/PIL/Image.py
Labels: automerge

#5318 Added link to class and function in release notes
  docs/releasenotes/8.2.0.rst
Labels: Documentation

#5268 Moved RGB fix inside ImageQt class
  Tests/test_qt_image_qapplication.py
  src/PIL/ImageQt.py
Labels: Qt

#5325 Fixed unclosed file warning
  Tests/test_file_icns.py
Labels: Testing

#5321 Save ICC profile from TIFF encoderinfo
  Tests/test_file_png.py
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5329 Add pytest-timeout to CI and requirements.txt
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/test-windows.yml
  requirements.txt
Labels: Testing

#5327 Document #5321
  docs/handbook/image-file-formats.rst
  docs/releasenotes/8.2.0.rst
Labels: Documentation

#5334 Updated harfbuzz to 2.8.0
  winbuild/build_prepare.py
Labels: Dependency, Testing

#5336 Updated list of TIFF compression methods
  docs/handbook/image-file-formats.rst
Labels: Documentation, TIFF

#5343 Replaced tiff_deflate with tiff_adobe_deflate compression when saving TIFF images
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#4947 Stop flattening EXIF IFD into getexif()
  Tests/test_file_jpeg.py
  Tests/test_image.py
  src/PIL/Image.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffTags.py
  src/PIL/WebPImagePlugin.py
Labels: Exif

#5344 Added release notes for #4947
  docs/releasenotes/8.2.0.rst
Labels: Documentation

#5326 Improved efficiency when creating GIF disposal images
  src/PIL/GifImagePlugin.py
Labels: GIF

#5331 Added test for saving PNG with bits keyword
  Tests/test_file_png.py
Labels: Testing

#5345 Increased use of assert_image_equal_tofile
  Tests/test_imagedraw.py
Labels: Testing

#5338 Use duration from info dictionary when saving WebP
  Tests/test_file_webp.py
  src/PIL/WebPImagePlugin.py
Labels: WebP

#5354 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5357 Contributing docs: Include release notes as needed or appropriate
  .github/CONTRIBUTING.md
Labels: Documentation

#5360 Listed Debian packages
  docs/installation.rst
Labels: Documentation, Linux

#5361 Document prerequisites and Python development libraries for Alpine
  docs/installation.rst
Labels: Documentation, Linux

#5352 Document quantize method defaults and mode support
  docs/reference/Image.rst
  src/PIL/Image.py
Labels: Documentation

#5363 Removed build_distance_tables return value
  src/libImaging/Quant.c
Labels: Cleanup

#5351 Deprecated categories
  Tests/test_image.py
  docs/deprecations.rst
  docs/reference/Image.rst
  docs/releasenotes/8.2.0.rst
  src/PIL/Image.py
  src/PIL/MicImagePlugin.py
Labels: Deprecation, Documentation

#5274 Fixed linear_gradient and radial_gradient I and F modes
  Tests/test_image.py
  src/libImaging/Fill.c
Labels: Bug

#5350 Add preserve_tone option to autocontrast
  Tests/test_imageops.py
  docs/releasenotes/8.2.0.rst
  src/PIL/ImageOps.py
Labels: Enhancement

#5365 Document Raqm/FriBiDi linking changes
  docs/installation.rst
  docs/releasenotes/8.2.0.rst
  src/thirdparty/fribidi-shim/fribidi.c
  winbuild/build.rst
Labels: Documentation

#5332 Corrected grammar
  src/libImaging/GifDecode.c
Labels: Documentation

#5368 Updated Ghostscript to 9.54.0
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Testing, automerge

#5291 Modify Gif.h and GifEncode.c to use LZW encoding
  docs/releasenotes/8.2.0.rst
  src/libImaging/Gif.h
  src/libImaging/GifEncode.c
Labels: GIF
