Repository python-pillow/Pillow, pull requests merged in 2021-06, with the labels that each got.

#5521 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5473 Do not allow TIFF to seek to a past frame
  Tests/images/multipage_multiple_frame_loop.tiff
  Tests/images/multipage_out_of_order.tiff
  Tests/images/multipage_single_frame_loop.tiff
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5522 Fix lcms2_static target for msbuild
  winbuild/build_prepare.py
Labels: Testing, Windows

#5513 Added ICO saving in BMP format
  Tests/test_file_ico.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/8.3.0.rst
  src/PIL/IcoImagePlugin.py
Labels: Enhancement

#5515 Fix differing background colors in right sidebar in dark mode docs
  docs/resources/css/dark.css
Labels: Documentation

#5532 Copies of an image do not retain the format
  docs/handbook/image-file-formats.rst
Labels: Documentation

#5533 Fixed errors when running tests in random order
  Tests/oss-fuzz/fuzz_font.py
  Tests/oss-fuzz/fuzz_pillow.py
  Tests/oss-fuzz/fuzzers.py
  Tests/oss-fuzz/test_fuzzers.py
  Tests/test_decompression_bomb.py
Labels: Testing

#5542 Reverse test order for two CI jobs
  .ci/test.sh
  .github/workflows/test.yml
Labels: Testing

#5540 Fixed default numresolution for small JPEG2000 images
  Tests/test_file_jpeg2k.py
  Tests/test_imagefile.py
  src/libImaging/Jpeg2KEncode.c
Labels: JPEG

#5547 Do not modify EXIF of original image instance in exif_transpose()
  Tests/test_imageops.py
  src/PIL/ImageOps.py
Labels: Exif

#5367 Avoid unstable nature of qsort in Quant.c
  Tests/images/hopper_resized.gif
  Tests/test_image_resize.py
  src/libImaging/Quant.c
Labels: Platform

#5556 Fixed undefined variable in logging
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffImagePlugin.py
Labels: Bug

#5557 Use transparency behind first GIF frame and when disposing to background
  Tests/images/first_frame_transparency.gif
  Tests/images/transparent_dispose.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#5560 Corrected comments
  Tests/test_file_gif.py
Labels: Testing, automerge

#5405 Read FITS image mode and size
  Tests/images/hopper_naxis_zero.fits
  Tests/test_file_fitsstub.py
  src/PIL/FitsStubImagePlugin.py
Labels: Enhancement

#5416 Allow getexif() to access TIFF tag_v2 data
  Tests/test_file_tiff.py
  Tests/test_image.py
  src/PIL/Image.py
Labels: Enhancement, TIFF

#5412 Convert to float for comparison with float in IFDRational __eq__
  Tests/test_file_tiff.py
  Tests/test_tiff_ifdrational.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5455 Improved getxmp()
  Tests/test_file_jpeg.py
  Tests/test_file_png.py
  Tests/test_file_tiff.py
  src/PIL/Image.py
  src/PIL/JpegImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: JPEG

#5402 Add DDS saving
  Tests/test_file_dds.py
  docs/handbook/image-file-formats.rst
  src/PIL/DdsImagePlugin.py
Labels: Enhancement

#5552 Improved ImagePalette
  Tests/test_file_apng.py
  Tests/test_file_gif.py
  Tests/test_image.py
  Tests/test_image_convert.py
  Tests/test_imageops.py
  Tests/test_imagepalette.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageOps.py
  src/PIL/ImagePalette.py
  src/PIL/PyAccess.py
  src/PIL/WebPImagePlugin.py
Labels: Palette Issue

#5539 Modified docstring for GaussianBlur
  src/PIL/ImageFilter.py
Labels: Documentation

#5561 Moved CVE image to pillow-depends
  Tests/images/crash-81154a65438ba5aaeca73fd502fa4850fbde60f8.tif
Labels: automerge

#5562 Corrected border position for P mode in ImageOps.expand()
  Tests/test_imageops.py
  src/PIL/ImageOps.py
Labels: automerge

#5563 Add Twitter to PyPI project URLs
  setup.py
Labels: Documentation

#5566 Added release notes
  docs/releasenotes/8.3.0.rst
Labels: Documentation

#5315 Simplified code
  src/PIL/Image.py
Labels: Cleanup

#5564 Do not use background or transparency index for new color
  Tests/test_imagepalette.py
  src/PIL/ImagePalette.py
Labels: Palette Issue, automerge

#4989 De-zigzag JPEG's DQT when loading; deprecate convert_dict_qtables
  Tests/test_file_jpeg.py
  docs/deprecations.rst
  docs/releasenotes/8.3.0.rst
  src/PIL/JpegImagePlugin.py
  src/PIL/JpegPresets.py
Labels: JPEG, automerge

#5514 Limit TIFF strip size when saving with libtiff
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF
