Repository python-pillow/Pillow, pull requests merged in 2021-02, with the labels that each got.

#5232 Moved test that requires libtiff
  Tests/test_file_libtiff.py
  Tests/test_file_tiff.py
Labels: TIFF, Testing

#5216 Deprecate Tk/Tcl 8.4, to be removed in Pillow 10 (2023-01-02)
  docs/deprecations.rst
  docs/releasenotes/8.2.0.rst
  docs/releasenotes/index.rst
  src/PIL/_tkinter_finder.py
Labels: Deprecation

#5244 Fixed unclosed file warning
  Tests/test_file_png.py
Labels: Testing

#5252 Updated lcms2 to 2.12
  docs/installation.rst
  winbuild/build_prepare.py
Labels: Dependency

#5253 Removed outdated limits documentation
  docs/reference/limits.rst
Labels: Documentation

#5255 Updated ImageColor.getrgb docstring
  src/PIL/ImageColor.py
Labels: Documentation

#5258 Added PyQt6 support
  Tests/test_imageqt.py
  Tests/test_qt_image_qapplication.py
  docs/releasenotes/8.2.0.rst
  src/PIL/ImageQt.py
Labels: Enhancement, Qt

#5181 Docs: add alpha channel to supported hex color specifiers
  docs/reference/ImageColor.rst
Labels: Documentation

#5261 Added context managers
  Tests/check_icns_dos.py
  Tests/check_j2k_dos.py
  Tests/test_decompression_bomb.py
  Tests/test_file_dds.py
  Tests/test_file_fpx.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_png.py
  Tests/test_file_ppm.py
  Tests/test_file_psd.py
  Tests/test_file_spider.py
  Tests/test_file_tiff.py
  Tests/test_file_webp.py
  Tests/test_image.py
  Tests/test_imagewin_pointers.py
Labels: Testing

#5269 Improved ImageQt documentation
  docs/reference/ImageQt.rst
  src/PIL/ImageQt.py
Labels: Documentation, Qt

#5259 Fixed asserting that no warnings were raised
  Tests/test_bmp_reference.py
  Tests/test_file_dcx.py
  Tests/test_file_fli.py
  Tests/test_file_gif.py
  Tests/test_file_icns.py
  Tests/test_file_im.py
  Tests/test_file_jpeg.py
  Tests/test_file_mpo.py
  Tests/test_file_png.py
  Tests/test_file_psd.py
  Tests/test_file_spider.py
  Tests/test_file_tar.py
  Tests/test_file_tiff.py
  Tests/test_file_webp.py
  Tests/test_image.py
  Tests/test_numpy.py
Labels: Testing

#5275 Increased use of _tofile helper functions
  Tests/test_file_blp.py
  Tests/test_file_bmp.py
  Tests/test_file_dds.py
  Tests/test_file_eps.py
  Tests/test_file_fli.py
  Tests/test_file_ftex.py
  Tests/test_file_gbr.py
  Tests/test_file_gif.py
  Tests/test_file_icns.py
  Tests/test_file_ico.py
  Tests/test_file_im.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_libtiff.py
  Tests/test_file_mcidas.py
  Tests/test_file_msp.py
  Tests/test_file_ppm.py
  Tests/test_file_sgi.py
  Tests/test_file_spider.py
  Tests/test_file_sun.py
  Tests/test_file_tiff.py
  Tests/test_file_webp_alpha.py
  Tests/test_file_wmf.py
  Tests/test_font_pcf.py
  Tests/test_font_pcf_charsets.py
  Tests/test_image.py
  Tests/test_image_rotate.py
  Tests/test_imagecms.py
  Tests/test_imagedraw.py
  Tests/test_imagedraw2.py
  Tests/test_imagefont.py
  Tests/test_imagefontctl.py
  Tests/test_imagemorph.py
  Tests/test_imageops.py
  Tests/test_imagepalette.py
  Tests/test_qt_image_toqimage.py
Labels: Testing

#5279 Corrected documentation syntax
  docs/handbook/writing-your-own-file-decoder.rst
Labels: Documentation

#5277 Example from filter should be next to filter method docs, not in 'frombytes'
  docs/reference/Image.rst
Labels: Documentation

#5290 Removed comment
  src/PIL/ImageShow.py
Labels: Documentation

#5288 Migrated from deprecated numpy bool and float
  Tests/test_numpy.py
Labels: NumPy

#5283 Added context managers to documentation
  docs/reference/Image.rst
  docs/reference/ImageDraw.rst
  docs/reference/ImageMath.rst
  docs/reference/c_extension_debugging.rst
Labels: Documentation

#5293 Add Valgrind GHA
  .github/workflows/test-valgrind.yml
Labels: Testing
