Repository python-pillow/Pillow, pull requests merged in 2021-05, with the labels that each got.

#5417 Added ImageOps contain()
  Tests/test_imageops.py
  docs/reference/ImageOps.rst
  docs/releasenotes/8.3.0.rst
  docs/releasenotes/index.rst
  src/PIL/ImageOps.py
Labels: Enhancement

#5445 Fixed bug when checking FreeType2 version if it is not installed
  src/PIL/ImageFont.py
Labels: Bug

#5426 Fixed UNDEFINED TIFF tag of length 0 being changed in roundtrip
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5437 Replace sys.stdout with sys.stdout.buffer when saving
  Tests/test_file_png.py
  Tests/test_psdraw.py
  docs/handbook/tutorial.rst
  docs/reference/ImageDraw.rst
  src/PIL/EpsImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/PSDraw.py
Labels: Bug

#5464 Updated harfbuzz to 2.8.1
  winbuild/build_prepare.py
Labels: Dependency

#5466 Updated tested libtiff versions
  docs/installation.rst
Labels: Documentation, TIFF

#5468 Corrected code references in docstring
  src/PIL/TiffImagePlugin.py
Labels: Documentation, TIFF

#5477 Use python3
  docs/releasenotes/8.0.0.rst
  src/PIL/IcnsImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageShow.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/features.py
Labels: Documentation

#5479 Updated libimagequant to 2.15.0
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#5443 Reset handle when seeking backwards in TIFF
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5458 Replaced uint16 and uint32 with uint16_t and uint32_t to resolve TIFF deprecations
  src/decode.c
  src/libImaging/TiffDecode.c
  src/libImaging/TiffDecode.h
Labels: TIFF

#5474 Corrected errors in restoring sys.stdout in tests
  Tests/test_file_png.py
  Tests/test_psdraw.py
Labels: Testing

#5471 Include code in WebP error
  Tests/test_file_webp.py
  src/_webp.c
Labels: WebP

#5446 Removed TIFF DPI rounding
  Tests/images/hopper_float_dpi_2.tif
  Tests/images/hopper_float_dpi_3.tif
  Tests/images/hopper_float_dpi_None.tif
  Tests/images/hopper_roundDown_2.tif
  Tests/images/hopper_roundDown_3.tif
  Tests/images/hopper_roundDown_None.tif
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5482 Removed GitHub Actions Ubuntu setuptools version requirement
  .ci/install.sh
Labels: Testing

#5483 Updated badges for wheels
  README.md
  docs/index.rst
Labels: Documentation

#5492 Updated libimagequant to 2.15.1
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency, automerge

#5496 Removed setuptools version requirement on GHA macOS and Windows
  .github/workflows/macos-install.sh
  .github/workflows/test-windows.yml
Labels: Testing

#5452 Updated default value for SAMPLESPERPIXEL TIFF tag
  Tests/images/old-style-jpeg-compression-no-samplesperpixel.tif
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5498 Build docs with sphinx_copybutton and sphinxext.opengraph
  .github/workflows/test.yml
  docs/conf.py
  docs/installation.rst
  requirements.txt
Labels: Cool, Documentation

#5505 Fixed typo
  src/libImaging/TiffDecode.c
Labels: automerge

#5379 Allow converting an image to a numpy array to raise errors
  Tests/test_image_array.py
  src/PIL/Image.py
Labels: NumPy

#5507 Avoid race condition when displaying images with eog
  src/PIL/ImageShow.py
Labels: Linux
