Repository python-pillow/Pillow, pull requests merged in 2021-01, with the labels that each got.

#5167 Moved QApplication into one test
  Tests/test_imageqt.py
  Tests/test_qt_image_fromqpixmap.py
  Tests/test_qt_image_qapplication.py
  Tests/test_qt_image_toqimage.py
  Tests/test_qt_image_toqpixmap.py
Labels: Qt

#5161 Add support for PySide6
  Tests/test_imageqt.py
  Tests/test_qt_image_qapplication.py
  src/PIL/ImageQt.py
Labels: Enhancement, Qt

#5170 Document #5161 in release notes
  docs/releasenotes/8.1.0.rst
Labels: Documentation

#5172 Added release notes for #5149
  docs/releasenotes/8.1.0.rst
Labels: Documentation, automerge

#5171 Add #5159 to the release notes
  Makefile
  docs/releasenotes/8.1.0.rst
Labels: Documentation

#5175 Fix TIFF OOB Write error
  Tests/images/crash-2020-10-test.tif
  Tests/test_tiff_crashes.py
  src/libImaging/TiffDecode.c
Labels: TIFF

#5176 Document CVE fixes
  CHANGES.rst
  docs/releasenotes/8.1.0.rst
Labels: Documentation

#5179 Release notes for LibTIFF update in pillow-wheels
  docs/releasenotes/8.1.0.rst
Labels: Documentation

#5186 CI: Use python3 in .ci/test.sh
  .ci/test.sh
Labels: automerge

#5189 Oss fuzz support
  Tests/oss-fuzz/fuzz_pillow.py
  setup.py
Labels: Testing

#5187 Use python3
  .github/workflows/lint.yml
  .github/workflows/test-docker.yml
  .github/workflows/test.yml
Labels: Testing

#5177 Added docs for C-Extension debugging with valgrind
  docs/reference/c_extension_debugging.rst
  docs/reference/internal_design.rst
Labels: Documentation

#5195 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5196 Changed example image file name
  docs/reference/Image.rst
Labels: Documentation

#5197 getcolors() returns colors in the image mode
  src/PIL/Image.py
Labels: Documentation

#5200 Removed broken link
  selftest.py
Labels: Documentation

#5213 Corrected CVE number
  src/PIL/PcxImagePlugin.py
Labels: Documentation

#5223 Documentation error: Wrong threshold in conversion from L to 1
  src/PIL/Image.py
Labels: Documentation

#5231 Install pytest and pytest-cov using pip rather than pacman
  .github/workflows/test-windows.yml
Labels: Testing, Windows

#5230 Updated libimagequant to 2.14.0
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#5233 Corrected documentation syntax
  docs/releasenotes/versioning.rst
Labels: Documentation

#5234 Removed specific setuptools version from AppVeyor
  .appveyor.yml
Labels: Testing, Windows

#5238 Updated libwebp to 1.2.0
  depends/install_webp.sh
  winbuild/build_prepare.py
Labels: Dependency

#5239 Improved close() docstring
  src/PIL/Image.py
Labels: Documentation
