Repository python-pillow/Pillow, pull requests merged in 2021-11, with the labels that each got.

#5805 Test Python 3.10.0 final on AppVeyor
  .appveyor.yml
Labels: Windows, Testing

#5806 Added Fedora 35
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Linux, Testing

#5808 Updated harfbuzz to 3.1.0
  winbuild/build_prepare.py
Labels: Windows, Dependency

#5768 Drop support for soon-EOL Python 3.6
  .appveyor.yml
  .pre-commit-config.yaml
  Makefile
  Tests/test_file_gif.py
  Tests/test_file_jpeg.py
  Tests/test_file_webp.py
  Tests/test_image.py
  Tests/test_imagefont.py
  Tests/test_imagemath.py
  docs/installation.rst
  docs/releasenotes/9.0.0.rst
  setup.cfg
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/PdfParser.py
  src/PIL/TiffImagePlugin.py
  src/libImaging/ImPlatform.h
  tox.ini
  winbuild/build_prepare.py
Labels: Removal

#5820 Updated harfbuzz to 3.1.1
  winbuild/build_prepare.py
Labels: Windows, Dependency

#5821 Docs: Remove docutils pin
  requirements.txt
Labels: Documentation

#5822 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5823 Removed setuptools install from AppVeyor
  .appveyor.yml
Labels: Windows, Testing, automerge

#5828 Only prefer command line tools SDK on macOS over the default
  setup.py
Labels: Build, macOS

#5826 Add support for pickling TrueType fonts
  Tests/test_pickle.py
  docs/releasenotes/9.0.0.rst
  src/PIL/ImageFont.py
Labels: Fonts

#5840 GHA: Use actions/setup-python's pip cache
  .github/workflows/lint.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#5841 Updated libjpeg-turbo to 2.1.2
  winbuild/build_prepare.py
Labels: Windows, Testing, automerge

#5844 Do not redeclare class each time when converting to NumPy
  src/PIL/Image.py
Labels: NumPy, Memory

#5694 Added width argument to ImageDraw polygon
  Tests/images/imagedraw/triangle_right_width.png
  Tests/images/imagedraw/triangle_right_width_no_fill.png
  Tests/test_imagedraw.py
  src/PIL/ImageDraw.py
  src/_imaging.c
  src/libImaging/Draw.c
  src/libImaging/Imaging.h
Labels: Enhancement

#5839 Block tile TIFF tags when saving
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5847 Documentation for #5829 and #5694
  docs/reference/ImageDraw.rst
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#5849 Improved explanation of fromarray "mode" parameter
  src/PIL/Image.py
Labels: Documentation

#5851 Added context managers
  Tests/check_fli_oob.py
  Tests/check_jp2_overflow.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_png.py
  Tests/test_image_resize.py
  Tests/test_imagechops.py
  Tests/test_pickle.py
  Tests/test_sgi_crash.py
Labels: Testing

#5853 Updated harfbuzz to 3.1.2
  winbuild/build_prepare.py
Labels: Dependency
