Repository python-pillow/Pillow, pull requests merged in 2021-09, with the labels that each got.

#5698 Pillow 8.3.2 supports Python 3.10
  docs/installation.rst
Labels: Documentation

#5699 Add release notes for Pillow 8.3.2
  docs/releasenotes/8.3.2.rst
  docs/releasenotes/index.rst
Labels: Documentation

#5659 Actually check the framesize in FliDecode.c
  src/libImaging/FliDecode.c
Labels: Hasn't worked in 20 years

#5702 Install numpy on Python 3.10
  .ci/install.sh
Labels: Testing, NumPy

#5696 Copy Python palette to new image in quantize()
  Tests/test_image_quantize.py
  src/PIL/Image.py
Labels: Palette Issue

#5575 Added "exif" keyword argument to TIFF saving
  Tests/test_file_tiff.py
  docs/handbook/image-file-formats.rst
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5704 Docs: Temporarily pin docutils to fix bullets in sphinx_rtd_theme
  requirements.txt
Labels: Documentation

#5705 Updated harfbuzz to 2.9.1
  winbuild/build_prepare.py
Labels: Dependency

#5708 Updated docstring
  src/PIL/TiffImagePlugin.py
Labels: Documentation, TIFF, automerge

#5709 CI: Split MINGW to own workflow, remove redundant job
  .github/mergify.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-valgrind.yml
  .github/workflows/test-windows.yml
Labels: Windows, Testing, automerge

#5688 Improve the fuzzer wrt. the current atheris version
  Tests/oss-fuzz/fuzz_font.py
  Tests/oss-fuzz/fuzz_pillow.py
Labels: Testing

#5713 Docs: Update CI targets table
  docs/installation.rst
Labels: Documentation

#5719 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5714 Add CentOS Stream 8
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#5720 Updated harfbuzz to 3.0.0
  winbuild/build_prepare.py
Labels: Dependency

#5722 Remove raqm.cmake
  winbuild/build.rst
  winbuild/raqm.cmake
Labels: Windows

#5726 Updated libimagequant to 2.16.0
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#5727 Update winbuild libimagequant to 2.16.0
  winbuild/build_prepare.py
Labels: Windows

#5732 Updated fribidi to 1.0.11
  winbuild/build_prepare.py
Labels: Windows, Dependency

#5737 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS
