Repository python-pillow/Pillow, pull requests merged in 2021-04, with the labels that each got.

#5371 Docs: Fix link in release notes
  docs/releasenotes/8.2.0.rst
Labels: Documentation

#5349 Add ImageShow support for GraphicsMagick
  Tests/helper.py
  Tests/test_file_palm.py
  docs/reference/ImageShow.rst
  docs/releasenotes/8.2.0.rst
  src/PIL/ImageShow.py
Labels: Enhancement

#5359 Compile LibTIFF with CMake on Windows
  .github/workflows/test-windows.yml
  setup.py
  winbuild/build_prepare.py
  winbuild/tiff.opt
Labels: TIFF, Windows

#5373 Fix pytest valgrind warnings
  Tests/conftest.py
Labels: Testing

#5144 Feature: XMP tags function integrated at src/PIL/image.py
  Tests/images/xmp_test.jpg
  Tests/test_image_getxmp.py
  src/PIL/Image.py
Labels: Enhancement

#5376 Move getxmp() to JpegImageFile
  Tests/test_file_jpeg.py
  Tests/test_image_getxmp.py
  docs/releasenotes/8.2.0.rst
  src/PIL/Image.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG

#5378 Removed Fedora 32 docker job
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#5380 Changed register_open calls to be consistent
  Tests/test_file_dds.py
  src/PIL/BlpImagePlugin.py
  src/PIL/DdsImagePlugin.py
  src/PIL/FtexImagePlugin.py
  src/PIL/IcnsImagePlugin.py
Labels: Cleanup

#5382 Round down the radius in rounded_rectangle
  Tests/images/imagedraw_rounded_rectangle_non_integer_radius_given.png
  Tests/images/imagedraw_rounded_rectangle_non_integer_radius_height.png
  Tests/images/imagedraw_rounded_rectangle_non_integer_radius_width.png
  Tests/test_imagedraw.py
  src/PIL/ImageDraw.py
Labels: Bug

#5393 Add test for CVE-2021-25292 ReDoS
  Tests/test_file_pdf.py
Labels: Testing

#5399 Fix PDF file format documentation
  docs/handbook/image-file-formats.rst
Labels: Documentation

#5386 Fixed ensuring that GIF previous frame was loaded
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: Bug, GIF

#5390 Use zero if GIF background color index is missing
  Tests/images/missing_background.gif
  Tests/images/missing_background_first_frame.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#5384 Added TransferFunction and ReferenceBlackWhite to core TIFF tags
  src/PIL/TiffTags.py
  src/encode.c
Labels: TIFF

#5410 Changed wording to avoid confusion with IMAGING_TYPE_SPECIAL
  docs/handbook/concepts.rst
Labels: Documentation

#4996 JPEG2000: Support decoding subsampled RGB and YCbCr images
  Tests/test_file_jpeg2k.py
  src/libImaging/Jpeg2KDecode.c
Labels: JPEG

#5396 TGA color map entry size is only 1 byte
  Tests/images/200x32_p_bl_raw_origin.tga
  Tests/test_file_tga.py
  src/PIL/TgaImagePlugin.py
Labels: Bug

#5400 Changed mode for TGA 16-bit palette to BGR;15
  Tests/images/p_16.png
  Tests/images/p_16.tga
  Tests/test_file_tga.py
  src/PIL/TgaImagePlugin.py
Labels: Bug

#5391 Treat previous contents of first GIF frame as transparent
  Tests/images/dispose_prev_first_frame.gif
  Tests/images/dispose_prev_first_frame_seeked.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#5420 Corrected test
  Tests/test_file_ico.py
Labels: Testing

#5419 Add EXIF tags specified in EXIF 2.32
  src/PIL/ExifTags.py
Labels: Exif

#5422 Updated nasm to 2.15.05 in AppVeyor
  .appveyor.yml
Labels: Testing, Windows

#5424 Add Raspberry Pi OS to platform support
  docs/installation.rst
Labels: Documentation

#5423 Added info about mode when saving ICO for Windows
  src/PIL/IcoImagePlugin.py
Labels: Documentation, Windows

#5425 Changed TIFF tag 33723 length to 1
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffTags.py
Labels: TIFF

#5427 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5408 Corrected JPEG APP14 transform value
  Tests/images/truncated_app14.jpg
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: Bug, JPEG

#5421 Updated libtiff to 4.3.0
  winbuild/build_prepare.py
Labels: Dependency, TIFF

#5433 Updated libjpeg-turbo to 2.1.0
  winbuild/build_prepare.py
Labels: Dependency, JPEG

#5451 Added Fedora 34
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#5447 Fixed Python 3.10 at alpha.7
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/test.yml
Labels: Testing

#5450 Changed WebP default "method" value to 4
  docs/handbook/image-file-formats.rst
  src/PIL/WebPImagePlugin.py
Labels: WebP

#5453 GHA: Update test-windows for 64-bit PyPy 7.3.4 release
  .github/workflows/test-windows.yml
Labels: Testing, Windows

#5456 Revert "Fixed Python 3.10 at alpha.7": use 3.10-dev
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/test.yml
Labels: Testing

#5457 Clarified error message
  src/decode.c
Labels: automerge
