Repository python-pillow/Pillow, pull requests merged in 2021-07, with the labels that each got.

#5572 Make Image.__array__ take optional dtype argument
  Tests/test_image_array.py
  src/PIL/Image.py
Labels: NumPy

#5579 Removed variable
  src/PIL/Image.py
Labels: Cleanup

#5596 Updated harfbuzz to 2.8.2
  winbuild/build_prepare.py
Labels: Dependency

#5605 Changed URLs to HTTPS
  docs/reference/c_extension_debugging.rst
  src/PIL/GifImagePlugin.py
  src/PIL/ImageCms.py
  src/PIL/MspImagePlugin.py
  src/Tk/_tkmini.h
  src/libImaging/ImagingUtils.h
  src/thirdparty/raqm/raqm.c
Labels: automerge

#5588 Ensure TIFF RowsPerStrip is multiple of 8 for JPEG compression
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5628 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#5630 Corrected Python 3.10 support
  docs/installation.rst
Labels: Documentation

#5638 Corrected ImagePalette size parameter documentation
  src/PIL/ImagePalette.py
Labels: Documentation

#5613 PSD layer count may be negative
  Tests/images/negative_layer_count.psd
  Tests/test_file_psd.py
  src/PIL/PsdImagePlugin.py
  src/PIL/_binary.py
Labels: Bug

#5597 Added tags when saving YCbCr TIFF
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
  src/encode.c
Labels: TIFF

#5601 Allow saving WebP with icc_profile None
  Tests/test_file_webp.py
  src/PIL/WebPImagePlugin.py
Labels: WebP

#5624 Prefer command line tools SDK on macOS
  setup.py
Labels: Build, macOS

#5641 Deprecate ImagePalette size parameter
  Tests/test_imagepalette.py
  docs/deprecations.rst
  src/PIL/ImagePalette.py
Labels: Deprecation, Palette Issue, automerge

#5645 Do not close file pointer in SGI save handler
  Tests/test_file_sgi.py
  src/PIL/SgiImagePlugin.py
Labels: File Closing
