Repository python-pillow/Pillow, pull requests merged in 2021-12, with the labels that each got.

#5866 Improved example code
  docs/handbook/image-file-formats.rst
  docs/handbook/tutorial.rst
  docs/handbook/writing-your-own-file-decoder.rst
  docs/reference/ImageDraw.rst
  docs/reference/PixelAccess.rst
  docs/reference/PyAccess.rst
  docs/reference/c_extension_debugging.rst
  docs/reference/open_files.rst
Labels: Documentation

#5867 Updated freetype to 2.11.1
  winbuild/build_prepare.py
Labels: Dependency, automerge

#5798 WebP: Fix memory leak during decoding on failure
  src/_webp.c
Labels: WebP, Memory

#5861 GHA: Add workflow_dispatch to enable manually triggering builds
  .github/workflows/cifuzz.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-valgrind.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#5857 Convert subsequent GIF frames to RGB or RGBA
  Tests/images/different_transparency_merged.gif
  Tests/images/different_transparency_merged.png
  Tests/images/dispose_bgnd_rgba.gif
  Tests/images/dispose_none_load_end_second.gif
  Tests/images/dispose_none_load_end_second.png
  Tests/images/dispose_prev_first_frame_seeked.gif
  Tests/images/dispose_prev_first_frame_seeked.png
  Tests/images/missing_background_first_frame.gif
  Tests/images/missing_background_first_frame.png
  Tests/test_file_gif.py
  docs/handbook/image-file-formats.rst
  src/PIL/GifImagePlugin.py
  src/PIL/PdfImagePlugin.py
  src/decode.c
  src/libImaging/Gif.h
  src/libImaging/GifDecode.c
Labels: GIF

#5874 Added release notes for #5857
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#5876 Updated libimagequant to 2.17.0
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#5883 Updated harfbuzz to 3.2.0
  winbuild/build_prepare.py
Labels: Dependency

#5885 Dedicate the next release to Fredrik Lundh
  docs/releasenotes/9.0.0.rst
Labels: Documentation, Release

#5886 GHA: Use macos-10.15 to fix build
  .github/workflows/test.yml
Labels: Testing

#5856 Support 16-bit grayscale ImageQt conversion
  Tests/test_imageqt.py
  src/PIL/ImageQt.py
Labels: automerge, Qt

#5888 GHA: Still use macos-latest for non-PyPy builds
  .github/workflows/test.yml
Labels: Testing

#5862 Added PIL + pathlib Tutorial
  docs/handbook/tutorial.rst
Labels: Documentation, automerge

#5897 Added ImageShow support for xdg-open
  docs/reference/ImageShow.rst
  src/PIL/ImageShow.py
Labels: Enhancement

#5905 Added release notes for #5897
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#5907 Do not compare properties to themselves
  Tests/test_image_convert.py
  Tests/test_image_quantize.py
  Tests/test_imagegrab.py
Labels: Testing

#5909 Fixed freeing pointer in ImageDraw.Outline.transform
  Tests/test_imagedraw.py
  src/libImaging/Draw.c
Labels: Bug, automerge

#5908 Image.NONE is only used for resampling and dithers
  src/PIL/Image.py
Labels: Cleanup

#5912 Exclude carriage return in PDF regex to help prevent ReDoS
  Tests/test_file_pdf.py
  src/PIL/PdfParser.py
Labels: automerge

#5848 Pass SAMPLEFORMAT to libtiff
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#5859 When saving RGBA to GIF, make use of first transparent palette entry
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#5879 Limit quantized palette to number of colors
  Tests/test_image_quantize.py
  src/PIL/Image.py
Labels: Palette Issue

#5899 Ensure that BMP pixel data offset does not ignore palette
  Tests/images/pal8_offset.bmp
  Tests/test_file_bmp.py
  src/PIL/BmpImagePlugin.py
Labels: BMP

#5901 Improved I;16 operations on big endian
  Tests/test_file_jpeg2k.py
  Tests/test_file_png.py
  src/libImaging/Jpeg2KDecode.c
  src/libImaging/Jpeg2KEncode.c
  src/libImaging/Pack.c
Labels: Big-endian

#5404 Changed error type to allow for incremental WebP parsing
  Tests/test_imagefile.py
  src/_webp.c
Labels: WebP

#5807 Use the Windows method to get TCL functions on Cygwin
  Tests/test_image.py
  setup.py
  src/Tk/tkImaging.c
  src/libImaging/ImPlatform.h
Labels: Windows

#5913 Added sys import
  Tests/test_image.py
Labels: Testing, automerge

#5517 Explicitly enable strip chopping for large uncompressed TIFFs
  src/libImaging/TiffDecode.c
Labels: TIFF

#5916 Updated winbuild libimagequant to 2.17.0
  winbuild/build_prepare.py
Labels: Windows

#5917 Added release notes for pillow-wheels#237
  docs/releasenotes/9.0.0.rst
Labels: Documentation, automerge
