Repository python-pillow/Pillow, pull requests merged in 2022-03, with the labels that each got.

#6098 Updated Python for doccheck to 3.10
  .github/workflows/test.yml
Labels: Testing

#6101 Reset size when seeking away from "Large Thumbnail" MPO frame
  Tests/test_file_mpo.py
  src/PIL/MpoImagePlugin.py
Labels: Bug

#6106 Document that histogram() uses 256 bins per channel
  docs/reference/ImageStat.rst
  src/PIL/Image.py
Labels: Documentation

#6111 Updated setup-python, checkout and upload-artifact actions to v3
  .github/workflows/cifuzz.yml
  .github/workflows/lint.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-valgrind.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  .github/workflows/tidelift.yml
Labels: Testing

#6099 Document alternatives to accessing individual pixels
  docs/reference/PixelAccess.rst
  docs/reference/PyAccess.rst
Labels: Documentation

#6094 Improved codec documentation
  docs/handbook/writing-your-own-image-plugin.rst
  src/PIL/Image.py
  src/PIL/ImageFile.py
Labels: Documentation

#6086 Fixed loading L mode GIF with transparency
  Tests/images/no_palette_with_transparency.gif
  Tests/test_file_gif.py
  Tests/test_image_convert.py
  Tests/test_image_paste.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/libImaging/Convert.c
  src/libImaging/Paste.c
Labels: GIF

#6112 Clip I;16 to be unsigned, not signed
  Tests/test_image_convert.py
  src/libImaging/Convert.c
Labels: Conversion

#6116 Removed load_prepare nearly identical to ImageFile load_prepare
  src/PIL/PsdImagePlugin.py
Labels: Cleanup

#6117 decode() should return -1 when finished
  src/PIL/BlpImagePlugin.py
  src/PIL/ImageFile.py
  src/PIL/MspImagePlugin.py
Labels: Documentation

#6077 GIF seek performance improvements
  src/PIL/GifImagePlugin.py
Labels: GIF, Performance

#6097 Added BigTIFF reading
  Tests/images/hopper_bigtiff.tif
  Tests/test_file_tiff.py
  docs/releasenotes/9.1.0.rst
  src/PIL/Image.py
  src/PIL/TiffImagePlugin.py
  src/PIL/TiffTags.py
Labels: TIFF

#6125 Updated harfbuzz to 4.0.1
  winbuild/build_prepare.py
Labels: Dependency, automerge

#5984 libwebp 1.2.2 fixed endian bugs
  Tests/test_file_webp_animated.py
Labels: WebP, Big-endian

#6137 Removed unused variable
  src/libImaging/TgaRleDecode.c
Labels: Cleanup, automerge

#6129 Added merging images example
  docs/handbook/tutorial.rst
Labels: Documentation

#6143 Removed period before colon
  src/PIL/Image.py
Labels: Documentation

#6140 Added WebP default duration of zero when saving
  Tests/test_file_webp.py
  src/PIL/WebPImagePlugin.py
Labels: WebP

#6141 Do not always require ctypes in tests
  Tests/test_file_libtiff.py
  Tests/test_image_access.py
  Tests/test_imagewin_pointers.py
Labels: Testing

#6153 Updated harfbuzz to 4.1.0
  winbuild/build_prepare.py
Labels: Dependency, automerge

#6124 Handle EXIF data truncated to just the header
  Tests/test_image.py
  src/PIL/Image.py
Labels: Exif

#6128 Retain RGBA transparency when saving multiple GIF frames
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6136 Fixed calling DisplayViewer or XVViewer without a title
  src/PIL/ImageShow.py
Labels: Bug

#6155 Document support for RLE8 reading in BMP
  docs/handbook/image-file-formats.rst
Labels: Documentation

#6157 Added pytest-timeout to AppVeyor
  .appveyor.yml
Labels: Windows, Testing

#6132 Added support for reading I;16R TIFF images
  Tests/images/16bit.r.tif
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
  src/libImaging/Unpack.c
Labels: TIFF

#6147 Fixed saving L mode GIF with background as WebP
  Tests/images/no_palette_with_background.gif
  Tests/test_file_webp.py
  src/PIL/WebPImagePlugin.py
Labels: WebP

#6152 Use screencapture arguments to crop on macOS
  src/PIL/ImageGrab.py
Labels: macOS, Screen grab

#5970 Fixed comparison warnings
  src/libImaging/TiffDecode.c
Labels: TIFF

#6032 Ensure Tkinter hook is activated for getimage()
  Tests/test_imagetk.py
  src/PIL/ImageTk.py
Labels: Bug

#5958 Corrected memory allocation
  src/path.c
Labels: Memory

#5973 Always save TIFF with contiguous planar configuration
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#6159 Raise ValueError when trying to save empty JPEG
  Tests/test_file_jpeg.py
  Tests/test_image.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG

#6160 Updated zlib to 1.2.12
  winbuild/build_prepare.py
Labels: Windows, Dependency

#6034 Allow 1 mode images to be inverted
  Tests/test_imageops.py
  src/PIL/ImageOps.py
Labels: Enhancement

#6150 Added setting for converting GIF P frames to RGB
  Tests/images/no_palette.gif
  Tests/images/no_palette_with_transparency.gif
  Tests/test_file_gif.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/9.1.0.rst
  src/PIL/GifImagePlugin.py
  src/decode.c
  src/libImaging/Gif.h
  src/libImaging/GifDecode.c
Labels: GIF

#6164 Updated harfbuzz to 4.2.0
  winbuild/build_prepare.py
Labels: Dependency

#6165 Fix loading FriBiDi on Alpine
  src/thirdparty/fribidi-shim/fribidi.c
Labels: Linux
