Repository python-pillow/Pillow, pull requests merged in 2022-08, with the labels that each got.

#6466 Updated harfbuzz to 5.1.0
  winbuild/build_prepare.py
Labels: Dependency

#6473 Updated Valgrind job to Jammy
  .github/workflows/test-valgrind.yml
Labels: Testing

#6477 Increased test tolerance to allow for libtiff with libjpeg-turbo
  Tests/test_file_libtiff.py
Labels: TIFF, macOS, Testing

#6483 Updated libwebp to 1.2.4
  depends/install_webp.sh
  winbuild/build_prepare.py
Labels: WebP, Dependency, automerge

#6485 Note to Windows users that FreeType will keep the font file open
  src/PIL/ImageFont.py
Labels: Documentation, Windows, Fonts

#6476 Orientation data is removed by exif_transpose()
  src/PIL/ImageOps.py
Labels: Documentation, Exif

#6498 Updated libjpeg-turbo to 2.1.4
  winbuild/build_prepare.py
Labels: Windows, Testing

#6484 Allow default ImageDraw font to be set
  Tests/test_imagedraw.py
  docs/reference/ImageDraw.rst
  docs/releasenotes/9.3.0.rst
  src/PIL/ImageDraw.py
Labels: Fonts

#6509 Added direct conversion from PA to P
  src/libImaging/Convert.c
Labels: Conversion

#6511 Ubuntu dependencies also apply to Jammy
  docs/installation.rst
Labels: Documentation, Linux

#6501 Do not install test-image-results on GitHub Actions
  .ci/install.sh
  .github/workflows/macos-install.sh
Labels: Cleanup, Testing

#6523 Updated libimagequant to 4.0.2
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#6524 Temporarily skip valgrind failure
  Tests/test_file_pdf.py
Labels: Testing

#6519 Parametrize Tests/test_image_paste.py
  Tests/test_image_paste.py
Labels: Testing

#6529 Build lcms2 VC2022
  winbuild/build_prepare.py
Labels: Windows, automerge

#6526 Parametrized tests
  Tests/test_file_apng.py
  Tests/test_file_container.py
  Tests/test_file_im.py
  Tests/test_file_libtiff.py
  Tests/test_file_mpo.py
  Tests/test_file_tga.py
  Tests/test_file_wmf.py
  Tests/test_image.py
  Tests/test_image_access.py
  Tests/test_image_convert.py
  Tests/test_image_copy.py
  Tests/test_image_crop.py
  Tests/test_image_resample.py
  Tests/test_image_resize.py
  Tests/test_image_rotate.py
  Tests/test_image_transpose.py
  Tests/test_imagedraw.py
  Tests/test_qt_image_toqimage.py
Labels: Testing, automerge

#6535 Updated libimagequant to 4.0.4
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#6538 NumPy now supports Python 3.11
  .ci/install.sh
  .github/workflows/macos-install.sh
Labels: NumPy

#6541 Set top-level permissions for remaining GitHub Actions
  .github/workflows/cifuzz.yml
  .github/workflows/test-cygwin.yml
Labels: Testing

#6549 Removed support for Python versions before interpaddr()
  src/PIL/ImageTk.py
  src/_imagingtk.c
Labels: Cleanup

#6550 Updated tested Windows environment list
  winbuild/README.md
Labels: Documentation, Windows, Testing

#6518 Do not use CCITTFaxDecode filter if libtiff is not available
  Tests/test_file_pdf.py
  src/PIL/PdfImagePlugin.py
Labels: TIFF

#6551 Removed support for PyPy before Python 3.6
  src/PIL/ImageTk.py
Labels: Cleanup

#6504 Allow RGB and RGBA values for PA image putpixel
  Tests/test_image_access.py
  docs/reference/PixelAccess.rst
  src/PIL/Image.py
  src/PIL/PyAccess.py
Labels: Palette, automerge

#6497 Copy palette when converting from P to PA
  Tests/test_image_convert.py
  src/libImaging/Convert.c
Labels: Palette, Conversion

#6552 Use constants in TiffImagePlugin
  src/PIL/TiffImagePlugin.py
Labels: TIFF
