Repository python-pillow/Pillow, pull requests merged in 2022-05, with the labels that each got.

#6255 Updated freetype to 2.12.1
  winbuild/build_prepare.py
Labels: Dependency, automerge

#6198 Convert pre-fork CHANGES to RST
  CHANGES.rst
Labels: Documentation

#6138 Search pkgconf system libs/cflags
  setup.py
Labels: Build

#6270 Adjust BITSPERSAMPLE to match SAMPLESPERPIXEL
  Tests/images/tiff_wrong_bits_per_sample_3.tiff
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#6274 Skip test_imagetk if tk raises a RuntimeError
  Tests/test_imagetk.py
Labels: Testing

#6265 Use durations from each frame by default when saving GIFs
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6264 libjpeg-turbo may result in different pixels
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#6280 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#6283 Populate Python palette in fromarray()
  Tests/test_image_array.py
  src/PIL/Image.py
Labels: Palette Issue

#6284 Replaced test image to fix xfail
  Tests/images/decompression_bomb.ico
  Tests/test_decompression_bomb.py
Labels: Testing

#6286 Added Fedora 36
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#5878 CI: Add a Cygwin run to GitHub Actions
  .ci/after_success.sh
  .ci/build.sh
  .ci/install.sh
  .github/mergify.yml
  .github/workflows/test-cygwin.yml
  README.md
  docs/index.rst
  docs/installation.rst
Labels: Windows, Testing

#6295 Updated openjpeg to 2.5.0
  depends/install_openjpeg.sh
  docs/installation.rst
  winbuild/build_prepare.py
Labels: Dependency

#6296 Fix some typos
  docs/releasenotes/8.0.0.rst
  src/PIL/Image.py
  src/PIL/SpiderImagePlugin.py
  src/libImaging/GifDecode.c
Labels: automerge

#6306 Upgrade non-amd64 Ubuntu jobs to Jammy
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Linux, Testing

#6234 If font is file-like object, do not re-read from object to get variant
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
Labels: Fonts

#6231 Ignore compression value from BMP info dictionary when saving as TIFF
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF, BMP

#6292 Always use GIF89a for comments
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6315 Updated harfbuzz to 4.3.0
  winbuild/build_prepare.py
Labels: Dependency

#6294 Separate multiple GIF comment blocks in a frame with newlines
  Tests/images/multiple_comments.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6313 Improved image file formats documentation
  docs/handbook/image-file-formats.rst
Labels: Documentation

#6300 Only write GIF comments at the beginning of the file
  Tests/images/second_frame_comment.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6333 Link to GitHub discussions in CONTRIBUTING
  .github/CONTRIBUTING.md
Labels: Documentation

#6211 Netscape GIF extension belongs after the global color table
  Tests/images/duplicate_number_of_loops.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6325 Once a GIF comment is loaded, it is kept for subsequent frames
  docs/handbook/image-file-formats.rst
Labels: Documentation, GIF

#6219 Do not update GIF frame position until local image is found
  Tests/images/comment_after_last_frame.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6338 Added EMF and SUN to list of supported file formats
  docs/handbook/image-file-formats.rst
Labels: Documentation

#6303 Only try to connect discontiguous corners at the end of edges
  Tests/test_imagedraw.py
  src/libImaging/Draw.c
Labels: Regression, automerge

#6339 Updated libtiff to 4.4.0
  docs/installation.rst
  src/libImaging/TiffDecode.c
  winbuild/build_prepare.py
Labels: TIFF, Dependency, automerge

#6340 Add Sphinx Lint to pre-commit and fix RST bug
  .pre-commit-config.yaml
  winbuild/build.rst
Labels: Documentation, Testing
