Repository python-pillow/Pillow, pull requests merged in 2022-07, with the labels that each got.

#6408 Install furo if it is not available
  docs/Makefile
Labels: Documentation, automerge

#6381 Deprecate ImageFont.getsize and related functions
  Tests/images/rectangle_surrounding_text.png
  Tests/oss-fuzz/fuzzers.py
  Tests/test_font_pcf.py
  Tests/test_font_pcf_charsets.py
  Tests/test_imagedraw.py
  Tests/test_imagedraw2.py
  Tests/test_imagefont.py
  Tests/test_imagefontctl.py
  docs/deprecations.rst
  docs/reference/ImageDraw.rst
  docs/reference/ImageFont.rst
  docs/releasenotes/9.2.0.rst
  src/PIL/ImageDraw.py
  src/PIL/ImageDraw2.py
  src/PIL/ImageFont.py
Labels: Deprecation, automerge

#6413 Set permissions for GitHub actions
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test-cygwin.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-valgrind.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  .github/workflows/tidelift.yml
Labels: Testing

#6425 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#6427 Updated links
  docs/handbook/image-file-formats.rst
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#6429 Fixed PSDraw rectangle
  src/PIL/PSDraw.py
Labels: Bug

#6438 Install libxcb-shape0
  .ci/install.sh
Labels: Qt

#6436 Added ABGR BMP mask mode
  Tests/images/rgb32bf-abgr.bmp
  Tests/test_file_bmp.py
  src/PIL/BmpImagePlugin.py
Labels: BMP

#6440 Docs: Allow setting Python interpreter via command line
  docs/Makefile
Labels: Documentation

#6442 Updated libwebp to 1.2.3
  depends/install_webp.sh
  winbuild/build_prepare.py
Labels: WebP, Dependency, automerge

#6443 Fix simple typo
  src/PIL/Image.py
Labels: Documentation, automerge

#6450 Do not quote Pillow version for setuptools >= 60
  setup.py
Labels: Windows

#6433 Docs: Replace version tables with RST csv-table and add 3.11
  docs/installation.rst
  docs/newer-versions.csv
  docs/older-versions.csv
Labels: Documentation

#6451 Updated libimagequant to 4.0.1
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#6456 Moved tile encoding into separate function
  src/PIL/ImageFile.py
Labels: Memory

#6444 Support saving multiple MPO frames
  Tests/test_file_mpo.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/9.3.0.rst
  docs/releasenotes/index.rst
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
Labels: Enhancement

#6455 Do not clear GIF tile when checking number of frames
  Tests/images/comment_after_only_frame.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6457 Add support for ATI1/2(BC4/BC5) DDS files
  Tests/images/ati1.dds
  Tests/images/ati1.png
  Tests/images/ati2.dds
  Tests/test_file_dds.py
  src/PIL/DdsImagePlugin.py
Labels: Enhancement, automerge

#6465 Added release notes for #6457
  docs/releasenotes/9.3.0.rst
Labels: Documentation

#6458 Switch to GitHub Actions artifacts for Windows wheels
  RELEASING.md
Labels: Documentation, Windows

#6463 Parse orientation from XMP tag contents
  Tests/images/xmp_tags_orientation_exiftool.png
  Tests/test_imageops.py
  src/PIL/Image.py
  src/PIL/ImageOps.py
Labels: automerge
