Repository python-pillow/Pillow, pull requests merged in 2022-01, with the labels that each got.

#5918 Updated copyright year
  LICENSE
  docs/COPYING
  docs/conf.py
Labels: Documentation

#5921 Ensure JpegImagePlugin stops at the end of a truncated file
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG, automerge

#5922 Added release notes for #5919, #5920 and #5921
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#5923 Restrict builtins for ImageMath.eval()
  Tests/test_imagemath.py
  docs/releasenotes/9.0.0.rst
  src/PIL/ImageMath.py
Labels: automerge

#5924 CVEs TBD
  CHANGES.rst
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#5937 Removed duplicate check
  Tests/test_image_mode.py
Labels: Testing

#5940 Add CVE IDs
  CHANGES.rst
  docs/releasenotes/9.0.0.rst
Labels: Documentation

#5946 Ensure duplicated file pointer is closed
  src/PIL/TiffImagePlugin.py
Labels: TIFF, File Closing

#5955 Autolink CWE numbers with sphinx-issues
  docs/releasenotes/9.0.0.rst
  requirements.txt
Labels: Documentation, automerge

#5959 Deprecated show_file "file" argument in favour of "path"
  Tests/test_imageshow.py
  docs/deprecations.rst
  src/PIL/ImageShow.py
Labels: Deprecation

#5965 Added Debian 11 Bullseye
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#5964 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation

#5969 Updated links
  README.md
  docs/about.rst
  docs/index.rst
Labels: Documentation

#5982 Updated libwebp to 1.2.2
  depends/install_webp.sh
  winbuild/build_prepare.py
Labels: WebP, Dependency, automerge

#5985 Removed unused variables
  Tests/test_file_psd.py
  src/PIL/PsdImagePlugin.py
Labels: Cleanup

#5987 Document when file argument will be removed
  docs/deprecations.rst
  src/PIL/ImageShow.py
Labels: Documentation

#5989 Upgraded raqm to 0.8.0
  .ci/install.sh
  depends/install_raqm.sh
  docs/installation.rst
Labels: Dependency

#5994 Updated GitHub Actions badges
  README.md
  docs/index.rst
Labels: Documentation

#5995 Updated raqm to 0.8.0 on Windows
  src/thirdparty/raqm/COPYING
  src/thirdparty/raqm/NEWS
  src/thirdparty/raqm/README.md
  src/thirdparty/raqm/raqm-version.h
  src/thirdparty/raqm/raqm.c
  src/thirdparty/raqm/raqm.h
Labels: Windows, Dependency

#5996 Parametrize test
  Tests/test_numpy.py
Labels: Testing

#5998 Updated lcms2 to 2.13
  docs/installation.rst
  winbuild/build_prepare.py
Labels: Dependency

#5999 Switched from windows-2019 to windows-latest in GitHub Actions
  .github/workflows/test-mingw.yml
  .github/workflows/test-windows.yml
Labels: Windows, Testing

#6000 Updated raqm to 0.9.0
  depends/install_raqm.sh
  src/thirdparty/raqm/COPYING
  src/thirdparty/raqm/README.md
  src/thirdparty/raqm/raqm-version.h
  src/thirdparty/raqm/raqm.c
  src/thirdparty/raqm/raqm.h
Labels: Dependency, automerge

#6002 Fix lcms2 URL
  winbuild/build_prepare.py
Labels: Dependency

#6003 Update harfbuzz to 3.3.1
  winbuild/build_prepare.py
Labels: Dependency, automerge

#6004 Stop testing EOL CentOS 8
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing, automerge
