Repository python-pillow/Pillow, pull requests merged in 2022-06, with the labels that each got.

#6232 Pad COLORMAP to 768 items when saving TIFF
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF, Palette Issue

#6345 Use SourceForge auto mirror capability
  winbuild/build_prepare.py
Labels: Windows, Dependency

#6346 Include #6178 in release notes
  docs/releasenotes/9.2.0.rst
Labels: Documentation

#6347 Fix Sphinx 5 warning by setting docs language
  docs/conf.py
Labels: Documentation, automerge

#6354 Revert "Skip test_realloc_overflow unless libtiff 4.0.4 or higher"
  Tests/test_file_libtiff.py
Labels: TIFF

#6350 Allow remapping P images with RGBA palettes
  Tests/test_image.py
  src/PIL/Image.py
Labels: Palette

#6301 Added pytest-timeout to test dependencies
  Tests/README.rst
Labels: Documentation

#6222 Use python3
  .github/workflows/test-windows.yml
  winbuild/build.rst
Labels: Windows

#6197 Fixed behaviour change from endian fix
  Tests/images/issue_6194.j2k
  Tests/test_file_jpeg2k.py
  src/libImaging/Jpeg2KDecode.c
Labels: Regression

#6352 Added apply_transparency()
  Tests/test_image.py
  docs/reference/Image.rst
  docs/releasenotes/9.2.0.rst
  src/PIL/Image.py
Labels: Palette

#5242 Add support for decoding plain PPM formats
  Tests/images/hopper_16bit.pgm
  Tests/images/hopper_16bit_plain.pgm
  Tests/images/hopper_1bit.pbm
  Tests/images/hopper_1bit_plain.pbm
  Tests/images/hopper_8bit.pgm
  Tests/images/hopper_8bit.ppm
  Tests/images/hopper_8bit_plain.pgm
  Tests/images/hopper_8bit_plain.ppm
  Tests/test_file_ppm.py
  src/PIL/PpmImagePlugin.py
Labels: Enhancement

#6370 Fix wrong operator bug in PyCMSError exception message
  Tests/test_imagecms.py
  src/PIL/ImageCms.py
Labels: automerge

#6384 Fixed loading L mode BMP RLE8 images
  Tests/images/hopper_rle8_greyscale.bmp
  Tests/test_file_bmp.py
  src/PIL/BmpImagePlugin.py
Labels: BMP

#6377 Fixed bug with rounding pixels to palette
  Tests/images/palette_negative.png
  Tests/images/palette_sepia.png
  Tests/images/palette_wedge.png
  Tests/test_image_entropy.py
  Tests/test_image_getcolors.py
  Tests/test_image_histogram.py
  Tests/test_image_quantize.py
  src/libImaging/Palette.c
Labels: Palette

#6391 Pad PCX palette to 768 bytes when saving
  Tests/test_file_pcx.py
  src/PIL/PcxImagePlugin.py
Labels: Regression

#6394 Reverted to __array_interface__ with the release of NumPy 1.23
  Tests/test_image_array.py
  src/PIL/Image.py
Labels: NumPy

#6378 Improved GIF optimize condition
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: Enhancement, GIF

#6386 Handle PCF fonts files with less than 256 characters
  Tests/fonts/10x20-ISO8859-1-fewer-characters.pcf
  Tests/test_font_pcf.py
  src/PIL/PcfFontFile.py
Labels: Needs Tests, Fonts

#6397 Updated harfbuzz to 4.4.0
  winbuild/build_prepare.py
Labels: Dependency

#6399 Docs: remove redundant search page from table of contents
  docs/index.rst
Labels: Documentation

#6401 Updated harfbuzz to 4.4.1
  winbuild/build_prepare.py
Labels: Dependency, automerge

#6402 Added GIF decompression bomb check
  Tests/images/decompression_bomb_extents.gif
  Tests/test_decompression_bomb.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6403 Added release notes for #6402
  docs/releasenotes/9.2.0.rst
Labels: Documentation, automerge
