Repository python-pillow/Pillow, pull requests merged in 2022-10, with the labels that each got.

#6632 Added headings before listing options
  docs/handbook/image-file-formats.rst
Labels: Documentation

#6556 Improved documentation of ImageDraw return values
  docs/deprecations.rst
  docs/reference/ImageDraw.rst
  docs/releasenotes/9.2.0.rst
  src/PIL/ImageFont.py
Labels: Documentation

#6634 Parametrized tests
  Tests/test_features.py
  Tests/test_file_apng.py
  Tests/test_file_eps.py
  Tests/test_file_gif.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_libtiff.py
  Tests/test_file_palm.py
  Tests/test_file_pcx.py
  Tests/test_file_pdf.py
  Tests/test_file_tiff.py
  Tests/test_font_pcf_charsets.py
  Tests/test_image_reduce.py
  Tests/test_image_resample.py
  Tests/test_image_split.py
  Tests/test_imagedraw.py
  Tests/test_imagedraw2.py
  Tests/test_imageenhance.py
  Tests/test_imagefont.py
  Tests/test_imagemorph.py
  Tests/test_imageshow.py
  Tests/test_imagetk.py
  Tests/test_mode_i16.py
  Tests/test_numpy.py
  Tests/test_pickle.py
Labels: Testing

#6651 Updated harfbuzz to 5.3.0
  winbuild/build_prepare.py
Labels: Dependency, Hacktoberfest-accepted

#6650 Moved mode check outside of loops
  src/libImaging/Paste.c
Labels: Performance

#6633 Improved layout_engine documentation
  src/PIL/ImageFont.py
Labels: Documentation

#6654 Raise an error when allocating translucent color to RGB palette
  Tests/test_image_access.py
  Tests/test_imagepalette.py
  src/PIL/ImagePalette.py
Labels: Palette

#6449 Added DDS BC6 reading
  Tests/images/bc6h.dds
  Tests/images/bc6h.png
  Tests/images/bc6h_sf.dds
  Tests/images/bc6h_sf.png
  Tests/images/unimplemented_dxgi_format.dds
  Tests/test_file_dds.py
  src/PIL/DdsImagePlugin.py
  src/decode.c
  src/libImaging/BcnDecode.c
Labels: automerge

#6579 Pad IM palette to 768 bytes when saving
  Tests/test_file_im.py
  src/PIL/ImImagePlugin.py
Labels: Palette

#6582 Removed EXIF prefix when saving WebP
  Tests/test_file_webp_metadata.py
  src/PIL/WebPImagePlugin.py
Labels: WebP, Exif

#6517 Round box position to integer when pasting embedded color
  Tests/images/text_float_coord.png
  Tests/images/text_float_coord_1_alt.png
  Tests/test_imagefont.py
  src/PIL/ImageDraw.py
Labels: Font Rendering

#6592 If first GIF frame has transparency for RGB_ALWAYS loading strategy, use RGBA mode
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6626 Allow FLI palette chunk to not be first
  Tests/images/hopper_palette_chunk_second.fli
  Tests/test_file_fli.py
  src/PIL/FliImagePlugin.py
Labels: Palette

#6638 High bit depth multichannel images are not yet supported
  docs/handbook/concepts.rst
Labels: Documentation

#6660 Removed print statement from tests
  Tests/test_imagemath.py
Labels: Testing

#6664 Updated zlib to 1.2.13
  winbuild/build_prepare.py
Labels: Windows, Dependency, automerge

#6662 Image channel is used when converting PA with an RGBA palette
  src/PIL/Image.py
Labels: Documentation, Palette, Conversion

#6576 Fixed seeking to an L frame in a GIF
  Tests/images/no_palette_after_rgb.gif
  Tests/images/palette_not_needed_for_second_frame.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#6644 Do not attempt normalization if mode is already normal
  Tests/test_image_convert.py
  src/PIL/Image.py
Labels: Conversion

#6647 Added conversion between RGB/RGBA/RGBX and LAB
  Tests/test_image_convert.py
  src/PIL/Image.py
Labels: Conversion

#6668 Added release notes for #6449 and #6611
  docs/releasenotes/9.1.0.rst
  docs/releasenotes/9.3.0.rst
Labels: Documentation

#6669 Updated harfbuzz to 5.3.1
  winbuild/build_prepare.py
Labels: Dependency

#6659 pylint warnings
  Tests/helper.py
  Tests/test_file_jpeg.py
  Tests/test_file_libtiff.py
  Tests/test_file_png.py
  Tests/test_file_ppm.py
  Tests/test_file_tiff.py
  Tests/test_image.py
  Tests/test_image_access.py
  Tests/test_imagemath.py
  setup.py
Labels: Cleanup

#6677 Consistently write in binary format in PPM tests
  Tests/test_file_ppm.py
Labels: Testing, automerge

#6680 Added release notes for #6678
  docs/releasenotes/9.3.0.rst
Labels: Documentation

#6674 Added support for reading BMP images with RLE4 compression
  Tests/test_file_bmp.py
  docs/handbook/image-file-formats.rst
  src/PIL/BmpImagePlugin.py
Labels: BMP, automerge

#6682 Document when BLP1 JPEG data started being loaded incorrectly
  docs/releasenotes/9.3.0.rst
Labels: Documentation

#6630 Added ExifTags enums
  docs/reference/ExifTags.rst
  src/PIL/ExifTags.py
Labels: Exif

#6685 Added release notes for #6630
  docs/releasenotes/9.3.0.rst
Labels: Documentation

#6533 Document ImageDraw attributes
  docs/reference/ImageDraw.rst
  src/PIL/ImageDraw.py
Labels: Documentation

#6418 Release Python GIL when converting images using matrix operations
  src/libImaging/Matrix.c
Labels: Performance

#6686 GitHub Actions: Test Python 3.11.0 final
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#6690 Fix malloc in _imagingft.c:font_setvaraxes
  src/_imagingft.c
Labels: Fonts

#6562 Windows build improvements
  .github/workflows/test-windows.yml
  Tests/fonts/LICENSE.txt
  Tests/fonts/OpenSans.woff2
  Tests/images/hopper_lzma.tif
  Tests/images/hopper_webp.png
  Tests/images/hopper_webp.tif
  Tests/images/test_woff2.png
  Tests/test_file_libtiff.py
  Tests/test_imagefont.py
  winbuild/build_prepare.py
Labels: Windows

#6445 Fixed set_variation_by_name offset
  Tests/images/variation_adobe_name.png
  Tests/images/variation_adobe_older_harfbuzz_name.png
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
Labels: Fonts

#6532 Upload fribidi.dll to GitHub Actions
  .github/workflows/test-windows.yml
  winbuild/build_prepare.py
Labels: Windows

#6696 Update release notes for 9.3.0
  docs/releasenotes/9.3.0.rst
Labels: Documentation

#6697 GHA: replace deprecated set-output command with GITHUB_OUTPUT file
  .github/workflows/test-windows.yml
Labels: Windows

#6695 Double quotes for old CPython on Windows
  setup.py
Labels: Windows

#6330 Fix memory leaks related to text features
  src/_imagingft.c
Labels: Memory

#6329 Inline fname2char to fix memory leak
  src/Tk/tkImaging.c
Labels: Memory

#6700 Limit SAMPLESPERPIXEL to avoid runtime DOS
  Tests/images/oom-225817ca0f8c663be7ab4b9e717b02c661e66834.tif
  Tests/test_file_tiff.py
  docs/releasenotes/9.3.0.rst
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#6699 Initialize libtiff buffer when saving
  Tests/test_file_pdf.py
  docs/releasenotes/9.3.0.rst
  src/libImaging/TiffDecode.c
Labels: TIFF

#6703 Add xfail mark to TestEmbeddable
  Tests/test_image_access.py
Labels: Windows, Testing
