Repository python-pillow/Pillow, pull requests merged in 2022-09, with the labels that each got.

#6546 Documented TGA save keyword arguments
  docs/handbook/image-file-formats.rst
Labels: Documentation

#6531 Parametrize more tests
  Tests/test_image_filter.py
  Tests/test_image_reduce.py
  Tests/test_image_transform.py
Labels: Testing

#6570 Move some static config to setup.cfg
  setup.cfg
  setup.py
Labels: Packaging

#6534 Use fixtures instead of classes in test_imagefont
  Tests/test_imagefont.py
Labels: Testing

#6500 Corrected BMP and TGA palette size when saving
  Tests/test_file_bmp.py
  Tests/test_file_tga.py
  src/PIL/BmpImagePlugin.py
  src/PIL/TgaImagePlugin.py
Labels: Palette

#6591 Updated harfbuzz to 5.2.0
  winbuild/build_prepare.py
Labels: automerge

#6593 Corrected dictionary name
  docs/reference/ExifTags.rst
Labels: Documentation

#6597 Add OpenSSF Best Practices badge
  README.md
  docs/index.rst
Labels: Documentation

#6599 Fix Renovate config
  .github/renovate.json
Labels: Dependency

#6543 Allow remap_palette() to return an image with less than 256 palette entries
  Tests/test_image.py
  src/PIL/Image.py
Labels: Palette

#6548 Fixed GIF remapping to palette with duplicate entries
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF, Palette

#6609 Updated Ghostscript to 10.0.0
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Windows, Dependency

#6613 Updated redirected URLs
  docs/deprecations.rst
  docs/installation.rst
  docs/reference/ImageDraw.rst
  src/PIL/ImageFont.py
  src/libImaging/TiffDecode.c
  src/thirdparty/raqm/README.md
Labels: Documentation

#6281 Updated codecov action to v3
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#6567 Defer parsing of palette into colors
  src/PIL/ImagePalette.py
Labels: Palette, Performance

#6617 Fixed broken URLs
  docs/releasenotes/5.2.0.rst
  docs/releasenotes/versioning.rst
Labels: Documentation, automerge

#6612 Ensure dependencies are installed when building docs
  .github/workflows/test.yml
  Makefile
  docs/Makefile
Labels: Documentation, automerge

#6596 Improved palette handling in ImageOps
  Tests/test_imageops.py
  src/PIL/ImageOps.py
Labels: Palette

#6621 Add "concurrency" to GitHub Actions
  .github/workflows/cifuzz.yml
  .github/workflows/lint.yml
  .github/workflows/release-drafter.yml
  .github/workflows/stale.yml
  .github/workflows/test-cygwin.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-valgrind.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  .github/workflows/tidelift.yml
Labels: Testing

#6569 Added reading of TIFF child images
  Tests/images/child_ifd.tiff
  Tests/images/child_ifd_jpeg.tiff
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
  src/PIL/TiffTags.py
Labels: TIFF

#6625 Improve documentation for ImageDraw.rectangle and rounded_rectangle
  docs/reference/ImageDraw.rst
Labels: Documentation
