Repository python-pillow/Pillow, pull requests merged in 2022-11, with the labels that each got.

#6711 Updated lcms2 to 2.14
  docs/installation.rst
  winbuild/build_prepare.py
Labels: Dependency

#6712 XCB will not be used by default on Linux if gnome-screenshot is present
  Tests/test_imagegrab.py
Labels: Linux, Testing, Screen grab

#6702 Disable __CxxFrameHandler4 when compiling HarfBuzz
  winbuild/build_prepare.py
Labels: Build, Windows

#6719 Added file to list of partially supported BMPs
  Tests/test_bmp_reference.py
Labels: Testing, BMP

#6704 CVE-2007-4559 patch in winbuild
  winbuild/build_prepare.py
Labels: Windows

#6723 Updated AppVeyor to Python 3.11
  .appveyor.yml
Labels: Windows, Testing

#6724 Added Interop to ExifTags
  docs/reference/ExifTags.rst
  src/PIL/ExifTags.py
Labels: Exif

#6727 Revert "Install NumPy with OpenBLAS"
  .github/workflows/macos-install.sh
Labels: Testing, NumPy

#6734 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#6717 Add oss-fuzz badge
  README.md
  docs/index.rst
Labels: Documentation

#6736 Remove ImagingAccessInit line() method
  src/PIL/PyAccess.py
  src/libImaging/Access.c
  src/libImaging/Imaging.h
Labels: Cleanup

#6738 Updated xz to 5.2.8
  winbuild/build_prepare.py
Labels: Windows

#6742 Added Fedora 37
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Linux, Testing

#6747 Added WebP encoding with exact config
  Tests/test_file_webp_alpha.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/9.4.0.rst
  src/PIL/WebPImagePlugin.py
  src/_webp.c
Labels: WebP, automerge

#6752 Updated libpng to 1.6.39
  winbuild/build_prepare.py
Labels: Windows, Dependency

#6758 Added getxmp() to WebPImagePlugin
  Tests/test_file_webp_metadata.py
  docs/releasenotes/9.4.0.rst
  src/PIL/WebPImagePlugin.py
Labels: WebP

#6756 Document how to install Pillow from a directory
  docs/installation.rst
Labels: Documentation

#6763 Fix WebP dealloc method definitions
  src/_webp.c
Labels: WebP
