Repository python-pillow/Pillow, pull requests merged in 2023-01, with the labels that each got.

#6850 Added release notes for #6842 and #6846
  docs/releasenotes/9.4.0.rst
Labels: Documentation, automerge

#6851 Updated size parameter descriptions
  src/PIL/Image.py
Labels: Documentation, automerge

#6854 array tobytes() always exists in Python >= 3.2
  Tests/test_imagepath.py
Labels: Testing

#6859 NotImplementedError will not be raised by grapclipboard if xclip is available on Linux
  Tests/test_imagegrab.py
Labels: Linux, Testing

#6856 LOAD_TRUNCATED_IMAGES may allow PNG images to open
  src/PIL/__init__.py
Labels: Documentation

#6761 Support arbitrary number of loaded modules on Windows
  src/Tk/tkImaging.c
Labels: Windows

#6868 Refer to Resampling enum
  docs/handbook/concepts.rst
  docs/reference/Image.rst
  docs/releasenotes/2.7.0.rst
  src/PIL/ImageOps.py
Labels: Documentation

#6869 Simplify isinstance, key in dict, enumerate
  Tests/test_file_mpo.py
  Tests/test_file_png.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/PdfParser.py
  src/PIL/PsdImagePlugin.py
  src/PIL/TiffImagePlugin.py
  winbuild/build_prepare.py
Labels: Cleanup

#6870 Tests: Convert internal check() functions to use parametrize
  Tests/test_file_gif.py
  Tests/test_image_mode.py
Labels: Cleanup, Testing

#6876 List Raqm build options in installation documentation
  docs/installation.rst
Labels: Documentation

#6874 Raise ValueError for BoxBlur filter with negative radius
  Tests/test_image_filter.py
  src/PIL/ImageFilter.py
  src/libImaging/BoxBlur.c
Labels: Bug

#6881 Verify the Mastodon docs link
  docs/index.rst
Labels: Documentation

#6883 Updated xz to 5.4.1
  winbuild/build_prepare.py
Labels: Windows, Dependency

#6885 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#6884 Updated raqm to 0.10.0
  depends/install_raqm.sh
  src/thirdparty/raqm/README.md
  src/thirdparty/raqm/raqm-version.h
  src/thirdparty/raqm/raqm.c
  src/thirdparty/raqm/raqm.h
Labels: Windows, Dependency

#6886 Only install python-pyqt6 package on 64-bit
  .github/workflows/test-mingw.yml
Labels: Windows, Testing, automerge

#6898 Parametrize test_file_tar::test_sanity()
  Tests/test_file_tar.py
Labels: Testing, automerge

#6901 Updated libimagequant to 4.0.5
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#6906 Updated libimagequant to 4.1.0
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency, automerge

#6907 Specify correct description for mode L
  docs/handbook/concepts.rst
Labels: Documentation

#6917 Prevent register_open from adding duplicates to ID
  Tests/test_image.py
  src/PIL/Image.py
Labels: automerge

#6920 pre-commit autoupdate
  .pre-commit-config.yaml
Labels: automerge
