Repository python-pillow/Pillow, pull requests merged in 2023-12, with the labels that each got.

#7590 Update Windows wheels info
  RELEASING.md
  docs/installation.rst
Labels: Documentation

#7555 Correct PDF palette size when saving
  src/PIL/PdfImagePlugin.py
Labels: Palette

#7599 Optimization of ImageStat.Stat._getcount method
  src/PIL/ImageStat.py
Labels: Performance

#7597 Use list comprehensions to create transformed lists
  Tests/test_file_apng.py
  src/PIL/FpxImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageCms.py
  src/PIL/ImageOps.py
  src/PIL/ImagePalette.py
  src/PIL/ImageQt.py
  src/PIL/ImageStat.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MicImagePlugin.py
  src/PIL/PcfFontFile.py
  src/PIL/SpiderImagePlugin.py
Labels: Performance

#7601 Document JPEG `streamtype` option
  docs/handbook/image-file-formats.rst
Labels: Documentation, JPEG

#7578 Handle pathlib.Path in FreeTypeFont
  Tests/test_imagefont.py
  docs/reference/ImageFont.rst
  src/PIL/ImageFont.py
Labels: Fonts

#7593 Optimize ImageStat.Stat._getextrema function
  src/PIL/ImageStat.py
Labels: Performance

#7608 Added release notes
  docs/releasenotes/10.2.0.rst
Labels: Documentation

#7615 Update pre-commit to fix Sphinx Lint
  .pre-commit-config.yaml
Labels: Testing

#7600 Clarify default anchor alignment
  docs/reference/ImageDraw.rst
  src/PIL/ImageFont.py
Labels: Documentation

#7623 ImageMath: Inline `isinstance` check
  src/PIL/ImageMath.py
Labels: Cleanup

#7622 Check types with mypy
  .github/workflows/lint.yml
  pyproject.toml
  tox.ini
Labels: Testing

#7515 Handle disposing GIF background from outside palette
  Tests/images/background_outside_palette.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#7521 Corrected duration when combining multiple GIF frames into single frame
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#7548 Determine mask mode in Python instead of C
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: Cleanup

#7560 Removed unnecessary string length check
  src/PIL/ImageFont.py
Labels: Cleanup

#7568 Fill identical pixels with transparency in subsequent frames when saving GIF
  Tests/test_file_gif.py
  docs/handbook/image-file-formats.rst
  src/PIL/GifImagePlugin.py
  src/PIL/ImagePalette.py
Labels: GIF

#7629 Compile FriBiDi for Windows ARM64
  .github/workflows/wheels.yml
  winbuild/build_prepare.py
  winbuild/fribidi.cmake
Labels: Windows

#7638 Added TarIO type hints
  src/PIL/ContainerIO.py
  src/PIL/TarIO.py
Labels: Type hints

#7640 Added type hints to selftest.py, docs/conf.py and docs/example/anchors.py
  docs/conf.py
  docs/example/anchors.py
  selftest.py
Labels: Type hints

#7616 Added trusted PyPI publishing
  .github/workflows/wheels.yml
Labels: Release

#7641 Optimise `ImageMode.getmode` using `functools.lru_cache`
  src/PIL/ImageMode.py
Labels: Performance

#7636 Document JPEG 2000 support for writing YCbCr and reading subsampled color
  docs/handbook/image-file-formats.rst
Labels: Documentation, JPEG

#7643 Added type hints to FontFile and subclasses
  Tests/test_fontfile.py
  src/PIL/BdfFontFile.py
  src/PIL/FontFile.py
  src/PIL/Image.py
  src/PIL/PcfFontFile.py
  src/PIL/_binary.py
Labels: Type hints

#7653 Add 'Type hints' as a release note category
  .github/release-drafter.yml
Labels: Documentation, automerge

#7647 Restored testing of ImageFont class
  Tests/test_imagefont.py
Labels: Testing

#7652 Updated RELEASING now that Trusted PyPI publishing is in use
  RELEASING.md
Labels: Documentation

#7657 Optimise `ImageColor` using `functools.lru_cache`
  src/PIL/ImageColor.py
Labels: Performance

#7656 Add type hints to PIL.ContainerIO
  src/PIL/ContainerIO.py
  src/PIL/TarIO.py
Labels: Type hints

#7659 Add type hints to _binary
  src/PIL/IptcImagePlugin.py
  src/PIL/_binary.py
Labels: Type hints

#7663 Updated copyright year
  LICENSE
  docs/COPYING
  docs/conf.py
Labels: Documentation

#7654 Support setting ROWSPERSTRIP tag
  Tests/test_file_tiff.py
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#7496 Concatenate multiple JPEG EXIF markers
  Tests/images/multiple_exif.jpg
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG, Exif

#7585 Add gcc problem matcher to test.yml
  .github/problem-matchers/gcc.json
  .github/workflows/test.yml
Labels: Testing
