Repository python-pillow/Pillow, pull requests merged in 2023-06, with the labels that each got.

#7181 Fixed saving multiple 1 mode frames to GIF
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#7141 If the clipboard fails to open on Windows, wait and try again
  src/display.c
Labels: Windows

#7200 Do not use temporary file when grabbing clipboard on Linux
  src/PIL/ImageGrab.py
Labels: Linux

#7148 Remove temporary file when error is raised
  src/PIL/EpsImagePlugin.py
  src/PIL/JpegImagePlugin.py
Labels: automerge

#7146 Fixed combining single duration across duplicate APNG frames
  Tests/test_file_apng.py
  src/PIL/PngImagePlugin.py
Labels: automerge

#7204 Document order of kernel weights
  src/PIL/ImageFilter.py
Labels: Documentation

#7205 Removed unused variables
  src/PIL/Image.py
  src/_imaging.c
  src/libImaging/Filter.c
  src/libImaging/Imaging.h
  src/libImaging/Storage.c
Labels: Cleanup

#7208 Add Debian 12 Bookworm
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#7210 Removed unused code
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: Cleanup, automerge

#7056 Do not set size unnecessarily if image fails to open
  src/PIL/EpsImagePlugin.py
Labels: Cleanup

#7078 Fixed saving TIFF multiframe images with LONG8 tag types
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#7169 Removed rectangle example from co-ordinate system documentation
  docs/handbook/concepts.rst
Labels: Documentation

#7187 Fixed calling putpalette() on L and LA images before load()
  Tests/test_image_putpalette.py
  src/libImaging/Unpack.c
Labels: Palette

#7206 Only call text_layout once in getmask2
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: Performance

#7174 Use "not in"
  src/PIL/GdImageFile.py
  src/PIL/Image.py
  src/PIL/features.py
Labels: Cleanup

#7211 Improved documention of "corners" argument for rounded_rectangle
  docs/reference/ImageDraw.rst
Labels: Documentation

#7092 Added in_place argument to ImageOps.exif_transpose()
  Tests/images/orientation_rectangle.jpg
  Tests/test_imageops.py
  src/PIL/Image.py
  src/PIL/ImageOps.py
  src/PIL/TiffImagePlugin.py
Labels: Exif, automerge

#7212 Moved QOI from Write-Only to Read-Only
  docs/handbook/image-file-formats.rst
Labels: Documentation, automerge

#7219 Change `grabclipboard()` to use PNG compression on macOS
  CHANGES.rst
  src/PIL/ImageGrab.py
Labels: macOS

#7220 Clarify that the changelog should not be updated in PRs
  .github/CONTRIBUTING.md
Labels: Documentation

#7224 Document how to install on MinGW when setuptools >= 60
  docs/installation.rst
Labels: Documentation, Build, Windows

#7175 Fixed finding dependencies on Cygwin
  .github/workflows/test-cygwin.yml
  setup.py
Labels: Windows

#7229 Update Image.show docs to list all viewers used on Linux
  src/PIL/Image.py
Labels: Documentation, Linux

#7171 Use --config-settings instead of deprecated --global-option
  .github/workflows/test-mingw.yml
  MANIFEST.in
  Makefile
  _custom_build/backend.py
  docs/installation.rst
  pyproject.toml
  tox.ini
Labels: Build

#7228 Removed support for 32-bit
  .appveyor.yml
  .github/mergify.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-windows.yml
  Tests/32bit_segfault_check.py
  Tests/check_large_memory.py
  Tests/check_large_memory_numpy.py
  Tests/test_core_resources.py
  Tests/test_file_webp.py
  Tests/test_image_putdata.py
  Tests/test_map.py
  docs/installation.rst
  docs/releasenotes/10.0.0.rst
  setup.py
  src/libImaging/ImagingUtils.h
  winbuild/build.rst
  winbuild/build_prepare.py
Labels: automerge

#7231 Updated freetype to 2.13.1
  winbuild/build_prepare.py
Labels: Windows, Dependency

#7238 Updated libwebp to 1.3.1
  depends/install_webp.sh
  winbuild/build_prepare.py
Labels: WebP, Dependency

#7233 Updated libtiff to 4.5.1
  docs/installation.rst
  winbuild/build_prepare.py
Labels: TIFF, Dependency

#7236 Do not use CFFI access by default on PyPy
  Tests/test_image_access.py
  docs/deprecations.rst
  docs/releasenotes/10.0.0.rst
  src/PIL/Image.py
  src/PIL/PyAccess.py
Labels: Performance, Deprecation

#7239 Added release notes for #7235
  docs/releasenotes/10.0.0.rst
Labels: Documentation

#7097 `Image.open()` seeks to the start of file objects
  src/PIL/Image.py
Labels: Documentation

#7123 Added alpha_only argument to getbbox()
  Tests/test_file_apng.py
  Tests/test_file_gif.py
  Tests/test_image_getbbox.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/PngImagePlugin.py
  src/_imaging.c
  src/libImaging/GetBBox.c
  src/libImaging/Imaging.h
Labels: GIF

#7199 Do not close provided file handles with libtiff
  src/PIL/TiffImagePlugin.py
  src/libImaging/TiffDecode.c
Labels: TIFF

#7230 Fix Windows build with pyproject.toml
  .appveyor.yml
  .github/workflows/test-windows.yml
  .pre-commit-config.yaml
  pyproject.toml
  setup.py
  winbuild/README.md
  winbuild/build.rst
  winbuild/build_prepare.py
Labels: Windows

#7243 Added release notes for #7123
  docs/releasenotes/10.0.0.rst
Labels: Documentation
