Repository python-pillow/Pillow, pull requests merged in 2023-10, with the labels that each got.

#7434 Removed unused code
  src/PIL/BlpImagePlugin.py
Labels: Cleanup

#7439 Updated PyPy to 7.3.13
  .github/workflows/wheels-linux.yml
  .github/workflows/wheels-macos.yml
Labels: Dependency

#7409 Updated harfbuzz to 8.2.1
  wheels/config.sh
  winbuild/build_prepare.py
Labels: Dependency

#7441 Test Python 3.12 final in GitHub Actions
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing, automerge

#7392 Added gs_binary to control Ghostscript use on all platforms
  Tests/test_file_eps.py
  docs/handbook/image-file-formats.rst
  src/PIL/EpsImagePlugin.py
Labels: Ghostscript

#7289 Set C palette to be empty by default
  Tests/test_file_gif.py
  Tests/test_image.py
  Tests/test_image_convert.py
  Tests/test_image_putpalette.py
  src/PIL/BlpImagePlugin.py
  src/PIL/Image.py
  src/libImaging/Convert.c
  src/libImaging/Palette.c
  src/libImaging/Quant.c
Labels: Palette

#7257 Corrected drawing I;16 points and writing I;16 text
  Tests/images/imagedraw_rectangle_I.png
  Tests/test_imagedraw.py
  Tests/test_imagefont.py
  src/libImaging/Draw.c
  src/libImaging/Paste.c
Labels: Bug

#7302 Allow saving I;16B images as PNG
  Tests/test_file_png.py
  src/PIL/PngImagePlugin.py
Labels: Enhancement

#7310 Added CMYK to RGB unpacker
  Tests/test_lib_pack.py
  src/libImaging/Convert.c
  src/libImaging/Convert.h
  src/libImaging/Unpack.c
Labels: Enhancement

#7303 Support BGR;15, BGR;16 and BGR;24 access, unpacking and putdata
  Tests/test_image_access.py
  Tests/test_image_putdata.py
  Tests/test_lib_pack.py
  src/_imaging.c
  src/libImaging/Access.c
  src/libImaging/Unpack.c
Labels: Enhancement

#7446 Added release notes for #7336, #7355, #7358 and #7392
  docs/releasenotes/10.1.0.rst
Labels: Documentation

#7447 Add warning to docs: Pillow > 9.5.0 no longer includes 32-bit wheels
  docs/installation.rst
Labels: Documentation

#7448 Updated redirected links
  README.md
  docs/conf.py
  docs/index.rst
Labels: Documentation

#7451 Updated brotli to 1.1.0
  winbuild/build_prepare.py
Labels: Windows, Dependency, automerge

#7452 Updated libtiff to 4.6.0
  docs/installation.rst
  wheels/config.sh
  winbuild/build_prepare.py
Labels: TIFF, Dependency, automerge

#7453 Fix libbrotli build for Windows wheels
  winbuild/build_prepare.py
Labels: Windows

#7460 Use new() instead of Image()._new()
  src/PIL/Image.py
Labels: Cleanup

#7458 Catch struct.error from truncated EXIF when reading JPEG DPI
  Tests/images/truncated_exif_dpi.jpg
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG, Exif

#7412 Added ImageOps cover method
  Tests/test_imageops.py
  docs/example/image_thumbnail.png
  docs/example/imageops_contain.png
  docs/example/imageops_cover.png
  docs/example/imageops_fit.png
  docs/example/imageops_pad.png
  docs/handbook/tutorial.rst
  docs/reference/ImageOps.rst
  docs/releasenotes/10.1.0.rst
  src/PIL/ImageOps.py
Labels: Enhancement, automerge

#7463 Updated libimagequant to 4.2.2
  depends/install_imagequant.sh
  docs/installation.rst
Labels: Dependency

#7354 Added TrueType default font to allow for different sizes
  Tests/images/default_font_freetype.png
  Tests/images/imagedraw_default_font_size.png
  Tests/test_imagedraw.py
  Tests/test_imagefont.py
  Tests/test_imagefontpil.py
  docs/reference/ImageDraw.rst
  docs/releasenotes/10.1.0.rst
  src/PIL/ImageDraw.py
  src/PIL/ImageFont.py
Labels: Fonts

#7465 Describe how to populate mode and size when writing a plugin
  docs/handbook/writing-your-own-image-plugin.rst
  docs/releasenotes/10.1.0.rst
Labels: Documentation

#7467 Update release checklist: macOS/Linux artifact is called 'wheels'
  RELEASING.md
Labels: Documentation

#7469 Fix typos in ImageOps.rst and tutorial.rst
  docs/handbook/tutorial.rst
  docs/reference/ImageOps.rst
Labels: Documentation

#7468 Skip non-wheel CI runs for tags
  .github/workflows/cifuzz.yml
  .github/workflows/docs.yml
  .github/workflows/test-cygwin.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-valgrind.yml
  .github/workflows/test.yml
Labels: Testing

#7470 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#7466 Add Python 3.12 support to Pillow 10.1.0 release notes
  docs/releasenotes/10.1.0.rst
Labels: Documentation, automerge

#7472 Updated libjpeg-turbo to 3.0.1
  wheels/config.sh
  winbuild/build_prepare.py
Labels: JPEG, Dependency

#7499 Simplified code
  src/PIL/ImageMath.py
Labels: Cleanup

#7505 Docs: Add `pypi` Sphinx role
  docs/conf.py
  docs/deprecations.rst
  docs/handbook/image-file-formats.rst
  docs/reference/ImageFont.rst
  docs/releasenotes/4.0.0.rst
  docs/releasenotes/5.0.0.rst
  docs/releasenotes/6.0.0.rst
Labels: Documentation

#7508 Updated AppVeyor to Python 3.12
  .appveyor.yml
  docs/installation.rst
Labels: Windows, Testing
