Repository python-pillow/Pillow, pull requests merged in 2023-11, with the labels that each got.

#7516 Removed Fedora 37
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Linux, Testing

#7509 Mention defusedxml and olefile in installation instructions
  docs/installation.rst
Labels: Documentation

#7520 Add CVE-2023-44271 to release notes
  docs/releasenotes/10.0.0.rst
Labels: Documentation

#7512 Docs: link exceptions to Python docs
  docs/deprecations.rst
  docs/reference/ImageFont.rst
  docs/releasenotes/10.1.0.rst
  docs/releasenotes/2.8.0.rst
  docs/releasenotes/3.4.0.rst
  docs/releasenotes/5.3.0.rst
  docs/releasenotes/5.4.1.rst
  docs/releasenotes/6.0.0.rst
  docs/releasenotes/6.1.0.rst
  docs/releasenotes/7.0.0.rst
  docs/releasenotes/7.1.2.rst
  docs/releasenotes/7.2.0.rst
  docs/releasenotes/8.0.0.rst
  docs/releasenotes/8.3.1.rst
  docs/releasenotes/9.0.0.rst
  docs/releasenotes/9.1.0.rst
Labels: Documentation

#6966 Move linting to ruff
  .editorconfig
  .flake8
  .pre-commit-config.yaml
  MANIFEST.in
  Makefile
  Tests/bench_cffi_access.py
  _custom_build/backend.py
  docs/conf.py
  pyproject.toml
  src/PIL/EpsImagePlugin.py
  src/PIL/IcnsImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFilter.py
  src/PIL/IptcImagePlugin.py
  src/PIL/PdfParser.py
  src/PIL/PyAccess.py
  winbuild/build_prepare.py
Labels: Testing

#7513 Updated xz to 5.4.5
  wheels/config.sh
  winbuild/build_prepare.py
Labels: Dependency

#7507 DOC: Add missing sections to FREETYPE2.txt
  wheels/dependency_licenses/FREETYPE2.txt
Labels: License

#7491 Implement `streamtype=1` option for tables-only JPEG encoding
  Tests/test_file_jpeg.py
  src/libImaging/JpegEncode.c
Labels: JPEG

#7530 Black and Ruff infer `target-version` from `requires-python` in `pyproject.toml`
  .pre-commit-config.yaml
  Makefile
  pyproject.toml
Labels: Testing, automerge

#7542 Test Fedora 39
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#7546 Tests: Replace `assert False` with `pytest.fail()`
  Tests/helper.py
  Tests/test_file_iptc.py
  Tests/test_file_jpeg2k.py
  Tests/test_image.py
  Tests/test_image_resize.py
  Tests/test_image_thumbnail.py
  Tests/test_imageshow.py
Labels: Testing

#7544 Release automation: create sdist on CI
  .github/workflows/wheels.yml
  RELEASING.md
Labels: Release

#7488 Allow configuring JPEG restart marker interval on save
  Tests/test_file_jpeg.py
  docs/handbook/image-file-formats.rst
  src/PIL/JpegImagePlugin.py
  src/encode.c
  src/libImaging/Jpeg.h
  src/libImaging/JpegEncode.c
Labels: Enhancement, JPEG

#7558 Add Windows 11 tested Pillow versions
  docs/installation.rst
Labels: Documentation

#7559 Windows arm64 dependency cross-compilation fixes
  winbuild/build_prepare.py
Labels: Windows

#7562 Docs: tcl/tk is no longer a build dependency
  docs/installation.rst
Labels: Documentation

#7564 Use --config-settings in external libraries list in installation.rst
  docs/installation.rst
Labels: Documentation

#7557 If absent, do not try to close fp when closing image
  Tests/test_image.py
  src/PIL/Image.py
Labels: File Closing

#7570 "optimize" default when saving GIF images
  docs/handbook/image-file-formats.rst
  src/PIL/GifImagePlugin.py
Labels: GIF

#7552 Use cibuildwheel
  .github/workflows/wheels-build.sh
  .github/workflows/wheels-dependencies.sh
  .github/workflows/wheels-linux.yml
  .github/workflows/wheels-macos.yml
  .github/workflows/wheels-test.sh
  .github/workflows/wheels.yml
  .travis.yml
  pyproject.toml
  wheels/config.sh
Labels: Build

#7572 Updated wheels README after cibuildwheel integration
  wheels/README.md
Labels: Documentation

#7579 Docs: Activate tabs based on browser's operating system
  docs/conf.py
  docs/installation.rst
  docs/resources/js/activate_tab.js
Labels: Documentation

#7563 List optional dependencies in pyproject (apart from docs and tests)
  pyproject.toml
Labels: Installation

#7581 Install cibuildwheel from requirements file
  .ci/requirements-cibw.txt
  .github/workflows/wheels.yml
  .travis.yml
Labels: Build

#7584 Improve error message when creating TrueType fonts of invalid size
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
Labels: Fonts

#7475 Updated harfbuzz to 8.3.0
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#7580 Build Windows wheels using cibuildwheel
  .github/workflows/test-windows.yml
  .github/workflows/wheels-test.ps1
  .github/workflows/wheels-test.sh
  .github/workflows/wheels.yml
  .travis.yml
  Tests/check_wheel.py
  Tests/helper.py
  Tests/test_imagegrab.py
  pyproject.toml
  winbuild/build_prepare.py
Labels: Build, Windows
