Repository python-pillow/Pillow, pull requests merged in 2023-03, with the labels that each got.

#6981 Updated lcms2 to 2.15
  docs/installation.rst
  winbuild/build_prepare.py
Labels: Dependency

#6978 Raise an error if ImageDraw co-ordinates are incorrectly ordered
  Tests/images/imagedraw_ellipse_various_sizes.png
  Tests/images/imagedraw_ellipse_various_sizes_filled.png
  Tests/test_imagedraw.py
  docs/reference/ImageDraw.rst
  src/PIL/ImageDraw.py
  src/_imaging.c
  src/libImaging/Draw.c
Labels: automerge

#6983 Updated harfbuzz to 7.1.0
  winbuild/build_prepare.py
Labels: Windows, Dependency, automerge

#6968 Fix up some pytest style issues
  Tests/test_core_resources.py
  Tests/test_decompression_bomb.py
  Tests/test_file_apng.py
  Tests/test_file_dcx.py
  Tests/test_file_fli.py
  Tests/test_file_gif.py
  Tests/test_file_ico.py
  Tests/test_file_im.py
  Tests/test_file_mpo.py
  Tests/test_file_psd.py
  Tests/test_file_spider.py
  Tests/test_file_tar.py
  Tests/test_file_tga.py
  Tests/test_file_tiff.py
  Tests/test_file_tiff_metadata.py
  Tests/test_file_webp.py
  Tests/test_imagefont.py
  Tests/test_imagefontctl.py
Labels: Testing

#6899 Log expected & actual color in image access tests
  Tests/test_image_access.py
Labels: Testing

#6990 Added release notes for #6961 and #6954
  docs/reference/ImageDraw.rst
  docs/releasenotes/9.5.0.rst
  docs/releasenotes/index.rst
Labels: Documentation

#6986 Close file pointer copy in the libtiff encoder if still open
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF, Windows

#6992 Removed missing anchor from link
  docs/installation.rst
Labels: Documentation

#6994 Run CIFuzz tests when GitHub Actions file changes
  .github/workflows/cifuzz.yml
Labels: Testing, automerge

#6993 Restore link anchor
  docs/installation.rst
Labels: Documentation

#6988 Added memoryview support to Dib.frombytes()
  Tests/test_imagewin.py
  src/display.c
Labels: Windows

#6866 Moved conversion test to test_imagecms
  Tests/test_image_convert.py
  Tests/test_imagecms.py
Labels: Testing

#6914 Remove redundant default values
  Tests/helper.py
  setup.py
  src/PIL/ImageFont.py
Labels: Cleanup

#6919 Moved tests that require libtiff
  Tests/test_file_libtiff.py
  Tests/test_file_tiff.py
Labels: TIFF, Testing

#6935 Do not raise an error if os.environ does not contain PATH
  setup.py
Labels: automerge

#6925 Added saving RGBA images as PDFs
  Tests/test_file_pdf.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/9.5.0.rst
  src/PIL/PdfImagePlugin.py
  src/libImaging/Jpeg2KEncode.c
Labels: Enhancement, automerge

#6852 Added QOI reading
  Tests/images/hopper.qoi
  Tests/images/pil123rgba.qoi
  Tests/test_file_qoi.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/9.5.0.rst
  src/PIL/QoiImagePlugin.py
  src/PIL/__init__.py
Labels: Enhancement, automerge

#7014 Remove EOL Debian 10 Buster from CI
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#7024 Fix order of arguments in docstring
  docs/reference/ImageDraw.rst
Labels: Documentation

#7025 Removed incorrect docstring
  src/PIL/ImageDraw.py
Labels: Documentation, Cleanup

#7026 Updated xz to 5.4.2
  winbuild/build_prepare.py
Labels: Windows, automerge

#7027 Restored deleted docstring
  src/PIL/ImageDraw.py
Labels: Documentation

#7029 Added Amazon Linux 2023 docker image
  .github/workflows/test-docker.yml
  docs/installation.rst
Labels: Testing

#7017 Minor improvement made to c_extension_debugging.rst
  docs/reference/c_extension_debugging.rst
Labels: Documentation

#7020 Allow libtiff_support_custom_tags to be missing
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#7016 Docs: Replace dependency sphinx-issues with builtin sphinx.ext.extlinks
  .github/workflows/docs.yml
  Makefile
  docs/Makefile
  docs/conf.py
  docs/deprecations.rst
  docs/make.bat
  docs/releasenotes/3.1.1.rst
  docs/releasenotes/3.1.2.rst
  docs/releasenotes/6.2.0.rst
  docs/releasenotes/6.2.2.rst
  docs/releasenotes/7.1.0.rst
  docs/releasenotes/8.0.1.rst
  docs/releasenotes/8.1.0.rst
  docs/releasenotes/8.1.1.rst
  docs/releasenotes/8.1.2.rst
  docs/releasenotes/8.2.0.rst
  docs/releasenotes/8.3.0.rst
  docs/releasenotes/8.3.2.rst
  docs/releasenotes/9.0.0.rst
  docs/releasenotes/9.0.1.rst
  docs/releasenotes/9.1.1.rst
  setup.cfg
Labels: Documentation

#7003 Decrement reference count
  src/_imaging.c
  src/_imagingcms.c
  src/_imagingft.c
  src/_imagingmorph.c
  src/_webp.c
Labels: Memory

#6909 Added reading of JPEG2000 comments
  Tests/images/comment.jp2
  Tests/test_file_jpeg2k.py
  docs/releasenotes/9.5.0.rst
  src/PIL/Jpeg2KImagePlugin.py
Labels: JPEG

#6996 Round duration when saving animated WebP images
  Tests/test_file_webp_animated.py
  src/PIL/WebPImagePlugin.py
Labels: WebP

#7036 Install Ghostscript using Chocolatey
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Windows, Dependency

#7034 Load before getting size in __array_interface__
  Tests/test_numpy.py
  src/PIL/Image.py
Labels: NumPy

#6903 Support custom comments and PLT markers when saving JPEG2000 images
  Tests/test_file_jpeg2k.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/9.5.0.rst
  src/PIL/Jpeg2KImagePlugin.py
  src/encode.c
  src/libImaging/Jpeg2K.h
  src/libImaging/Jpeg2KEncode.c
Labels: JPEG

#6912 Document how to create universal2 wheels
  docs/installation.rst
Labels: Documentation

#6947 Windows: compile xz with CMake
  .github/workflows/test-windows.yml
  winbuild/README.md
  winbuild/build.rst
  winbuild/build_prepare.py
Labels: Windows

#7044 Removed absolute path to ldconfig
  setup.py
Labels: Linux

#7049 Document handling of modes when converting to or from NumPy
  src/PIL/Image.py
Labels: Documentation, NumPy

#7051 Add missing word
  src/PIL/Image.py
Labels: Documentation, automerge

#7021 Do not render text if image has zero width or height
  src/PIL/ImageFont.py
Labels: Font Rendering
