Repository python-pillow/Pillow, pull requests merged in 2023-07, with the labels that each got.

#7246 Fixed deallocating mask images
  src/PIL/ImageFont.py
  src/_imagingft.c
Labels: automerge

#7254 Updated libjpeg-turbo to 3.0.0
  winbuild/build_prepare.py
Labels: Windows, JPEG, Dependency

#7258 Updated libjpeg shared library name
  Tests/oss-fuzz/build.sh
Labels: automerge

#7262 Add link to PIL.Image.Image.putpalette in WAL documentation
  docs/handbook/image-file-formats.rst
Labels: Documentation

#7264 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#7272 Updated harfbuzz to 8.0.0
  winbuild/build_prepare.py
Labels: automerge

#7280 Declare support for Python 3.12
  docs/newer-versions.csv
  setup.cfg
  tox.ini
Labels: Documentation

#7284 Do not use transparency when saving GIF if it has been removed when normalizing mode
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#7286 Include NumPy version in Cygwin pip cache key
  .github/workflows/test-cygwin.yml
Labels: Windows, Testing

#7298 Added more information about PPM formats
  docs/handbook/image-file-formats.rst
Labels: Documentation, automerge

#7296 Simplified access code
  src/libImaging/Access.c
Labels: Cleanup

#7300 Parametrized test
  Tests/test_file_jpeg2k.py
Labels: Testing

#7305 Docs: Clarify that a single value is returned, and depends on the text direction
  docs/reference/ImageDraw.rst
  src/PIL/ImageFont.py
Labels: Documentation
