Repository python-pillow/Pillow, pull requests merged in 2023-02, with the labels that each got.

#6923 Updated libjpeg-turbo to 2.1.5
  winbuild/build_prepare.py
Labels: Windows, JPEG, Dependency

#6929 Updated libjpeg-turbo to 2.1.5.1
  winbuild/build_prepare.py
Labels: Windows, JPEG, Dependency

#6931 Updated freetype to 2.13
  winbuild/build_prepare.py
Labels: Windows, Dependency, automerge

#6918 Replace SVN with Git for installing extra test images
  .appveyor.yml
  .github/workflows/test-cygwin.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-windows.yml
  .gitignore
  depends/download-and-extract.sh
  depends/install_extra_test_images.sh
Labels: Cleanup, Testing

#6939 Raise an error if EXIF data is too long when saving JPEG
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG, Exif

#6853 Relaxed child images check to allow for libjpeg
  Tests/test_file_jpeg.py
Labels: JPEG

#6930 Add description for getexif() and Exif
  src/PIL/Image.py
Labels: Documentation, Exif, automerge

#6946 Updated harfbuzz to 7.0.0
  winbuild/build_prepare.py
Labels: Windows, Dependency, automerge

#6936 Update HPND wording in LICENSE file
  LICENSE
Labels: License

#6944 Enable gcov support for codecov/codecov-action
  .github/workflows/test-docker.yml
  .github/workflows/test.yml
Labels: Testing

#6951 image-file-formats.rst: document WebP 'xmp' option
  docs/handbook/image-file-formats.rst
Labels: Documentation, WebP

#6952 Corrected documented WebP quality range
  docs/handbook/image-file-formats.rst
Labels: Documentation, WebP, automerge

#6959 Updated harfbuzz to 7.0.1
  winbuild/build_prepare.py
Labels: Windows, Dependency

#6969 Highlight code example
  docs/handbook/image-file-formats.rst
Labels: Documentation, automerge

#6961 Support saving PDF with different X and Y resolution
  Tests/test_file_pdf.py
  docs/handbook/image-file-formats.rst
  src/PIL/PdfImagePlugin.py
Labels: Enhancement

#6974 Added memoryview support to frombytes()
  Tests/test_image_frombytes.py
  src/decode.c
Labels: Enhancement

#6958 Replace Python code-blocks with double colons
  docs/deprecations.rst
  docs/handbook/image-file-formats.rst
  docs/handbook/text-anchors.rst
  docs/handbook/writing-your-own-image-plugin.rst
  docs/reference/Image.rst
  docs/reference/ImageDraw.rst
  docs/reference/ImageEnhance.rst
  docs/reference/ImageFile.rst
  docs/reference/ImageFilter.rst
  docs/reference/ImageFont.rst
  docs/reference/ImageMath.rst
  docs/reference/ImagePath.rst
  docs/reference/ImageSequence.rst
  docs/reference/ImageWin.rst
  docs/reference/PixelAccess.rst
  docs/reference/PyAccess.rst
  docs/reference/open_files.rst
  docs/releasenotes/6.1.0.rst
  docs/releasenotes/6.2.0.rst
  docs/releasenotes/7.0.0.rst
  docs/releasenotes/7.1.0.rst
  docs/releasenotes/8.2.0.rst
  docs/releasenotes/8.4.0.rst
  docs/releasenotes/9.0.0.rst
  docs/releasenotes/9.1.0.rst
  docs/releasenotes/9.2.0.rst
  src/PIL/ImageChops.py
  src/PIL/ImageFont.py
  winbuild/build.rst
Labels: Documentation
