Repository python-pillow/Pillow, pull requests merged in 2024-09, with the labels that each got.

#8302 Updated freetype to 2.13.3
  winbuild/build_prepare.py
Labels: Windows, Dependency

#8284 Updated libimagequant to 4.3.3
  depends/install_imagequant.sh
  docs/installation/building-from-source.rst
Labels: Dependency

#8344 Updated harfbuzz to 9.0.0
  winbuild/build_prepare.py
Labels: Dependency

#8230 When IFD is missing, connect get_ifd() dictionary to Exif
  Tests/test_image.py
  src/PIL/Image.py
Labels: Exif

#8237 Expand C image to match GIF frame image size
  Tests/images/test_extents_transparency.gif
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#8256 Support JPEG2000 RGBA palettes
  Tests/test_file_jpeg2k.py
  src/PIL/Jpeg2KImagePlugin.py
Labels: JPEG

#8261 Require font parameter in FreeTypeFont and truetype()
  src/PIL/ImageFont.py
Labels: Cleanup

#8286 Added writing XMP bytes to JPEG
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG

#8297 Updated oss-fuzz to Python 3.10
  Tests/oss-fuzz/python.supp
Labels: Testing

#8336 Added type hints to ImageFile.__init__()
  Tests/test_imagefile.py
  docs/example/DdsImagePlugin.py
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/CurImagePlugin.py
  src/PIL/DdsImagePlugin.py
  src/PIL/FitsImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/FpxImagePlugin.py
  src/PIL/FtexImagePlugin.py
  src/PIL/GdImageFile.py
  src/PIL/GifImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/ImtImagePlugin.py
  src/PIL/IptcImagePlugin.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/McIdasImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/MspImagePlugin.py
  src/PIL/PcdImagePlugin.py
  src/PIL/PcxImagePlugin.py
  src/PIL/PixarImagePlugin.py
  src/PIL/PpmImagePlugin.py
  src/PIL/PsdImagePlugin.py
  src/PIL/QoiImagePlugin.py
  src/PIL/SgiImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/SunImagePlugin.py
  src/PIL/TgaImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WebPImagePlugin.py
  src/PIL/XVThumbImagePlugin.py
  src/PIL/XbmImagePlugin.py
  src/PIL/XpmImagePlugin.py
Labels: Type hints

#8339 Added type hints
  .ci/requirements-mypy.txt
  Tests/oss-fuzz/fuzz_font.py
  Tests/oss-fuzz/fuzz_pillow.py
  docs/reference/internal_modules.rst
  pyproject.toml
  src/PIL/BmpImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/ImageFont.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/MspImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/_typing.py
Labels: Type hints

#8349 Canonical type comparison
  Tests/test_image_array.py
Labels: Testing, NumPy

#8351 Added type hints
  Tests/test_file_gif.py
  src/PIL/PngImagePlugin.py
Labels: Type hints

#8350 Handle duplicate EXIF header
  Tests/test_image.py
  src/PIL/Image.py
Labels: Exif

#8355 Removed unused TiffImagePlugin IFD_LEGACY_API
  docs/deprecations.rst
  docs/releasenotes/11.0.0.rst
  src/PIL/TiffImagePlugin.py
Labels: Cleanup, TIFF

#8354 Added type hints
  Tests/test_file_jpeg.py
  Tests/test_imagefile.py
  docs/conf.py
  docs/example/DdsImagePlugin.py
  docs/reference/internal_modules.rst
  setup.py
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/DdsImagePlugin.py
  src/PIL/FitsImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/MspImagePlugin.py
  src/PIL/PpmImagePlugin.py
  src/PIL/QoiImagePlugin.py
  src/PIL/SgiImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/_typing.py
  tox.ini
Labels: Type hints

#8356 Deprecate support for FreeType 2.9.0
  Tests/test_imagefont.py
  docs/deprecations.rst
  docs/releasenotes/11.0.0.rst
  src/PIL/ImageFont.py
Labels: Deprecation

#8194 Optimize getbbox() and getextrema() routines
  src/libImaging/GetBBox.c
Labels: Performance

#8358 Support converting more modes to LAB by converting to RGBA first
  Tests/test_imagecms.py
  src/PIL/Image.py
Labels: Conversion

#8361 Updated harfbuzz to 9.0.0 in wheels, except for manylinux2014
  .github/workflows/wheels-dependencies.sh
Labels: Dependency

#8364 Deprecate isImageType
  Tests/test_image.py
  docs/deprecations.rst
  docs/releasenotes/11.0.0.rst
  src/PIL/Image.py
  src/PIL/ImageMath.py
Labels: Deprecation

#8366 Improved handling of RGBA palettes when saving GIF images
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
Labels: GIF, Palette

#8352 Deprecate ICNS (width, height, scale) sizes in favour of load(scale)
  Tests/test_file_icns.py
  docs/deprecations.rst
  docs/handbook/image-file-formats.rst
  docs/releasenotes/11.0.0.rst
  src/PIL/IcnsImagePlugin.py
Labels: Deprecation

#8367 Added release notes for #8199, #8213 and #8286
  docs/releasenotes/11.0.0.rst
Labels: Documentation

#8370 Remove comments
  src/encode.c
  src/libImaging/Jpeg2K.h
  src/libImaging/Jpeg2KDecode.c
  src/libImaging/Jpeg2KEncode.c
Labels: Cleanup

#8369 Accept float stroke widths
  Tests/images/imagedraw_stroke_float.png
  Tests/test_imagedraw.py
  src/_imagingft.c
Labels: Font Rendering

#8371 Windows wheels are now grouped with the others
  wheels/README.md
Labels: Documentation

#8372 Install NumPy from PyPI for free threaded job
  .ci/install.sh
Labels: Testing, NumPy, Free-threading

#8373 Install NumPy from PyPI when testing wheels
  .github/workflows/wheels-test.sh
Labels: NumPy, Free-threading

#8374 Test NumPy with musllinux wheels
  .github/workflows/wheels-test.sh
Labels: Linux, Testing, NumPy

#8375 Updated libpng to 1.6.44
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#7916 Updated xz to 5.6.2
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8377 Removed unused ImagePath variable
  src/path.c
Labels: Cleanup, automerge

#8379 Updated macOS deployment target for Python >= 3.12 on Intel to 10.13
  .github/workflows/wheels.yml
Labels: macOS

#8381 Added release notes for #8379
  docs/releasenotes/11.0.0.rst
Labels: Documentation, macOS

#8382 Lint: Run PT016
  Tests/test_image.py
  Tests/test_imageshow.py
  pyproject.toml
Labels: Testing

#8384 Updated libjpeg-turbo to 3.0.4
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: JPEG, Dependency, automerge

#8385 Cast Dib handle to int
  Tests/test_imagewin.py
  src/PIL/ImageWin.py
Labels: Windows

#8390 Use transposed size after opening for TIFF images
  Tests/test_image_copy.py
  Tests/test_image_resize.py
  Tests/test_image_thumbnail.py
  Tests/test_numpy.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8395 Updated Ghostscript to 10.4.0
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Windows, Dependency

#8399 Updated link to OSS Fuzz issues
  README.md
  docs/index.rst
Labels: Documentation

#8404 Updated raqm to 0.10.2
  depends/install_raqm.sh
Labels: Dependency

#8403 winbuild: Build freetype.vcxproj to fix passing in custom parameters
  winbuild/build_prepare.py
Labels: Windows, Dependency

#8396 Use common test scripts for more tests
  .appveyor.yml
  .ci/test.cmd
  .ci/test.sh
  .github/workflows/test-mingw.yml
  .github/workflows/test-windows.yml
Labels: Testing

#8407 Shared imagequant libraries may be located within usr/lib64
  depends/install_imagequant.sh
Labels: Dependency

#8411 Updated harfbuzz to 10.0.0
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8415 Updated harfbuzz to 10.0.1
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8414 Updated macOS deployment target for PyPy on Intel to 10.15
  .github/workflows/wheels.yml
Labels: macOS

#8317 Fixed writing multiple StripOffsets to TIFF
  Tests/test_file_tiff.py
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8419 Updated fribidi to 1.0.16
  winbuild/build_prepare.py
Labels: Windows, Dependency

#8386 Use Capsule for WEBP saving
  Tests/test_file_webp.py
  src/PIL/WebPImagePlugin.py
  src/_webp.c
Labels: WebP

#8420 Improved copying imagequant libraries
  depends/install_imagequant.sh
Labels: Dependency

#8424 Updated harfbuzz to 10.0.1 in remaining wheels
  .github/workflows/wheels-dependencies.sh
Labels: Dependency

#8400 Check image value before use
  src/libImaging/Geometry.c
Labels: automerge

#8429 Updated macOS tested Pillow versions
  docs/installation/platform-support.rst
Labels: Documentation, macOS

#8427 Updated test environment documentation
  docs/installation/platform-support.rst
  winbuild/README.md
Labels: Documentation
