Repository python-pillow/Pillow, pull requests merged in 2024-12, with the labels that each got.

#8577 Only use start year in copyright, remove end years
  LICENSE
  docs/COPYING
  docs/conf.py
Labels: Documentation

#8582 ImageFile tile is never None
  src/PIL/ImageFile.py
Labels: Documentation

#8586 Replace python-pillow.org with python-pillow.github.io
  docs/handbook/tutorial.rst
  pyproject.toml
Labels: Documentation

#8591 Updated openjpeg to 2.5.3
  .github/workflows/wheels-dependencies.sh
  depends/install_openjpeg.sh
  docs/installation/building-from-source.rst
  winbuild/build_prepare.py
Labels: Dependency

#8533 Updated harfbuzz to 10.1.0
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8595 Updated libjpeg-turbo to 3.1.0
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: JPEG, Dependency

#8596 Test libjpeg-turbo on macOS
  .github/workflows/macos-install.sh
Labels: macOS, Testing

#8598 Updated libXau to 1.0.12
  .github/workflows/wheels-dependencies.sh
Labels: Dependency

#8500 Use zlib-ng instead of zlib
  .github/workflows/wheels-dependencies.sh
  Tests/check_wheel.py
  Tests/test_features.py
  docs/reference/features.rst
  pyproject.toml
  src/PIL/features.py
  src/_imaging.c
  winbuild/build_prepare.py
Labels: Build, Windows, macOS, Linux, Performance

#8599 Added release notes for using zlib-ng instead of zlib
  docs/releasenotes/11.1.0.rst
  docs/releasenotes/index.rst
Labels: Documentation

#8601 Use .tar.gz zlib in Windows build to match macOS and Linux
  winbuild/build_prepare.py
Labels: Build, Windows

#8494 Improved handling of RGBA palettes when saving GIF images
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#8579 Do not describe raw data as a table
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8604 Updated libjpeg-turbo and harfbuzz URLs
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Build, Windows

#8567 Derive dir from filename if root is the same in winbuild
  winbuild/build_prepare.py
Labels: Cleanup, Windows

#8606 Extract tar files with "data" filter in Windows build scripts
  winbuild/build_prepare.py
Labels: Build, Windows

#8610 Install libjpeg-turbo8-dev
  .ci/install.sh
Labels: Build, JPEG

#8612 Updated libwebp to 1.5.0
  .github/workflows/wheels-dependencies.sh
  depends/install_webp.sh
  winbuild/build_prepare.py
Labels: WebP, Dependency

#8615 Updated MakerNote capitalization
  src/PIL/ExifTags.py
  src/PIL/Image.py
Labels: Exif

#8623 Fixed indentation
  src/_imagingcms.c
  src/display.c
Labels: Cleanup

#8624 Corrected loadImageSeries type hint
  src/PIL/SpiderImagePlugin.py
Labels: Type hints

#8626 Use monkeypatch
  Tests/test_image_thumbnail.py
Labels: Testing

#8476 Include JpegImageFile layers in pickle state
  Tests/test_pickle.py
  src/PIL/Image.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG

#8499 Use register_handler
  Tests/test_file_bufrstub.py
  Tests/test_file_gribstub.py
  Tests/test_file_hdf5stub.py
Labels: Testing

#8529 Pass IFDs to libtiff as TIFF_LONG8
  src/PIL/TiffImagePlugin.py
  src/encode.c
Labels: TIFF

#8535 Raise UnidentifiedImageError when opening TIFF without dimensions
  Tests/test_imagefile.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8555 Do not create new image when exif_transpose() is used in place
  src/PIL/ImageOps.py
Labels: Cleanup

#8625 Pass file handle to ContainerIO
  Tests/test_file_container.py
Labels: Testing, Type hints

#8630 Do not use temporary file in ImageGrab.grabclipboard() on macOS
  src/PIL/ImageGrab.py
Labels: macOS

#8628 Use monkeypatch
  Tests/test_file_png.py
  Tests/test_file_ppm.py
Labels: Testing

#8631 Removed variable
  src/libImaging/Jpeg2KDecode.c
Labels: Cleanup

#8622 Added reading of J2K comments
  Tests/test_file_jpeg2k.py
  docs/releasenotes/11.1.0.rst
  src/PIL/Jpeg2KImagePlugin.py
Labels: JPEG

#8592 Support saving CMYK JP2 images
  Tests/test_file_jpeg2k.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/11.1.0.rst
  src/libImaging/Jpeg2KEncode.c
Labels: JPEG, automerge

#8627 Added release notes for writing XMP bytes to JPEG and MPO
  docs/releasenotes/11.1.0.rst
Labels: Documentation, JPEG

#8633 Populate JPEG DPI from JFIF cm density
  Tests/images/jfif_unit_cm.jpg
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG

#8635 Keep new IFDs when converting EXIF to bytes
  Tests/test_image.py
  src/PIL/Image.py
Labels: Exif

#8641 Use elif
  src/PIL/TiffImagePlugin.py
Labels: Cleanup

#8629 Restored Makernote as a deprecated enum
  docs/deprecations.rst
  docs/releasenotes/11.1.0.rst
  src/PIL/ExifTags.py
Labels: Exif, automerge

#8642 Allow saving as BigTIFF
  Tests/test_file_tiff.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/11.1.0.rst
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8644 Remove pre-C99 definitions
  docs/releasenotes/11.1.0.rst
  src/libImaging/ImPlatform.h
Labels: Cleanup, automerge

#8646 Added CentOS Stream 10
  .github/workflows/test-docker.yml
  docs/installation/platform-support.rst
Labels: Linux, Testing
