Repository python-pillow/Pillow, pull requests merged in 2024-08, with the labels that each got.

#8274 Deprecate JpegImageFile huffman_ac and huffman_dc
  Tests/test_file_jpeg.py
  docs/deprecations.rst
  docs/releasenotes/11.0.0.rst
  src/PIL/JpegImagePlugin.py
Labels: Deprecation, automerge

#8238 Lock around usages of imaging memory arenas
  src/_imaging.c
  src/libImaging/Imaging.h
  src/libImaging/Storage.c
Labels: Free-threading

#8288 Removed unused variable
  src/libImaging/Quant.c
Labels: Cleanup

#8294 Fixed sign comparison warning
  src/_imagingft.c
Labels: Cleanup

#8290 Parametrize some color_lut tests for DRYness
  Tests/test_color_lut.py
Labels: Testing

#8298 Add missing TIFF CMYK;16B reader
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8285 Added type hints
  .ci/requirements-mypy.txt
  Tests/test_imagefile.py
  docs/example/DdsImagePlugin.py
  docs/handbook/image-file-formats.rst
  docs/handbook/tutorial.rst
  docs/handbook/writing-your-own-image-plugin.rst
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MspImagePlugin.py
  src/PIL/PalmImagePlugin.py
  src/PIL/PcxImagePlugin.py
  src/PIL/PdfImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/PpmImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TgaImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/XbmImagePlugin.py
  tox.ini
  winbuild/build_prepare.py
Labels: Type hints

#8306 Log value from tag_v2 instead of tag
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8309 Lint: run more flake8-pytest-style
  .pre-commit-config.yaml
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_imagechops.py
  Tests/test_imagemorph.py
  Tests/test_tiff_ifdrational.py
  pyproject.toml
Labels: Testing

#8318 Uninstall gradle and maven on macOS 13
  .github/workflows/macos-install.sh
Labels: macOS, Testing

#8310 Move repeated code to private helper function
  src/PIL/TiffImagePlugin.py
Labels: Cleanup, TIFF

#8325 Catch defusedxml warnings
  Tests/test_file_webp_metadata.py
  Tests/test_image.py
Labels: Testing

#8326 Remove warning if NumPy failed to raise an error during conversion
  Tests/test_image_array.py
  src/PIL/Image.py
Labels: NumPy

#8322 Updated error message when saving WebP with invalid width or height
  Tests/test_file_webp.py
  src/_webp.c
Labels: WebP

#8319 Added type hints
  .appveyor.yml
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/test-cygwin.yml
  Tests/test_file_tiff.py
  Tests/test_image.py
  Tests/test_imagefile.py
  Tests/test_psdraw.py
  docs/reference/Image.rst
  src/PIL/IcoImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/IptcImagePlugin.py
  src/PIL/PSDraw.py
  src/PIL/TiffImagePlugin.py
Labels: Type hints

#8332 Corrected GitHub Actions Windows Ghostscript path
  .github/workflows/test-windows.yml
Labels: Windows, Testing

#8331 Added type hints
  Tests/test_qt_image_qapplication.py
  Tests/test_qt_image_toqimage.py
  pyproject.toml
  src/PIL/EpsImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageQt.py
Labels: Type hints

#8279 Added type hints to Image.__init__()
  Tests/test_color_lut.py
  Tests/test_file_webp.py
  Tests/test_image.py
  Tests/test_image_array.py
  Tests/test_image_convert.py
  Tests/test_image_putpalette.py
  Tests/test_image_quantize.py
  selftest.py
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/FpxImagePlugin.py
  src/PIL/GbrImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/IcnsImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageFile.py
  src/PIL/ImageTk.py
  src/PIL/IptcImagePlugin.py
  src/PIL/PalmImagePlugin.py
  src/PIL/PcdImagePlugin.py
  src/PIL/PcxImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/QoiImagePlugin.py
  src/PIL/TgaImagePlugin.py
  src/PIL/WalImageFile.py
Labels: Type hints

#8335 Drop support for EOL PyPy3.9
  .ci/install.sh
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  .github/workflows/wheels.yml
Labels: Removal
