Repository python-pillow/Pillow, pull requests merged in 2024-03, with the labels that each got.

#7779 Match mask size to pasted image size in GifImagePlugin
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#7847 Parametrize test_seek_mode functions
  Tests/test_file_container.py
Labels: Testing

#7846 Added type hints to additional tests
  Tests/check_imaging_leaks.py
  Tests/check_png_dos.py
  Tests/helper.py
  Tests/test_file_container.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_libtiff.py
  Tests/test_file_mpo.py
  Tests/test_file_png.py
  Tests/test_file_spider.py
  Tests/test_file_tiff.py
  Tests/test_image.py
  Tests/test_image_access.py
  Tests/test_image_fromqimage.py
  Tests/test_image_paste.py
  Tests/test_image_resample.py
  Tests/test_image_resize.py
  Tests/test_imagemorph.py
  Tests/test_imageops.py
  Tests/test_imageops_usm.py
  Tests/test_imagesequence.py
  Tests/test_imageshow.py
  Tests/test_mode_i16.py
  Tests/test_tiff_crashes.py
  src/PIL/EpsImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
Labels: Type hints

#7832 Move installation.rst to installation/*.rst
  docs/index.rst
  docs/installation.rst
  docs/installation/basic-installation.rst
  docs/installation/building-from-source.rst
  docs/installation/index.rst
  docs/installation/newer-versions.csv
  docs/installation/old-versions.rst
  docs/installation/older-versions.csv
  docs/installation/platform-support.rst
  docs/installation/python-support.rst
Labels: Documentation

#7852 Build macOS arm64 wheels natively
  .github/workflows/wheels-dependencies.sh
  .github/workflows/wheels-test.sh
  .github/workflows/wheels.yml
Labels: Build, macOS

#7858 Update installation docs
  docs/installation/basic-installation.rst
  docs/installation/building-from-source.rst
  docs/installation/index.rst
  docs/installation/old-versions.rst
  docs/installation/platform-support.rst
  docs/installation/python-support.rst
Labels: Documentation

#7861 Update "What about PIL?" section
  docs/about.rst
Labels: Documentation

#7862 Update CI targets on GitHub Actions
  docs/installation/platform-support.rst
Labels: Documentation, automerge

#7843 winbuild: Refactor dependency versions into constants
  winbuild/build_prepare.py
Labels: Build, Windows

#7746 Updated zlib to 1.3.1
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#7752 Updated libjpeg-turbo to 3.0.2
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: JPEG, Dependency

#7768 Updated libpng to 1.6.43
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency, automerge

#7827 Turn off nullability warnings for macOS SDK
  setup.py
Labels: Build, macOS

#7713 Use consistent arguments for load_read and load_seek
  src/PIL/EpsImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImageFile.py
  src/PIL/XpmImagePlugin.py
Labels: Cleanup

#7748 Restored testing of non-TrueType default font
  Tests/test_font_leaks.py
Labels: Testing

#7798 Use palette when loading ICO images
  Tests/test_file_ico.py
  src/PIL/IcoImagePlugin.py
Labels: Palette

#7797 Prevent opening P TGA images without a palette
  Tests/images/p_8.tga
  Tests/test_file_tga.py
  src/PIL/TgaImagePlugin.py
Labels: Palette

#7801 Decoders and encoders subclass PyDecoder and PyEncoder
  Tests/test_file_jpeg.py
  Tests/test_image.py
  Tests/test_imagefile.py
  src/PIL/Image.py
Labels: Documentation, Type hints

#7815 Updated giflib on macOS to 5.2.2
  .github/workflows/wheels-dependencies.sh
Labels: macOS, Dependency

#7749 Updated libimagequant to 4.3.0
  depends/install_imagequant.sh
  docs/installation/building-from-source.rst
Labels: Dependency

#7853 Updated libxcb to 1.16.1
  .github/workflows/wheels-dependencies.sh
Labels: Dependency

#7842 Fix logged tag name when loading Exif data
  src/PIL/Image.py
Labels: Exif

#7788 When saving GIF frame that restores to background color, do not fill identical pixels
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#7791 Use subprocess with CREATE_NO_WINDOW flag in ImageShow WindowsViewer
  src/PIL/ImageShow.py
Labels: Windows

#7644 Update UnidentifiedImageError and __version__ imports
  Tests/oss-fuzz/test_fuzzers.py
  Tests/test_file_eps.py
  Tests/test_file_psd.py
  src/PIL/ImageCms.py
Labels: Cleanup

#7880 Removed Python and NumPy pinning on Cygwin
  .github/workflows/test-cygwin.yml
  src/PIL/Image.py
Labels: NumPy

#7877 Backfill release notes with security fix details
  docs/releasenotes/10.0.0.rst
  docs/releasenotes/10.0.1.rst
  docs/releasenotes/10.2.0.rst
  docs/releasenotes/10.3.0.rst
  docs/releasenotes/2.3.1.rst
  docs/releasenotes/2.3.2.rst
  docs/releasenotes/2.5.2.rst
  docs/releasenotes/2.6.0.rst
  docs/releasenotes/2.7.0.rst
  docs/releasenotes/2.8.0.rst
  docs/releasenotes/3.0.0.rst
  docs/releasenotes/3.1.0.rst
  docs/releasenotes/3.1.1.rst
  docs/releasenotes/3.1.2.rst
  docs/releasenotes/3.2.0.rst
  docs/releasenotes/3.3.0.rst
  docs/releasenotes/3.3.2.rst
  docs/releasenotes/3.4.0.rst
  docs/releasenotes/4.0.0.rst
  docs/releasenotes/4.1.0.rst
  docs/releasenotes/4.1.1.rst
  docs/releasenotes/4.2.0.rst
  docs/releasenotes/4.2.1.rst
  docs/releasenotes/5.1.0.rst
  docs/releasenotes/5.4.1.rst
  docs/releasenotes/6.2.0.rst
  docs/releasenotes/6.2.2.rst
  docs/releasenotes/7.1.0.rst
  docs/releasenotes/7.1.1.rst
  docs/releasenotes/7.1.2.rst
  docs/releasenotes/8.0.1.rst
  docs/releasenotes/8.1.0.rst
  docs/releasenotes/8.1.1.rst
  docs/releasenotes/8.1.2.rst
  docs/releasenotes/8.2.0.rst
  docs/releasenotes/8.3.0.rst
  docs/releasenotes/8.3.1.rst
  docs/releasenotes/8.3.2.rst
  docs/releasenotes/9.0.0.rst
  docs/releasenotes/9.0.1.rst
  docs/releasenotes/9.1.1.rst
  docs/releasenotes/9.4.0.rst
  docs/releasenotes/index.rst
  docs/releasenotes/template.rst
Labels: Documentation

#7885 Update release notes
  docs/releasenotes/10.3.0.rst
  docs/releasenotes/2.3.1.rst
  docs/releasenotes/2.3.2.rst
  docs/releasenotes/2.5.2.rst
  docs/releasenotes/2.6.0.rst
  docs/releasenotes/2.7.0.rst
  docs/releasenotes/2.8.0.rst
  docs/releasenotes/3.0.0.rst
  docs/releasenotes/3.1.0.rst
  docs/releasenotes/3.1.1.rst
  docs/releasenotes/3.2.0.rst
  docs/releasenotes/3.3.0.rst
  docs/releasenotes/3.4.0.rst
  docs/releasenotes/4.0.0.rst
  docs/releasenotes/4.1.1.rst
  docs/releasenotes/4.2.0.rst
  docs/releasenotes/4.2.1.rst
  docs/releasenotes/5.1.0.rst
  docs/releasenotes/5.4.1.rst
  docs/releasenotes/6.2.0.rst
  docs/releasenotes/6.2.1.rst
  docs/releasenotes/6.2.2.rst
  docs/releasenotes/7.1.0.rst
  docs/releasenotes/7.1.1.rst
  docs/releasenotes/7.1.2.rst
  docs/releasenotes/8.1.1.rst
  docs/releasenotes/8.3.1.rst
  docs/releasenotes/8.4.0.rst
  docs/releasenotes/9.0.0.rst
  docs/releasenotes/9.1.0.rst
  docs/releasenotes/9.1.1.rst
  docs/releasenotes/9.2.0.rst
  docs/releasenotes/9.3.0.rst
  docs/releasenotes/9.5.0.rst
Labels: Documentation

#7887 Updated Ghostscript to 10.3.0
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Windows, Dependency

#7886 Updated harfbuzz to 8.3.1
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#7870 Added reading of JPEG2000 palettes
  Tests/test_file_jpeg2k.py
  src/PIL/Jpeg2KImagePlugin.py
  src/libImaging/Jpeg2KDecode.c
Labels: Palette, JPEG

#7893 Remove TIFF tag OSUBFILETYPE when saving using libtiff
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#7891 Raise ValueError if kmeans is negative
  Tests/test_image_quantize.py
  src/PIL/Image.py
  src/libImaging/Quant.c
Labels: automerge

#7904 Added release notes for #7872, #7882 and #7891
  docs/releasenotes/10.3.0.rst
Labels: Documentation

#7897 Type hints: Add PYI (flake8-pyi) to Ruff and fix errors
  Tests/test_file_libtiff.py
  Tests/test_lib_pack.py
  pyproject.toml
  src/PIL/PdfParser.py
  src/PIL/TiffTags.py
  src/PIL/_imaging.pyi
  src/PIL/_imagingcms.pyi
  src/PIL/_imagingft.pyi
  src/PIL/_imagingmath.pyi
  src/PIL/_imagingmorph.pyi
  src/PIL/_webp.pyi
Labels: Type hints

#7905 Removed references to the "current version"
  docs/handbook/image-file-formats.rst
  docs/reference/ImageFilter.rst
  docs/reference/ImagePath.rst
  src/PIL/Image.py
  src/PIL/ImageFilter.py
  src/_imagingcms.c
Labels: Documentation

#7909 Skip AppVeyor builds for irrelevant files
  .appveyor.yml
Labels: Windows, Testing

#7907 Updated xorgproto to 2024.1
  .github/workflows/wheels-dependencies.sh
Labels: macOS, Dependency

#7911 Use setup_module() to open images so they aren't opened if skipped
  Tests/test_image_fromqimage.py
Labels: Testing, Qt

#7894 Support FITS images with GZIP_1 compression
  Tests/images/m13.fits
  Tests/images/m13_gzip.fits
  Tests/test_file_fits.py
  docs/handbook/image-file-formats.rst
  src/PIL/FitsImagePlugin.py
Labels: Enhancement

#7888 Improved conversion from RGB to RGBa, LA and La
  Tests/test_image_convert.py
  src/PIL/Image.py
  src/libImaging/Convert.c
Labels: Conversion

#7917 Updated harfbuzz to 8.4.0
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#7658 Fix editable installation with custom build backend and configuration options
  .github/workflows/wheels.yml
  _custom_build/backend.py
  docs/installation/building-from-source.rst
  setup.py
  winbuild/build.rst
Labels: Build

#7918 Added RGB to I;16, I;16L and I;16B conversion
  Tests/helper.py
  src/libImaging/Convert.c
Labels: Conversion

#7920 Added RGB to I;16N conversion
  src/libImaging/Convert.c
Labels: Conversion

#7856 Corrected exiv2.org links
  Tests/test_file_jpeg.py
  src/PIL/JpegPresets.py
Labels: Documentation

#7913 Add type hints for ImageCms
  Tests/test_imagecms.py
  docs/conf.py
  docs/reference/ImageCms.rst
  pyproject.toml
  src/PIL/ImageCms.py
  src/PIL/_imagingcms.pyi
  src/_imagingcms.c
Labels: Type hints
