Repository python-pillow/Pillow, pull requests merged in 2024-07, with the labels that each got.

#8182 Remove PSFile, PyAccess and USE_CFFI_ACCESS
  .ci/install.sh
  .coveragerc
  .github/workflows/macos-install.sh
  .github/workflows/test-cygwin.yml
  .github/workflows/test-mingw.yml
  Tests/bench_cffi_access.py
  Tests/test_deprecate.py
  Tests/test_file_eps.py
  Tests/test_image_access.py
  codecov.yml
  docs/deprecations.rst
  docs/reference/PyAccess.rst
  docs/reference/index.rst
  docs/releasenotes/10.0.0.rst
  docs/releasenotes/11.0.0.rst
  docs/releasenotes/9.5.0.rst
  docs/releasenotes/index.rst
  src/PIL/EpsImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageOps.py
  src/PIL/PngImagePlugin.py
  src/PIL/PyAccess.py
  src/PIL/_deprecate.py
  tox.ini
Labels: Removal

#8186 Updated CVE URL
  docs/conf.py
Labels: Documentation, automerge

#8185 Removed Debian 11
  .github/workflows/test-docker.yml
  docs/installation/platform-support.rst
Labels: automerge

#8187 Fix incompatibility with NumPy 1.20
  src/PIL/_typing.py
Labels: NumPy, Type hints

#8191 Added type hints
  Tests/test_color_lut.py
  Tests/test_file_pcx.py
  Tests/test_image.py
  Tests/test_image_access.py
  Tests/test_image_convert.py
  Tests/test_image_load.py
  Tests/test_image_paste.py
  Tests/test_image_quantize.py
  Tests/test_image_resample.py
  Tests/test_imageops.py
  Tests/test_imagetk.py
  Tests/test_mode_i16.py
  Tests/test_numpy.py
  src/PIL/FpxImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageOps.py
  src/PIL/ImageTk.py
  src/PIL/MicImagePlugin.py
Labels: Type hints

#8189 Test NumPy on Python 3.13
  .ci/install.sh
  .github/workflows/macos-install.sh
  .github/workflows/wheels-test.sh
Labels: Testing, NumPy

#8183 Drop support for Python 3.8
  .appveyor.yml
  .ci/install.sh
  .github/workflows/test-cygwin.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  .github/workflows/wheels.yml
  Tests/helper.py
  Tests/test_file_eps.py
  Tests/test_file_gif.py
  Tests/test_file_pdf.py
  Tests/test_file_tiff.py
  Tests/test_image_resample.py
  Tests/test_image_resize.py
  Tests/test_imagedraw.py
  Tests/test_imageops_usm.py
  Tests/test_imagepath.py
  docs/installation/basic-installation.rst
  docs/installation/newer-versions.csv
  docs/installation/platform-support.rst
  docs/releasenotes/11.0.0.rst
  pyproject.toml
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageFilter.py
  src/PIL/ImageOps.py
  src/PIL/ImagePalette.py
  src/PIL/ImageTransform.py
  src/PIL/IptcImagePlugin.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/PdfParser.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/_typing.py
  tox.ini
  winbuild/README.md
  winbuild/build.rst
Labels: Removal

#8204 Added type hints
  Tests/test_imageshow.py
  src/PIL/EpsImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/FpxImagePlugin.py
  src/PIL/GbrImagePlugin.py
  src/PIL/IcnsImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageShow.py
  src/PIL/IptcImagePlugin.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WalImageFile.py
  src/PIL/WebPImagePlugin.py
Labels: Type hints

#8203 Added type hints to tests
  Tests/helper.py
  Tests/test_file_libtiff.py
  Tests/test_file_webp_animated.py
  Tests/test_image.py
  Tests/test_image_access.py
  Tests/test_image_convert.py
  Tests/test_image_getcolors.py
  Tests/test_image_putdata.py
  Tests/test_image_quantize.py
  Tests/test_image_resample.py
  Tests/test_image_transform.py
  Tests/test_imagechops.py
  Tests/test_imagecms.py
  Tests/test_imagedraw.py
  Tests/test_imagefile.py
  Tests/test_imagemorph.py
  Tests/test_imageops.py
  Tests/test_imagetk.py
  Tests/test_tiff_ifdrational.py
Labels: Type hints

#8201 Allow size argument to resize() to be a NumPy array
  Tests/test_image_resize.py
  Tests/test_numpy.py
  src/PIL/Image.py
Labels: NumPy

#8208 Check test type hints
  Tests/test_file_gif.py
  Tests/test_file_libtiff.py
  Tests/test_file_pdf.py
  Tests/test_file_tiff.py
  Tests/test_image.py
  Tests/test_imagegrab.py
  pyproject.toml
  src/PIL/Image.py
  tox.ini
Labels: Type hints

#8207 Added type hints to PdfParser
  src/PIL/PdfParser.py
Labels: Type hints

#8210 Added type hint
  Tests/test_file_pdf.py
Labels: automerge, Type hints

#8200 Test 3.13 free-threaded build on CI
  .ci/install.sh
  .github/workflows/test.yml
Labels: Testing, Free-threading

#8214 Added type hints
  Tests/test_file_mpo.py
  Tests/test_imagefile.py
  Tests/test_imagetk.py
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/ImageFile.py
  src/PIL/ImageTk.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/PsdImagePlugin.py
  src/PIL/WebPImagePlugin.py
  src/PIL/WmfImagePlugin.py
  src/PIL/_imagingtk.pyi
Labels: Type hints

#8219 Build free-threaded wheels
  .github/workflows/wheels-test.sh
  .github/workflows/wheels.yml
Labels: Free-threading

#8228 Added type hints
  Tests/test_file_png.py
  Tests/test_imagefile.py
  src/PIL/ImageFile.py
  src/PIL/ImageSequence.py
  src/PIL/JpegImagePlugin.py
  src/PIL/PdfImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WalImageFile.py
Labels: Type hints

#8216 Move away from APIs that use borrowed references under the free-threaded build
  src/_imaging.c
  src/_imagingcms.c
  src/_imagingft.c
  src/_imagingmath.c
  src/_imagingmorph.c
  src/_imagingtk.c
  src/_webp.c
  src/encode.c
  src/path.c
  src/thirdparty/pythoncapi_compat.h
Labels: Free-threading

#8235 Simplified code
  src/_imagingft.c
Labels: Cleanup

#8234 Added type hints
  Tests/test_imagewin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/ImageQt.py
  src/PIL/ImageWin.py
  src/PIL/IptcImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/PngImagePlugin.py
Labels: Type hints

#8240 Changed ContainerIO to subclass IO
  Tests/test_file_container.py
  pyproject.toml
  src/PIL/ContainerIO.py
  src/PIL/TarIO.py
Labels: Type hints

#8236 Upload wheels to scientific-python-nightly-wheels index
  .github/workflows/wheels.yml
Labels: Free-threading

#8243 Skip QEMU-emulated wheels on workflow dispatch event
  .github/workflows/wheels.yml
Labels: Free-threading

#8244 Move uploading nightly wheels to different job
  .github/workflows/wheels.yml
Labels: Free-threading

#8242 Deprecate ImageMath lambda_eval and unsafe_eval options argument
  Tests/test_imagemath_lambda_eval.py
  Tests/test_imagemath_unsafe_eval.py
  docs/deprecations.rst
  docs/reference/ImageMath.rst
  docs/releasenotes/11.0.0.rst
  src/PIL/ImageMath.py
Labels: Deprecation

#8248 Use local variable instead of casting every line
  src/encode.c
Labels: Cleanup

#8250 Added type hints
  Tests/test_file_libtiff.py
  docs/reference/ImageFile.rst
  src/PIL/ImageWin.py
  src/PIL/PsdImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/TiffTags.py
Labels: automerge, Type hints

#8246 Add tutorial images
  docs/handbook/animated_hopper.gif
  docs/handbook/contrasted_hopper.jpg
  docs/handbook/cropped_hopper.webp
  docs/handbook/enhanced_hopper.webp
  docs/handbook/flip_left_right_hopper.webp
  docs/handbook/flip_top_bottom_hopper.webp
  docs/handbook/hopper_ps.webp
  docs/handbook/masked_hopper.webp
  docs/handbook/merged_hopper.webp
  docs/handbook/pasted_hopper.webp
  docs/handbook/rebanded_hopper.webp
  docs/handbook/rolled_hopper.webp
  docs/handbook/rotated_hopper_180.webp
  docs/handbook/rotated_hopper_270.webp
  docs/handbook/rotated_hopper_90.webp
  docs/handbook/show_hopper.webp
  docs/handbook/thumbnail_hopper.jpg
  docs/handbook/transformed_hopper.webp
  docs/handbook/tutorial.rst
Labels: Documentation

#8257 Removed unused argument
  src/PIL/ImageDraw.py
Labels: Cleanup

#8260 Restore exiv2.org links
  Tests/test_file_jpeg.py
  src/PIL/JpegPresets.py
Labels: Documentation

#8259 Remove unused _util.is_directory
  Tests/test_util.py
  src/PIL/_util.py
Labels: Cleanup

#8262 Added type hints
  Tests/test_font_pcf.py
  Tests/test_imagefont.py
  docs/reference/ImageFont.rst
  docs/reference/internal_modules.rst
  pyproject.toml
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageFont.py
  src/PIL/_imaging.pyi
  src/PIL/_imagingft.pyi
Labels: Type hints

#8263 Added type hints
  Tests/test_file_iptc.py
  src/PIL/Image.py
  src/PIL/ImageDraw2.py
  src/PIL/ImageQt.py
  src/PIL/IptcImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: Type hints

#8267 Added type hints
  Tests/test_file_png.py
  src/PIL/Image.py
  src/PIL/ImageDraw2.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: Type hints

#8268 Added type hints
  src/PIL/Image.py
  src/PIL/ImageDraw2.py
  src/PIL/ImageFont.py
  src/PIL/ImagePalette.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/PdfImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: Type hints

#8270 Added type hints
  Tests/test_file_jpeg.py
  Tests/test_image.py
  docs/reference/plugins.rst
  src/PIL/EpsImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/JpegImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
Labels: Type hints
