Repository python-pillow/Pillow, pull requests merged in 2024-10, with the labels that each got.

#8413 Free memory on early return
  src/libImaging/SgiRleDecode.c
Labels: Memory

#8431 Do not convert images unnecessarily in ImageEnhance
  src/PIL/ImageEnhance.py
Labels: Performance

#8434 Updated xz to 5.6.3
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8435 Test cifuzz when wheel dependencies change
  .github/workflows/cifuzz.yml
Labels: Testing

#8442 Test Python 3.13 on AppVeyor
  .appveyor.yml
  docs/installation/platform-support.rst
Labels: Windows, Testing

#8446 Fixed unclosed file warning in test_imageshow.py
  Tests/test_imageshow.py
Labels: Testing

#8447 Removed unused code
  src/_imagingft.c
Labels: Cleanup

#8445 Simplified code
  src/_imagingmorph.c
Labels: Cleanup

#8457 Use CVE and CWE roles from Sphinx 8.1
  Makefile
  docs/Makefile
  docs/conf.py
  pyproject.toml
Labels: Documentation

#8458 Do not close provided file handles with libtiff when saving
  src/PIL/TiffImagePlugin.py
  src/libImaging/TiffDecode.c
Labels: TIFF

#8459 Always raise warnings for deprecated feature checks
  Tests/test_features.py
  src/PIL/features.py
Labels: WebP

#8461 Use ImageFile.MAXBLOCK when saving TIFF images
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8417 Support writing LONG8 offsets in AppendingTiffWriter
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8197 Conditionally define ImageCms type hint to avoid requiring core
  docs/conf.py
  src/PIL/ImageCms.py
Labels: Type hints

#8365 Removed custom build_openjpeg
  .github/workflows/wheels-dependencies.sh
Labels: Cleanup

#8392 Do not create core image in TIFF seek()
  src/PIL/TiffImagePlugin.py
Labels: TIFF, Performance

#8460 Update licence to MIT-CMU
  .pre-commit-config.yaml
  pyproject.toml
Labels: Documentation, License

#8463 Update Python 3.13 release date
  docs/releasenotes/11.0.0.rst
Labels: Documentation

#8464 Added type hints to remaining ImageMath methods
  src/PIL/ImageMath.py
Labels: Type hints

#8466 Removed Fedora 39
  .github/workflows/test-docker.yml
  docs/installation/platform-support.rst
Labels: Testing

#8469 Fixed disabling a feature during install
  setup.py
Labels: automerge

#8490 Update license to MIT-CMU
  LICENSE
  docs/about.rst
Labels: License

#8498 Added filename placeholder in winbuild URL
  winbuild/build_prepare.py
Labels: Cleanup, Windows

#8505 Fixed catching warnings
  Tests/test_bmp_reference.py
  Tests/test_file_dcx.py
  Tests/test_file_fli.py
  Tests/test_file_gif.py
  Tests/test_file_icns.py
  Tests/test_file_im.py
  Tests/test_file_jpeg.py
  Tests/test_file_mpo.py
  Tests/test_file_png.py
  Tests/test_file_psd.py
  Tests/test_file_spider.py
  Tests/test_file_tar.py
  Tests/test_file_tiff.py
  Tests/test_file_webp.py
  Tests/test_image.py
  Tests/test_imageqt.py
  Tests/test_numpy.py
Labels: Testing

#8504 Move MPO into "Fully supported formats"
  docs/handbook/image-file-formats.rst
Labels: Documentation

#8484 Use fixture to re-open image for each JPEG2000 test
  Tests/test_file_jpeg2k.py
Labels: Testing

#8496 Fix SEGFAULT from calling FT_New_Face/FT_Done_Face in multiple threads
  src/_imagingft.c
  src/thirdparty/pythoncapi_compat.h
Labels: Free-threading

#8502 brew remove libdeflate
  .github/workflows/wheels-dependencies.sh
Labels: Build, macOS

#8509 Detach PyQt6 QPixmap instance before returning
  .github/workflows/test-windows.yml
  src/PIL/ImageQt.py
Labels: Windows, Qt

#8512 Do not repeatedly save to the same path
  Tests/test_file_jpeg.py
Labels: Testing, Free-threading
