Repository python-pillow/Pillow, pull requests merged in 2024-05, with the labels that each got.

#8041 Updated codecov/codecov-action to v4
  .github/workflows/test-cygwin.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#8042 Added type hints
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/DcxImagePlugin.py
  src/PIL/DdsImagePlugin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/FliImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/Hdf5StubImagePlugin.py
  src/PIL/IcnsImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/ImageFilter.py
  src/PIL/ImageWin.py
  src/PIL/MicImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/PsdImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WalImageFile.py
  src/PIL/WebPImagePlugin.py
Labels: Type hints

#8051 Added type hints
  src/PIL/BufrStubImagePlugin.py
  src/PIL/CurImagePlugin.py
  src/PIL/FpxImagePlugin.py
  src/PIL/FtexImagePlugin.py
  src/PIL/GbrImagePlugin.py
  src/PIL/GribStubImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/ImageTk.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PSDraw.py
  src/PIL/PdfParser.py
  src/PIL/PngImagePlugin.py
  src/PIL/PyAccess.py
  src/PIL/QoiImagePlugin.py
  src/PIL/WebPImagePlugin.py
  src/PIL/WmfImagePlugin.py
  src/PIL/XpmImagePlugin.py
Labels: Type hints

#7999 Added MPEG accept function
  Tests/test_file_mpeg.py
  src/PIL/MpegImagePlugin.py
Labels: Performance

#8055 Added type hints
  src/PIL/FliImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/GimpPaletteFile.py
  src/PIL/ImImagePlugin.py
  src/PIL/ImageDraw.py
  src/PIL/ImageFilter.py
  src/PIL/ImagePalette.py
  src/PIL/ImageTk.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/PdfParser.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WebPImagePlugin.py
Labels: Type hints

#8053 Removed helper.py modes
  Tests/helper.py
  Tests/test_image.py
  Tests/test_image_access.py
Labels: Cleanup, Testing

#8061 Added type hints
  src/PIL/DdsImagePlugin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/FtexImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImageFile.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/WebPImagePlugin.py
  src/PIL/XpmImagePlugin.py
  src/PIL/features.py
Labels: Type hints

#8015 Add ClangFormat to pre-commit
  .clang-format
  .pre-commit-config.yaml
  src/Tk/tkImaging.c
  src/_imaging.c
  src/_imagingcms.c
  src/_imagingft.c
  src/encode.c
  src/libImaging/Access.c
  src/libImaging/BcnDecode.c
  src/libImaging/BoxBlur.c
  src/libImaging/Convert.c
  src/libImaging/Draw.c
  src/libImaging/Filter.c
  src/libImaging/FliDecode.c
  src/libImaging/Geometry.c
  src/libImaging/GetBBox.c
  src/libImaging/Gif.h
  src/libImaging/GifEncode.c
  src/libImaging/Imaging.h
  src/libImaging/ImagingUtils.h
  src/libImaging/Jpeg2KDecode.c
  src/libImaging/Jpeg2KEncode.c
  src/libImaging/JpegEncode.c
  src/libImaging/Paste.c
  src/libImaging/Point.c
  src/libImaging/Quant.c
  src/libImaging/QuantOctree.c
  src/libImaging/Reduce.c
  src/libImaging/Resample.c
  src/libImaging/SgiRleDecode.c
  src/libImaging/Storage.c
  src/libImaging/TiffDecode.c
  src/libImaging/TiffDecode.h
  src/libImaging/Unpack.c
  src/path.c
Labels: Testing

#8037 Use functools.cached_property in GifImagePlugin
  src/PIL/GifImagePlugin.py
Labels: GIF

#8079 Removed documentation of unused argument
  src/PIL/ImageFont.py
Labels: Documentation

#8085 Add function and documentation to draw circle
  Tests/test_imagedraw.py
  docs/reference/ImageDraw.rst
  docs/releasenotes/10.4.0.rst
  src/PIL/ImageDraw.py
Labels: Enhancement

#8090 Added type hints to additional tests
  Tests/helper.py
  Tests/test_file_webp_animated.py
  Tests/test_imagecms.py
  Tests/test_imagefile.py
  Tests/test_imagefont.py
Labels: Type hints

#8091 Added type hints to additional tests
  Tests/oss-fuzz/test_fuzzers.py
  Tests/test_features.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_libtiff.py
  Tests/test_file_png.py
  Tests/test_file_webp.py
  Tests/test_image_quantize.py
  Tests/test_image_reduce.py
  Tests/test_imageops_usm.py
Labels: Type hints
