Repository python-pillow/Pillow, pull requests merged in 2024-06, with the labels that each got.

#8095 Updated type hints for tests
  Tests/test_file_gif.py
  Tests/test_file_jpeg.py
  Tests/test_file_libtiff.py
  Tests/test_image.py
  Tests/test_image_array.py
  Tests/test_image_crop.py
  Tests/test_image_filter.py
  Tests/test_image_getextrema.py
  Tests/test_imagecms.py
  Tests/test_imagedraw.py
Labels: Type hints

#8098 Corrected type hint
  src/PIL/ImageCms.py
  src/PIL/_imagingcms.pyi
Labels: Type hints

#8099 Added type hints
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/PyAccess.py
Labels: Type hints

#8066 Added type hints
  docs/reference/ImageFile.rst
  src/PIL/BlpImagePlugin.py
  src/PIL/BufrStubImagePlugin.py
  src/PIL/DcxImagePlugin.py
  src/PIL/GimpPaletteFile.py
  src/PIL/GribStubImagePlugin.py
  src/PIL/Hdf5StubImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/ImageFilter.py
  src/PIL/ImageFont.py
  src/PIL/ImagePalette.py
  src/PIL/ImageWin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/PSDraw.py
  src/PIL/PdfParser.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WebPImagePlugin.py
  src/PIL/WmfImagePlugin.py
Labels: Type hints

#8105 Added type hints
  src/PIL/BlpImagePlugin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/FpxImagePlugin.py
  src/PIL/ImageEnhance.py
  src/PIL/ImageFilter.py
  src/PIL/ImageMorph.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/PaletteFile.py
  src/PIL/QoiImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/WebPImagePlugin.py
Labels: Type hints

#8107 Added type hints
  src/PIL/BmpImagePlugin.py
  src/PIL/BufrStubImagePlugin.py
  src/PIL/DdsImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/GribStubImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/Image.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PdfImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WmfImagePlugin.py
Labels: Type hints

#8109 Use Sphinx long options in `Makefile`
  docs/Makefile
Labels: Documentation

#8078 Updated Ghostscript to 10.3.1
  .appveyor.yml
  .github/workflows/test-windows.yml
Labels: Windows, Dependency

#8059 Updated harfbuzz to 8.5.0
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8025 Updated libimagequant to 4.3.1
  depends/install_imagequant.sh
  docs/installation/building-from-source.rst
Labels: Dependency

#7982 Updated libxcb and xcb-proto to 1.17.0
  .github/workflows/wheels-dependencies.sh
Labels: Dependency

#7973 Updated libwebp to 1.4.0
  .github/workflows/wheels-dependencies.sh
  depends/install_webp.sh
  winbuild/build_prepare.py
Labels: WebP, Dependency

#8014 Updated fribidi to 1.0.15
  winbuild/build_prepare.py
Labels: Windows, Dependency, automerge

#8048 Updated libjpeg-turbo to 3.0.3
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: JPEG, Dependency, automerge

#7990 Updated nasm to 2.16.03
  .appveyor.yml
Labels: Windows

#8046 Add various type annotations
  Tests/test_image_rotate.py
  docs/handbook/concepts.rst
  docs/reference/Image.rst
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageFont.py
  src/PIL/ImageTransform.py
  src/PIL/JpegImagePlugin.py
  src/PIL/_imaging.pyi
  src/PIL/_imagingft.pyi
Labels: Type hints

#8113 Renamed C transform2 to transform
  src/PIL/Image.py
  src/_imaging.c
Labels: Cleanup

#8115 Added type hints to ImageColor
  src/PIL/ImageColor.py
Labels: Type hints

#8117 Added type hints
  src/PIL/GifImagePlugin.py
  src/PIL/GimpGradientFile.py
  src/PIL/Image.py
  src/PIL/ImageDraw2.py
  src/PIL/ImageTk.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/PaletteFile.py
  src/PIL/TiffImagePlugin.py
Labels: Type hints

#8126 Accept 't' suffix for libtiff version
  Tests/test_features.py
Labels: TIFF, Linux, Testing

#8125 Added type hints
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/BufrStubImagePlugin.py
  src/PIL/DdsImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/GribStubImagePlugin.py
  src/PIL/Hdf5StubImagePlugin.py
  src/PIL/IcnsImagePlugin.py
  src/PIL/IcoImagePlugin.py
  src/PIL/ImImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageFile.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/JpegImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/MspImagePlugin.py
  src/PIL/PcxImagePlugin.py
  src/PIL/PdfImagePlugin.py
  src/PIL/PdfParser.py
  src/PIL/PngImagePlugin.py
  src/PIL/PpmImagePlugin.py
  src/PIL/QoiImagePlugin.py
  src/PIL/SgiImagePlugin.py
  src/PIL/SpiderImagePlugin.py
  src/PIL/TgaImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/WebPImagePlugin.py
  src/PIL/WmfImagePlugin.py
  src/PIL/XbmImagePlugin.py
Labels: Type hints

#8128 Added type hints to GifImagePlugin
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/ImageOps.py
  src/PIL/ImagePalette.py
Labels: Type hints

#8124 Deprecate ImageDraw.getdraw hints parameter
  Tests/test_imagedraw.py
  docs/deprecations.rst
  docs/releasenotes/10.4.0.rst
  src/PIL/ImageDraw.py
Labels: Deprecation

#8132 Added type hints
  src/PIL/BlpImagePlugin.py
  src/PIL/BmpImagePlugin.py
  src/PIL/DdsImagePlugin.py
  src/PIL/EpsImagePlugin.py
  src/PIL/FitsImagePlugin.py
  src/PIL/FpxImagePlugin.py
  src/PIL/ImageFile.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/MicImagePlugin.py
  src/PIL/MpoImagePlugin.py
  src/PIL/PSDraw.py
  src/PIL/PalmImagePlugin.py
  src/PIL/PdfParser.py
  src/PIL/PngImagePlugin.py
  src/PIL/TarIO.py
  src/PIL/TiffImagePlugin.py
Labels: Type hints

#8136 Use latest Ubuntu on Read The Docs
  .readthedocs.yml
Labels: Documentation

#8138 Corrected AppVeyor Ghostscript path
  .appveyor.yml
Labels: Windows, Testing

#8140 Ignore brew dependencies for libraqm on macOS 13
  .github/workflows/macos-install.sh
Labels: macOS, Testing

#8142 Use pkg-config to help find libwebp and raqm
  setup.py
Labels: Build

#8118 Added type hints to additional tests
  Tests/test_decompression_bomb.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_tiff.py
  Tests/test_image.py
  Tests/test_image_mode.py
  Tests/test_image_putdata.py
  Tests/test_image_quantize.py
  Tests/test_image_reduce.py
  Tests/test_image_thumbnail.py
  Tests/test_imagedraw.py
  Tests/test_imagefont.py
  Tests/test_imageops.py
  Tests/test_imagewin_pointers.py
  Tests/test_main.py
  Tests/test_numpy.py
  Tests/test_shell_injection.py
Labels: Type hints

#8134 Added type hints
  src/PIL/BdfFontFile.py
  src/PIL/ImageDraw.py
  src/PIL/ImagePalette.py
  src/PIL/MicImagePlugin.py
  src/PIL/PngImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/PIL/_imaging.pyi
  src/PIL/features.py
Labels: Type hints

#8150 Added type hints to Image
  src/PIL/FitsImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/PIL/Jpeg2KImagePlugin.py
  src/PIL/PalmImagePlugin.py
  src/PIL/_imaging.pyi
Labels: Type hints

#8151 Added type hints to ImageDraw shape methods
  Tests/test_imagedraw.py
  src/PIL/ImageDraw.py
  src/PIL/_imaging.pyi
Labels: Type hints

#8135 Improve `ImageFont.freetype` support for XDG directories on Linux
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
Labels: Linux, Fonts

#8159 Removed support for Qt 5
  Tests/test_imageqt.py
  src/PIL/ImageQt.py
Labels: Cleanup, Qt

#7966 Support unpacking more rawmodes to RGBA palettes
  Tests/test_image_putpalette.py
  src/PIL/DdsImagePlugin.py
  src/PIL/GifImagePlugin.py
  src/PIL/Image.py
  src/_imaging.c
Labels: Palette

#8156 Added type hints to ImageFilter
  Tests/test_color_lut.py
  Tests/test_image_filter.py
  Tests/test_numpy.py
  docs/reference/internal_modules.rst
  src/PIL/ImageFilter.py
  src/PIL/_typing.py
Labels: Type hints

#8153 Updated type hints
  Tests/helper.py
  Tests/test_file_jpeg.py
  Tests/test_file_png.py
  Tests/test_file_ppm.py
  Tests/test_file_tiff.py
  Tests/test_font_leaks.py
  Tests/test_image.py
  Tests/test_image_draft.py
  Tests/test_image_paste.py
  Tests/test_image_point.py
  Tests/test_image_putdata.py
  Tests/test_image_resample.py
  Tests/test_imagecms.py
  Tests/test_imagedraw.py
  Tests/test_imagedraw2.py
  Tests/test_imagefile.py
  Tests/test_imagefont.py
  Tests/test_imagefontpil.py
  Tests/test_imagepalette.py
  Tests/test_psdraw.py
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageFont.py
  src/PIL/ImageQt.py
  src/PIL/ImageTransform.py
  src/PIL/JpegImagePlugin.py
  src/PIL/TiffTags.py
Labels: Type hints

#8163 Added type hints to additional tests
  Tests/test_file_bufrstub.py
  Tests/test_file_gribstub.py
  Tests/test_file_hdf5stub.py
  Tests/test_file_png.py
  Tests/test_file_ppm.py
  Tests/test_file_psd.py
  Tests/test_file_tiff_metadata.py
  Tests/test_file_webp.py
  Tests/test_image.py
  Tests/test_image_array.py
  Tests/test_imagefile.py
  Tests/test_imagefont.py
  Tests/test_imagewin_pointers.py
  Tests/test_psdraw.py
Labels: Type hints

#8032 Added type hints for PixelAccess related methods and others
  Tests/test_imagegrab.py
  docs/reference/ImageDraw.rst
  docs/reference/PixelAccess.rst
  docs/reference/PyAccess.rst
  src/PIL/Image.py
  src/PIL/ImageDraw.py
  src/PIL/ImageGrab.py
  src/PIL/PyAccess.py
  src/PIL/_imaging.pyi
Labels: Type hints

#8167 Added type hints
  Tests/test_file_spider.py
  Tests/test_imagefile.py
  Tests/test_imageops_usm.py
  Tests/test_imagepalette.py
  src/PIL/BlpImagePlugin.py
  src/PIL/ImageDraw2.py
  src/PIL/ImageFile.py
  src/PIL/ImagePalette.py
  src/PIL/ImageWin.py
  src/PIL/SpiderImagePlugin.py
Labels: Type hints

#7948 Only preserve TIFF IPTC_NAA_CHUNK tag if type is BYTE or UNDEFINED
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#7963 Converted example images to WebP
  docs/deprecations.rst
  docs/example/anchors.png
  docs/example/anchors.py
  docs/example/anchors.webp
  docs/example/image_thumbnail.png
  docs/example/image_thumbnail.webp
  docs/example/imageops_contain.png
  docs/example/imageops_contain.webp
  docs/example/imageops_cover.png
  docs/example/imageops_cover.webp
  docs/example/imageops_fit.png
  docs/example/imageops_fit.webp
  docs/example/imageops_pad.png
  docs/example/imageops_pad.webp
  docs/example/size_vs_bbox.png
  docs/example/size_vs_bbox.webp
  docs/handbook/text-anchors.rst
  docs/handbook/tutorial.rst
  docs/reference/ImageOps.rst
  docs/releasenotes/9.2.0.rst
Labels: Documentation

#7997 Read IM and TIFF images as RGB, rather than RGBX
  src/PIL/ImImagePlugin.py
  src/PIL/TiffImagePlugin.py
  src/libImaging/Unpack.c
Labels: TIFF

#8141 Added byte support to FreeTypeFont
  Tests/test_imagefont.py
  src/PIL/ImageFont.py
  src/PIL/_imagingft.pyi
  src/_imagingft.c
Labels: Font Rendering

#8168 Use more specific error
  Tests/test_file_jpeg2k.py
Labels: Testing

#8169 Simplified casts
  src/PIL/Image.py
Labels: Type hints

#8110 Do not preserve EXIFIFD tag by default when saving TIFF images
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8127 Fixed processing multiple JPEG EXIF markers
  Tests/images/multiple_exif.jpg
  Tests/test_file_jpeg.py
  src/PIL/JpegImagePlugin.py
Labels: JPEG, Exif

#8031 Deprecate non-image ImageCms modes
  Tests/test_imagecms.py
  docs/deprecations.rst
  docs/releasenotes/10.4.0.rst
  src/PIL/ImageCms.py
  src/_imagingcms.c
Labels: Deprecation
