Repository python-pillow/Pillow, pull requests merged in 2024-01, with the labels that each got.

#7650 Allow uncompressed TIFF images to be saved in chunks
  Tests/test_file_tiff.py
  Tests/test_file_tiff_metadata.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#7664 Deprecate IptcImagePlugin helpers
  Tests/test_file_iptc.py
  docs/deprecations.rst
  docs/releasenotes/10.2.0.rst
  src/PIL/Image.py
  src/PIL/IptcImagePlugin.py
Labels: Deprecation

#7666 Coverage: add more exclusions
  .coveragerc
  Tests/test_imagemorph.py
Labels: Testing

#7669 Do not try and crop glyphs from outside of source ImageFont image
  Tests/test_imagefontpil.py
  docs/releasenotes/10.2.0.rst
  src/PIL/ImageFont.py
  src/_imaging.c
Labels: Font Rendering

#7668 Removed unnecessary "pragma: no cover"
  src/PIL/ImageFilter.py
Labels: Cleanup

#7670 Added release notes for #7589 and #7654
  docs/releasenotes/10.2.0.rst
Labels: Documentation

#7665 Release notes: add `ImageColor` and `ImageMode` optimisations, and type hints
  docs/PIL.rst
  docs/releasenotes/10.2.0.rst
Labels: Documentation

#7642 Add type hints to _util
  Tests/test_util.py
  docs/reference/internal_modules.rst
  pyproject.toml
  src/PIL/Image.py
  src/PIL/ImageCms.py
  src/PIL/ImageFile.py
  src/PIL/ImageFont.py
  src/PIL/PyAccess.py
  src/PIL/_imagingcms.pyi
  src/PIL/_imagingft.pyi
  src/PIL/_typing.py
  src/PIL/_util.py
  tox.ini
Labels: Type hints

#7671 Added type hints to ImageTransform
  docs/releasenotes/10.2.0.rst
  src/PIL/Image.py
  src/PIL/ImageTransform.py
Labels: Type hints

#7553 Add `keep_rgb` option when saving JPEG to prevent conversion of RGB colorspace
  Tests/test_file_jpeg.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/10.2.0.rst
  src/PIL/JpegImagePlugin.py
  src/encode.c
  src/libImaging/Jpeg.h
  src/libImaging/JpegEncode.c
Labels: JPEG

#7674 Fix image URL in "Reading from URL" example
  docs/handbook/tutorial.rst
Labels: Documentation

#7681 Package name is now lowercase in wheel filenames
  RELEASING.md
Labels: Documentation

#7682 Skip PyPy3.8 Windows wheel
  .github/workflows/wheels.yml
Labels: Windows

#7678 ImageGrab.grab() bbox on macOS is not 2x on retina screens
  docs/reference/ImageGrab.rst
Labels: Documentation, macOS, Screen grab

#7685 Update Windows 11 tested versions
  docs/installation.rst
Labels: Documentation, Windows

#7689 Updated macOS tested Pillow versions
  docs/installation.rst
Labels: Documentation, macOS

#7688 If ImageGrab.grab() bbox is omitted, screenshot is taken at 2x on Retina screens
  docs/reference/ImageGrab.rst
Labels: Documentation, macOS, Screen grab

#7692 Skip non-wheel CI runs for tags: Windows
  .github/workflows/test-windows.yml
Labels: Windows, Testing

#7690 Build QEMU-emulated Linux aarch64 wheels on GitHub Actions instead of Travis CI
  .github/workflows/test-cygwin.yml
  .github/workflows/test-docker.yml
  .github/workflows/test-mingw.yml
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
  .github/workflows/wheels.yml
  .travis.yml
  README.md
  RELEASING.md
  docs/about.rst
  docs/index.rst
Labels: Release

#7684 Improve ImageTransform documentation
  docs/PIL.rst
  docs/reference/ImageTransform.rst
  docs/reference/index.rst
  src/PIL/Image.py
  src/PIL/ImageTransform.py
Labels: Documentation

#7693 Rename x64 to AMD64 in winbuild
  .appveyor.yml
  .github/workflows/wheels.yml
  winbuild/build.rst
  winbuild/build_prepare.py
Labels: Build, Windows

#7695 Use "non-zero" consistently
  Tests/test_file_eps.py
  Tests/test_image_resample.py
  src/libImaging/GifEncode.c
  src/libImaging/Jpeg.h
Labels: Documentation

#7703 PyPI project page URL is now lowercase
  README.md
  docs/about.rst
  docs/index.rst
  docs/installation.rst
Labels: Documentation

#7696 Add support for reading and writing grayscale PFM images
  Tests/images/hopper.pfm
  Tests/images/hopper_be.pfm
  Tests/test_file_ppm.py
  docs/handbook/image-file-formats.rst
  docs/releasenotes/10.3.0.rst
  docs/releasenotes/index.rst
  src/PIL/PpmImagePlugin.py
Labels: Enhancement

#7698 Removed PPM loop to read header tokens
  src/PIL/PpmImagePlugin.py
Labels: Cleanup

#7702 Deprecate ImageCms constants and versions() function
  Tests/test_imagecms.py
  docs/deprecations.rst
  docs/reference/ExifTags.rst
  docs/reference/ImageCms.rst
  docs/releasenotes/10.0.0.rst
  docs/releasenotes/10.3.0.rst
  docs/releasenotes/9.1.0.rst
  docs/releasenotes/9.3.0.rst
  src/PIL/ImageCms.py
Labels: Deprecation

#7701 Fix APNG info after seeking backwards more than twice
  Tests/images/apng/different_durations.png
  Tests/test_file_apng.py
  src/PIL/PngImagePlugin.py
Labels: Bug

#7707 Added type hints to ImageMath
  pyproject.toml
  src/PIL/Image.py
  src/PIL/ImageMath.py
  src/PIL/_imagingmath.pyi
Labels: Type hints

#7708 Added type hints to ImageMorph
  pyproject.toml
  src/PIL/ImageMorph.py
  src/PIL/_imagingmorph.pyi
Labels: Type hints

#7712 Added type hints for ImageShow
  pyproject.toml
  src/PIL/Image.py
  src/PIL/ImageShow.py
  tox.ini
Labels: Type hints

#7714 Added type hints to FitsImagePlugin
  src/PIL/FitsImagePlugin.py
  src/PIL/Image.py
Labels: automerge, Type hints

#7716 Added type hints to seven plugins
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/ImagePalette.py
  src/PIL/McIdasImagePlugin.py
  src/PIL/PcdImagePlugin.py
  src/PIL/PcxImagePlugin.py
  src/PIL/PixarImagePlugin.py
  src/PIL/SunImagePlugin.py
  src/PIL/XVThumbImagePlugin.py
  src/PIL/XbmImagePlugin.py
Labels: Type hints

#7719 Added type hints to MspImagePlugin
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/MspImagePlugin.py
Labels: automerge, Type hints

#7720 Added type hints to ImtImagePlugin
  src/PIL/ImtImagePlugin.py
Labels: Type hints

#7724 Added type hints to SgiImagePlugin
  src/PIL/Image.py
  src/PIL/SgiImagePlugin.py
Labels: Type hints

#7725 Added type hints to TgaImagePlugin
  src/PIL/TgaImagePlugin.py
Labels: Type hints

#7726 Added type hints to PpmImagePlugin
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/PpmImagePlugin.py
Labels: Type hints

#7727 Added type hints to GdImageFile
  src/PIL/GdImageFile.py
Labels: Type hints

#7728 Added type hints to MpegImagePlugin
  src/PIL/MpegImagePlugin.py
Labels: Type hints

#7731 Added type hints to OSS Fuzz scripts
  Tests/helper.py
  Tests/oss-fuzz/fuzz_font.py
  Tests/oss-fuzz/fuzz_pillow.py
  Tests/oss-fuzz/fuzzers.py
  Tests/oss-fuzz/test_fuzzers.py
Labels: Type hints

#7733 Added type hints to Tests/helper.py
  Tests/helper.py
Labels: Type hints

#7732 Added type hints to Tests/check_*.py
  Tests/check_fli_overflow.py
  Tests/check_imaging_leaks.py
  Tests/check_j2k_leaks.py
  Tests/check_j2k_overflow.py
  Tests/check_jpeg_leaks.py
  Tests/check_large_memory.py
  Tests/check_large_memory_numpy.py
  Tests/check_libtiff_segfault.py
  Tests/check_png_dos.py
  Tests/check_wheel.py
Labels: Type hints

#7740 Added type hints to Tests/conftest.py
  Tests/conftest.py
Labels: Type hints

#7739 Do not support using test-image-results to upload images after test failures
  Tests/helper.py
Labels: Testing

#7741 CI: Cache libimagequant on Linux builds
  .github/workflows/docs.yml
  .github/workflows/test.yml
  depends/download-and-extract.sh
  depends/install_imagequant.sh
Labels: Testing

#7754 Added type hints to additional tests
  Tests/test_image_convert.py
  Tests/test_image_copy.py
  Tests/test_image_crop.py
  Tests/test_image_frombytes.py
  Tests/test_image_fromqimage.py
  Tests/test_image_getbands.py
  Tests/test_image_getbbox.py
  Tests/test_image_getcolors.py
  Tests/test_image_getdata.py
  Tests/test_image_getim.py
  Tests/test_image_getprojection.py
  Tests/test_image_histogram.py
  Tests/test_image_point.py
  Tests/test_image_putalpha.py
  Tests/test_image_quantize.py
  Tests/test_image_resize.py
  Tests/test_image_split.py
  Tests/test_image_tobitmap.py
  Tests/test_image_tobytes.py
  Tests/test_image_transpose.py
Labels: Type hints

#7755 Added type hints to additional tests
  Tests/test_000_sanity.py
  Tests/test_binary.py
  Tests/test_file_cur.py
  Tests/test_file_ftex.py
  Tests/test_file_gbr.py
  Tests/test_file_gd.py
  Tests/test_file_gimppalette.py
  Tests/test_file_imt.py
  Tests/test_file_mcidas.py
  Tests/test_file_pcd.py
  Tests/test_file_pixar.py
  Tests/test_file_qoi.py
  Tests/test_file_wal.py
  Tests/test_file_webp_lossless.py
  Tests/test_file_xpm.py
  Tests/test_file_xvthumb.py
  Tests/test_fontfile.py
  Tests/test_format_lab.py
  Tests/test_lib_image.py
  Tests/test_locale.py
  Tests/test_main.py
  Tests/test_pyroma.py
  Tests/test_uploader.py
  Tests/test_util.py
  Tests/test_webp_leaks.py
Labels: Type hints

#7760 Remove execute bit from `setup.py`
  .pre-commit-config.yaml
  Tests/check_fli_oob.py
  Tests/check_jp2_overflow.py
  Tests/images/create_eps.gnuplot
  Tests/oss-fuzz/fuzz_pillow.py
  setup.py
Labels: Cleanup

#7766 Test on macOS M1 where available
  .github/workflows/macos-install.sh
  .github/workflows/test.yml
Labels: macOS, Testing

#7762 Pin to Python 3.9.16-1
  .github/workflows/test-cygwin.yml
Labels: Testing
