Repository python-pillow/Pillow, pull requests merged in 2025-06, with the labels that each got.

#8918 Removed unreachable code
  src/PIL/MpegImagePlugin.py
Labels: Cleanup

#8996 Fix test
  Tests/test_deprecate.py
Labels: Testing

#8998 Call startswith once with a tuple
  setup.py
Labels: Cleanup

#8863 Simplify code
  src/PIL/ImageGrab.py
  src/PIL/JpegImagePlugin.py
  src/libImaging/Arrow.c
  src/libImaging/Draw.c
Labels: Cleanup

#8984 Use mask in C when drawing wide polygon lines
  src/PIL/ImageDraw.py
  src/_imaging.c
  src/libImaging/Draw.c
  src/libImaging/Imaging.h
Labels: Performance

#8962 Clear TIFF core image if memory mapping was used for last load
  Tests/test_tiff_crashes.py
  src/PIL/TiffImagePlugin.py
  src/map.c
Labels: TIFF

#9004 Reduce number of bytes read for PCX header
  src/PIL/PcxImagePlugin.py
Labels: Performance

#9011 Test Python 3.14t on macOS and Linux
  .github/workflows/test.yml
Labels: Testing

#9017 CI: Require Python >= 3.13.5 on Windows
  .github/workflows/test-windows.yml
Labels: Windows, changelog: skip

#9014 Update libpng to 1.6.49
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#9019 Add release notes for #8912 and #8969
  docs/releasenotes/11.3.0.rst
Labels: Documentation

#9023 Deprecate saving I mode images as PNG
  Tests/test_file_png.py
  docs/deprecations.rst
  docs/releasenotes/11.3.0.rst
  src/PIL/PngImagePlugin.py
  src/PIL/_deprecate.py
Labels: Deprecation

#8871 Use same AVIF URL when fetching dependency
  winbuild/build_prepare.py
Labels: Windows, Dependency

#9002 Fix libtiff cleanup
  src/libImaging/TiffDecode.c
Labels: TIFF

#9025 Only check DHT marker for libjpeg-turbo
  Tests/test_file_jpeg.py
Labels: JPEG, Testing

#9015 Support saving I;16L TIFF images
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8994 Update ruff pre-commit ID
  .pre-commit-config.yaml
Labels: Testing

#8896 Improve SgiImagePlugin test coverage
  Tests/test_file_sgi.py
  src/PIL/SgiImagePlugin.py
Labels: Testing

#9044 Use unpacking
  src/PIL/ImageMath.py
  src/PIL/McIdasImagePlugin.py
Labels: Cleanup

#8879 Fix qtables and quality scaling
  Tests/test_file_jpeg.py
  docs/handbook/image-file-formats.rst
  src/libImaging/JpegEncode.c
Labels: JPEG
