Repository python-pillow/Pillow, pull requests merged in 2025-01, with the labels that each got.

#8654 Updated macOS tested Pillow versions
  docs/installation/platform-support.rst
Labels: Documentation, macOS

#8656 Upgrade zlib-ng to 2.2.3
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8653 Updated freetype to 2.13.3 in macOS and Linux wheels
  .github/workflows/wheels-dependencies.sh
Labels: Dependency

#8657 Add overloads for exif_transpose
  Tests/test_file_jpeg.py
  Tests/test_imageops.py
  src/PIL/ImageOps.py
Labels: Type hints

#8658 Corrected installing ImageMagick on cifuzz
  .github/workflows/wheels-dependencies.sh
Labels: Linux

#8661 Removed giflib as webp dependency
  .github/workflows/wheels-dependencies.sh
Labels: WebP

#8674 Trigger wheel builds from changes in pyproject.toml
  .github/workflows/wheels.yml
Labels: Testing

#8645 Added compile-time mozjpeg feature flag
  Tests/test_file_jpeg.py
  src/PIL/features.py
  src/_imaging.c
  src/libImaging/JpegEncode.c
Labels: JPEG

#8648 PngImageFile text is a property
  Tests/test_file_png.py
Labels: Testing

#8649 Removed unused image open
  Tests/test_file_ico.py
Labels: Cleanup, Testing

#8660 Updated TIFF decode error message string
  Tests/test_file_libtiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8652 Use namedtuple _replace
  src/PIL/BlpImagePlugin.py
  src/libImaging/Unpack.c
Labels: Cleanup

#8668 Improved SPIDER test coverage
  Tests/test_file_spider.py
Labels: Testing

#8666 Use ImageFile._Tile
  Tests/test_file_jpeg.py
Labels: Testing, Type hints

#8670 Updated libpng to 1.6.45
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8663 Allow saving multiple frames as BigTIFF
  Tests/test_file_tiff.py
  src/PIL/TiffImagePlugin.py
Labels: TIFF

#8683 Removed xfail for test_embeddable on Python 3.13
  Tests/test_image_access.py
Labels: Windows, Testing

#8684 Only F mode starts with F
  src/PIL/SpiderImagePlugin.py
Labels: Cleanup

#8679 Improved test coverage
  Tests/helper.py
  Tests/test_file_apng.py
  Tests/test_file_iptc.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_libtiff.py
  Tests/test_image.py
Labels: Testing

#8686 Skip test_embeddable if compiler cannot be initialized
  Tests/test_image_access.py
Labels: Windows, Testing

#8690 Test Python 3.14 pre-release
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#8681 Corrected argument types
  Tests/test_image.py
  Tests/test_image_resize.py
Labels: Testing, Type hints

#8696 Test Windows amd64 wheels with NumPy
  .github/workflows/wheels-test.ps1
Labels: Windows, NumPy, automerge

#8525 Test oldest Python on 32-bit Windows 2019 and remove AppVeyor
  .appveyor.yml
  .github/CONTRIBUTING.md
  .github/mergify.yml
  .github/workflows/test-windows.yml
  MANIFEST.in
  README.md
  RELEASING.md
  Tests/helper.py
  docs/about.rst
  docs/index.rst
  docs/installation/platform-support.rst
  winbuild/README.md
  winbuild/build.rst
Labels: Windows, Testing

#8689 Moved get_child_images() to ImageFile
  Tests/test_image.py
  docs/deprecations.rst
  docs/releasenotes/11.2.0.rst
  docs/releasenotes/index.rst
  src/PIL/Image.py
  src/PIL/ImageFile.py
  src/PIL/_deprecate.py
Labels: Deprecation

#8699 Added MozJPEG documentation
  docs/reference/features.rst
  docs/releasenotes/11.2.0.rst
Labels: Documentation, JPEG

#8700 Updated Ubuntu arm to 24.04 with arm64 runner
  .github/workflows/test-docker.yml
  docs/installation/platform-support.rst
Labels: Linux, Testing

#8710 Updated libimagequant to 4.3.4
  depends/install_imagequant.sh
  docs/installation/building-from-source.rst
Labels: Dependency

#8712 Updated libpng to 1.6.46
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8711 Updated xz to 5.6.4
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8688 Updated harfbuzz to 10.2.0
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8707 Use monkeypatch
  Tests/check_png_dos.py
  Tests/test_decompression_bomb.py
  Tests/test_file_fli.py
  Tests/test_file_gif.py
  Tests/test_file_ico.py
  Tests/test_file_jpeg.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_libtiff.py
  Tests/test_file_png.py
  Tests/test_file_tiff.py
  Tests/test_file_webp.py
  Tests/test_imagefile.py
  Tests/test_map.py
Labels: Testing

#8705 Fixed unclosed file warnings
  Tests/test_file_libtiff.py
Labels: Testing

#8717 Use Py_RETURN_NONE macro when possible
  src/_imaging.c
  src/_imagingcms.c
  src/_imagingft.c
  src/_imagingmath.c
  src/_imagingtk.c
  src/decode.c
  src/display.c
  src/encode.c
  src/libImaging/Except.c
  src/libImaging/Imaging.h
  src/outline.c
  src/path.c
Labels: Cleanup

#8709 Seek relative to current position
  src/PIL/BufrStubImagePlugin.py
  src/PIL/GribStubImagePlugin.py
  src/PIL/Hdf5StubImagePlugin.py
Labels: Cleanup

#8723 Fixed exceptions when closing AppendingTiffWriter
  Tests/test_file_tiff.py
Labels: TIFF, Testing
