Repository python-pillow/Pillow, pull requests merged in 2025-02, with the labels that each got.

#8725 Revert "Ignore brew dependencies for libraqm on macOS 13"
  .github/workflows/macos-install.sh
Labels: macOS, Testing

#8727 Use getpixel() instead of load()
  Tests/test_file_gif.py
  Tests/test_image.py
  Tests/test_image_convert.py
  Tests/test_image_quantize.py
  Tests/test_imageops.py
  Tests/test_numpy.py
Labels: Cleanup, Testing

#8732 Removed redundant argument parsing
  src/_imaging.c
Labels: Cleanup

#8733 Simplify Python code by passing tuples to C
  Tests/test_color_lut.py
  src/PIL/ImageFilter.py
  src/PIL/ImageFont.py
  src/PIL/JpegImagePlugin.py
  src/PIL/WebPImagePlugin.py
  src/PIL/_imagingft.pyi
  src/_imaging.c
  src/_imagingft.c
  src/_webp.c
  src/encode.c
Labels: Cleanup

#8735 Updated AffineTransform docstring to mention it uses the inverse matrix
  src/PIL/ImageTransform.py
Labels: Documentation

#8740 Simplify Python code by receiving tuple from C
  src/PIL/WebPImagePlugin.py
  src/_webp.c
Labels: Cleanup, WebP

#8739 Use boolean format argument for irreversible
  src/encode.c
Labels: Cleanup

#8747 Use monkeypatch
  Tests/test_file_gif.py
Labels: Testing

#8744 Updated libimagequant to 4.3.4 on Windows
  winbuild/build_prepare.py
Labels: Windows, Dependency

#8745 Updated zlib-ng to 2.2.4
  .github/workflows/wheels-dependencies.sh
  winbuild/build_prepare.py
Labels: Dependency

#8752 Removed unused test code
  Tests/helper.py
Labels: Cleanup, Testing

#8753 Remove unused `bdf_slant` and `bdf_spacing` variables
  src/PIL/BdfFontFile.py
Labels: Cleanup

#8755 Remove debug `Image._wedge`
  Tests/test_file_gif.py
  Tests/test_format_hsv.py
  src/PIL/Image.py
  src/_imaging.c
Labels: Cleanup

#8673 Rewrite the install_name of the ZLIB-NG library on macOS
  .github/workflows/wheels-dependencies.sh
  pyproject.toml
Labels: Build, macOS

#8754 Don't call `make clean` or `pip` in tox
  tox.ini
Labels: Testing

#8758 Add PyPy3.11 to CI
  .ci/install.sh
  .github/workflows/test-windows.yml
  .github/workflows/test.yml
Labels: Testing

#8748 Only crop GIF frames when saving with disposal method 2 if transparency is present
  Tests/test_file_gif.py
  src/PIL/GifImagePlugin.py
Labels: GIF

#8738 Pass CFLAGS to build_simple directly
  .github/workflows/wheels-dependencies.sh
Labels: Cleanup

#8741 Use member names to initialize PyTypeObjects
  src/_imaging.c
  src/_imagingcms.c
  src/_imagingft.c
  src/_webp.c
  src/decode.c
  src/display.c
  src/encode.c
  src/outline.c
  src/path.c
Labels: Cleanup

#8618 Improve type checking in tests
  Tests/test_file_dds.py
  Tests/test_file_eps.py
  Tests/test_file_gbr.py
  Tests/test_file_gif.py
  Tests/test_file_icns.py
  Tests/test_file_ico.py
  Tests/test_file_jpeg2k.py
  Tests/test_file_ppm.py
  Tests/test_file_tga.py
  Tests/test_file_wal.py
  Tests/test_file_wmf.py
  Tests/test_image.py
  Tests/test_image_convert.py
  Tests/test_image_transform.py
  Tests/test_imagepalette.py
Labels: Testing, Type hints

#8759 Improve TarIO test coverage
  Tests/test_file_tar.py
Labels: Testing, automerge

#8760 Corrected type check
  Tests/test_file_gbr.py
Labels: automerge, Type hints

#8762 Improved SunImagePlugin coverage
  Tests/test_file_sun.py
Labels: Testing

#8763 Update Sphinx to 8.2 to remove nitpick ignore
  docs/conf.py
  pyproject.toml
Labels: Documentation

#8765 Improved MpoImagePlugin test coverage
  Tests/test_file_mpo.py
Labels: Testing

#8771 Improved FontFile test coverage
  Tests/test_fontfile.py
Labels: Testing
